### ISSUE TITLE
find_bucket_by_name Returns invalid bucket

### ISSUE THREAD

**Issue by AlenBadel** [influxdata/influxdb-client-python#104]
Using:

```
client = InfluxDBClient('<url>','<token>')
bucket_api = client.buckets_api()
bucket_name = "Invalid Bucket"
bucket_response = bucket_api.find_bucket_by_name(bucket_name)
```

Given the name of a bucket that doesn't exist, `find_bucket_by_name `will return one of the system buckets. 

Looks like the API call will always return a response with all system buckets included. If the name of the bucket is valid, you'll find the bucket with that name at index 0.

API Call:
https://github.com/influxdata/influxdb-client-python/blob/fdec77d8db34a1acc14feb0bb5642d3ce51c1e9f/influxdb_client/service/buckets_service.py#L551-L565

`find_bucket_by_name` returns the bucket at index 0. If the name of the bucket is a valid bucket it will return the valid bucket, otherwise it will return one of the system buckets.

https://github.com/influxdata/influxdb-client-python/blob/fdec77d8db34a1acc14feb0bb5642d3ce51c1e9f/influxdb_client/client/bucket_api.py#L75-L81

Is this known behavior? I expected that the API return None if we're passing the name of a bucket that doesn't exist. 

Using this workaround for now: 
https://github.com/AlenBadel/influxdb-client-python/commit/877ad50f83adb8dbfefa5d33f26c49ae1541a80e

**Comment by bednar** [comment]
Hi @AlenBadel,

thanks for using our client It's an issue in InfluxDB - https://github.com/influxdata/influxdb/issues/14900. 

Please vote up for https://github.com/influxdata/influxdb/issues/14900 to escalate it.

Regards
