### ISSUE TITLE
How to retrieve every single Time Series from a bucket

### ISSUE THREAD

**Issue by emanuelef** [influxdata/influxdb-client-python#109]
Hi,
I'm looking for the best way to fetch every single time series from a bucket.
I have a bucket with many different measurements and each has different tags, is there any example on how to query (maybe with a stream) in order to get every possible TS in the bucket ?
Thanks a lot for the great work.

**Comment by bednar** [comment]
Hi @emanuelef,

thanks for using our client.

For retrieve all data from bucket you could use something like:

```python
large_stream = query_api.query_stream('from(bucket:"my-bucket") |> range(start: 1970)')
for record in large_stream:
    if record["location"] == "New York":
        print(f'New York temperature: {record["_value"]}')
        break
```

For detail see: https://github.com/influxdata/influxdb-client-python/blob/f247f233ca87ce5471011e86b6ca3a0157b61cd7/examples/query.py#L42

Regards

**Comment by emanuelef** [comment]
Thanks for the quick reply.
What I'm trying to do is to write a generic code that can give me all the Time Series present.
This means I don't know statically all the tags present.
I presume I'd need to use keys() and other functions for getting the metadata but it's not clear how to get all the combinations of tags/values.

**Comment by bednar** [comment]
I am not expert in the Flux lang, but what about:

> All keys
```flux
import "influxdata/influxdb/v1"

v1.tagKeys(
  bucket: "my-bucket",
  predicate: (r) => r._measurement == "my-measurement",
  start: duration(v: uint(v: 1970-01-01) - uint(v: now()))
)
|> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
```

> All series
```flux
from(bucket: "my-bucket")
  |> range(start: 1970)
  |> filter(fn: (r) => r["_measurement"] == "my-measurement")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> limit(n:1)
  |> keep(columns: ["tag1", "tag2", ...])
```

Maybe you could try ask at our [![Slack Status](https://img.shields.io/badge/slack-join_chat-white.svg?logo=slack&style=social)](https://www.influxdata.com/slack) channel.

Regards

**Comment by emanuelef** [comment]
Thanks, I'll try what you suggested and on the Slack channel as well.
Is there v1.tagKeys in influxdb-client-python ?

**Comment by bednar** [comment]
The client should supports all types of Flux queries. 

You could define your query in a separate file and used with query api. See this example:

https://github.com/influxdata/influxdb-client-python/blob/93fca3157364792f8694a8d0aade3b8662a0d8e8/examples/query_from_file.py#L36
