### ISSUE TITLE
Pandas DataFrame Query Broken

### ISSUE THREAD

**Issue by dp1140a** [influxdata/influxdb-client-python#111]
As of 17JUN2020 the Pandas Dataframe query is broken.  It now returns a Python list.  For instance:
query = [SOME VALID FLUX QUERY]
df = client.query_api().query_data_frame(query)
df.head()

AttributeError: 'list' object has no attribute 'head'

This worked just fine right up until today.

**Comment by supermar1010** [comment]
Hey sorry to dig this up, but I have exactly the same problem, but with version 1.18. As you closed this right away, was there any mistake on your side?
