### ISSUE TITLE
Creating buckets using BucketsApi

### ISSUE THREAD

**Issue by MajorCarrot** [influxdata/influxdb-client-python#119]
On using BucketsApi from influxdb_client, if the org_id is not passed, the api updates the org_id with the org field from influxdb_client (which is a name). Ref: 
https://github.com/influxdata/influxdb-client-python/blob/91ffed11c270c295a93b3e7d0b94a69b4657a917/influxdb_client/client/bucket_api.py#L39

A possible option would be to load the influxdb_client with the org_id during initialization, so that the org_id can be used instead of org_name.

**Comment by bednar** [comment]
Hi @MajorCarrot,

thanks for using our client.

You could set `org_id` as a field of `influxdb_client`. This code is pretty fine and will be works:

```python
influxdb_client  = InfluxDBClient(url="http://localhost:9999", token="my-token", org="05ebba61321e9000")
```

Regards

**Comment by MajorCarrot** [comment]
I know (and am using that), but the org_id is an optional parameter and ignoring it raises an error!

**Comment by bednar** [comment]
Could you please share a snippet of  your code to better understanding what is a problem?

You have two options how to create bucket:

1. By `bucket` parameter 

```python
buckets_api = self.client.buckets_api()

bucket = PostBucketRequest(name="my-bucket", retention_rules=[], description="description", org_id=my_org.id)
my_bucket = buckets_api.create_bucket(bucket=bucket)
```

2. By specify values of `PostBucketRequest`

```
buckets_api = self.client.buckets_api()

my_bucket = buckets_api.create_bucket(bucket_name="my-bucket", org_id=my_org.id)
```

The `org_id` is required by InfluxDB.
