### ISSUE TITLE
Nanoseconds ignored when writing Points with RFC string format

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-client-python#124]
See: https://github.com/influxdata/influxdb-python/issues/829#issuecomment-650468586

I believe this library suffers the same problem.

https://github.com/influxdata/influxdb-client-python/blob/8c167e9a4880472c5df1043630934fb76c451b61/influxdb_client/client/date_utils.py#L10

**Comment by bednar** [comment]
> As you mentioned the `datetime` has a precision to microseconds and also almost all time libraries are without supports of nanoseconds:
> 
> - [pendelum](https://github.com/sdispater/pendulum/)
> - [udatetime](https://github.com/freach/udatetime)
> - [isodate](https://github.com/gweis/isodate/)
> - [arrow](https://github.com/crsmithdev/arrow)
> 
> We will have to use something like [pandas timestamp](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html):
> 
> ```python
> >>> import pandas as pd
> >>> pd.to_datetime('1996-02-25T21:20:00.001001231Z', unit='ns')
> Timestamp('1996-02-25 21:20:00.001001231+0000', tz='UTC')
> 
> ```

**Comment by bednar** [comment]
Hi @fcoetzee,

we preparing workaround by [pandas.Timestamp](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html#pandas.Timestamp). 

For detail info see #141 or this example [nanosecond_precision.py](https://github.com/influxdata/influxdb-client-python/blob/feat/nanoseconds/examples/nanosecond_precision.py).

Regards
