### ISSUE TITLE
Simple way to test connection and auth info

### ISSUE THREAD

**Issue by mdegat01** [influxdata/influxdb-client-python#131]
__Proposal:__
When using this library if the config information (url, org, bucket and token) is collected from users then there needs to be a way to test that configuration to see if:
- There is an Influx 2.0 deployment listening at that URL
- The Org, Bucket and Token details provided are valid at that URL
- The token has the required permissions based on the use case (Read and/or Write to that org and bucket)

I think the library should include a simple way to do this test which succeeds without exception on success and fails with an exception otherwise.

__Current behavior:__
I believe the best way available to do this test today is the following:
- To test a write, do a synchronous write of `b""`. On success it will fail with an Invalid Inputs`ApiException` with the message 'writing requires points'. On failure it will return a `urllib3.exceptions.MaxRetryError` on connection failure and an Unauthorized `ApiException` if the other config is invalid or a permissions failure.
- To test a read, execute a query of `buckets()`. This returns the buckets that can be seen with the provided config on success. On failure it will return a `urllib3.exceptions.MaxRetryError` on connnection failure and an Unauthorized `ApiException` if the config is invalid

__Desired behavior:__
First, assuming I am correct about those being the ideal ways to do a test read and write it would be good if they were added to the doc as cookbook examples.

Also ideally the test write should only throw an exception in case of failure. Perhaps instead of using the normal `write` method for this test then `write_api` could have a `test` method that does a `write(b"")` behind the scenes and only returns an exception in case of connection or authorization failure?

__Alternatives considered:__
I noticed that the `InfluxDBClient` class also has a method called `health` and `ready` which seem like they should be usable for doing a connection check. I wasn't sure how to make them work though or if they were implemented yet.

__Use case:__
I feel like users of this library will often be collecting config information that they then need to test. Even if no enhancements are prioritized at this time around this it would be good if the documentation included an example of the best practice way to do this.

**Comment by bednar** [comment]
Hi @mdegat01,

the `health()`  is useful to check the connection. Try this code:

```python
from influxdb_client import InfluxDBClient

client = InfluxDBClient(url="http://localhost:9999",
                        token="my-token",
                        org="my-org",)

health = client.health()
if health.status == "pass":
    print("Connection success.")
else:
    print(f"Connection failure: {health.message}!")

client.__del__()
```

I will take a look to solution for check permission to the `read` and  the `write` from a particular `bucket`.

Regards

**Comment by bednar** [comment]
Hi @malwinweiler,

currently the InfluxDB doesn't have API to test the token to have appropriate rights. 

You can use something similar as is in this pending PR: https://github.com/influxdata/influxdb-client-python/pull/269/files#diff-294bf3f7a19058974064e47c8e95dce7383a1716d1e59822a81fefca09ce7d48

Regards
