### ISSUE TITLE
Writing Dataframe to InfluxDB returns status code 204, however data set is not in measurement

### ISSUE THREAD

**Issue by masonhuemmer** [influxdata/influxdb-client-python#133]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Query InfluxDB using .query_data_frame()
2. Manipulate Dataframe
3. Write Updated Dataframe to InfluxDB using **data_frame_measurement_name** parameter

__Expected behavior:__
Describe what you expected to happen.
- When I write to InfluxDB using **data_frame_measurement_name** parameter, I receive a 204 status code. I should be able to query the measurement and return the data set I just imported.

__Actual behavior:__
Describe What actually happened.
- When I write to InfluxDB using **data_frame_measurement_name** parameter, I receive a 204 status code. However, when I go to query the measurement, I am unable to find the data I just imported.

__Specifications:__
 - Client Version: 1.8.0
 - InfluxDB Version: 2.0.0-beta.14
 - Platform: WSL 2.0 - Ubuntu 20.04

![image](https://user-images.githubusercontent.com/49791141/87592181-0e513180-c6af-11ea-9d4f-57bafedbed79.png)

![image](https://user-images.githubusercontent.com/49791141/87592217-1f01a780-c6af-11ea-9b88-cfbe75042dcb.png)

**Comment by bednar** [comment]
Hi @masonhuemmer,

thanks for using our client.

1/ The `unix_dt` has milliseconds precision so you have to set this precision to the `write` method:

```python
from influxdb_client import WritePrecision
write_api.write(bucket='default', record=category_frequency, write_precision=WritePrecision.MS,
                data_frame_measurement_name="borough")
```

2/ The `category_frequency.set_index("_time")` is immutable method so you have to set results to `category_frequency`:

```python
category_frequency = category_frequency.set_index("_time")
```

3/ The `category_frequency["_time"] = unix_dt` causes that all of rows in DataFrame will have same timestamp and produce these LineProtocols:

```
borough class=4.0,frequency=30.68 1594843919628
borough class=3.0,frequency=29.51 1594843919628
borough class=1.0,frequency=21.85 1594843919628
...
```

Only the latest record will be saved - see [time-series](https://v2.docs.influxdata.com/v2.0/reference/glossary/#time-series-data)

Regards
