### ISSUE TITLE
Unable to use line protocol to write data.

### ISSUE THREAD

**Issue by dans-acc** [influxdata/influxdb-client-python#135]
Hello,

I am unable to write data using the line protocol. Here is the code utilised to try and achieve this.

**Creating the write API:**
```python
write_options = ifx.WriteOptions(write_type=ifx.client.write_api.WriteType.asynchronous,
                                             batch_size=1)
ifx_write_api = self._ifx_client.write_api(write_options=write_options)
```

**The following code is used to generate the record:**
```python
f"{self.apca_res},symbol={bar['symbol']} " \
f"o={bar['o']:.4f},h={bar['h']:.4f},l={bar['l']:.4f},c={bar['c']:.4f},v={bar['v']}i " \
f"{bar['time']}"
```
_This in turn prints:_
A,symbol=TEST o=99.0000,h=99.0000,l=99.9000,c=99.5000,v=100i 1

**The following code is used to write:**
```python
ifx_write_api.write(bucket=self.ifx_bucket_name, org=self.ifx_org_id,
                                                record=record)
```

_There are no erros, nothing within the logs etc. When the bucket is deleted, the code takes care of creating it etc. To this extent, everything is created. Though calling .get() on the write results in None(?)_

I'd very much appreciate any hep regarding this matter, I was not sure if this was a bug or-

Best

**Comment by dans-acc** [comment]
Moreover, does changing the write scheduler mumber of workers yield better performance? When should this be increased etc?

**Comment by bednar** [comment]
Hi @dans-acc,

If you would like to use the `asynchronous` write you should call `get()` on writes result. Something like:

```python
from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import ASYNCHRONOUS

client = InfluxDBClient(url="http://localhost:9999", token="my-token", org="my-org")
write_api = client.write_api(write_options=ASYNCHRONOUS)

_point1 = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3)
_point2 = Point("my_measurement").tag("location", "New York").field("temperature", 24.3)

async_result = write_api.write(bucket="my-bucket", record=[_point1, _point2])
async_result.get()

client.__del__()
```

- https://github.com/influxdata/influxdb-client-python#asynchronous-client
- https://kite.com/python/docs/multiprocessing.pool.ApplyResult

Regards

**Comment by dans-acc** [comment]
Hello, @bednar,

Sorry, maybe I should have stated this earlier. The solution you posit was already tried (the asynchronous write options) to no avail; the solution I posted was an attempt to explore various solutions of the stated issue.

_If I delete the bucket, my code takes care of creating it. However, when it comes to writing, no measurements get written into it._ Could this be a permission related issue, or-? But I should note that I have looked at the permissing and both read and write have been granted. Personally, I initially thought I had messed up the line protocol somehow.

Best.

**Comment by bednar** [comment]
Hi @dans-acc,

please, could you share output from debug mode?

```python
client = InfluxDBClient(url="http://localhost:9999", token="my-token", org="my-org", debug=True)
``` 

Regards

**Comment by dans-acc** [comment]
/home/doombana/miniconda3/envs/pennywise-env/bin/python /home/doombana/Workbench/PennyWise/pennywise/market/__main__.py
send: b'GET /api/v2/orgs/ORG_NAME HTTP/1.1\r\nHost: DB_ADDRESS:9999\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nAuthorization: Token TOKEN_THAT_WAS_GENERATED_BY_DB==\r\nUser-Agent: influxdb-client-python/1.9.0\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json; charset=utf-8
header: Date: Mon, 20 Jul 2020 22:56:14 GMT
header: Content-Length: 629
InfluxDB organisation ORG_NAME exists.
send: b'GET /api/v2/buckets?name=market HTTP/1.1\r\nHost: DB_ADDRESS:9999\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nAuthorization: Token TOKEN_THAT_WAS_GENERATED_BY_DB==\r\nUser-Agent: influxdb-client-python/1.9.0\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json; charset=utf-8
header: Date: Mon, 20 Jul 2020 22:56:14 GMT
header: Content-Length: 845
InfluxDB bucket market exists.
send: b'GET /health HTTP/1.1\r\nHost: DB_ADDRESS:9999\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nAuthorization: Token TOKEN_THAT_WAS_GENERATED_BY_DB==\r\nUser-Agent: influxdb-client-python/1.9.0\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json; charset=utf-8
header: Date: Mon, 20 Jul 2020 22:56:14 GMT
header: Content-Length: 144
Test data that is to be written: A,symbol=TEST o=99.0000,h=99.0000,l=99.9000,c=99.5000,v=100i 1
send: b'POST /api/v2/write?org=ORG_NAME&bucket=market&precision=ns HTTP/1.1\r\nHost: DB_ADDRESS:9999\r\nAccept-Encoding: identity\r\nContent-Length: 62\r\nContent-Encoding: identity\r\nContent-Type: text/plain\r\nAccept: application/json\r\nAuthorization: Token TOKEN_THAT_WAS_GENERATED_BY_DB==\r\nUser-Agent: influxdb-client-python/1.9.0\r\n\r\n'
send: b'A,symbol=TEST o=99.0000,h=99.0000,l=99.9000,c=99.5000,v=100i 1'
reply: 'HTTP/1.1 204 No Content\r\n'
header: Date: Mon, 20 Jul 2020 22:56:14 GMT
None

_The last none represents the .get() called on the object returned by .write(...)_

**Comment by bednar** [comment]
Data was successfully written. As you see here:

```
send: b'A,symbol=TEST o=99.0000,h=99.0000,l=99.9000,c=99.5000,v=100i 1'
reply: 'HTTP/1.1 204 No Content\r\n'
```

The timestamp is `1 ns` which is `1970-01-01T00:00:00.000000001Z`. Use this query to show your line protocol:

```flux
from(bucket: "market")
  |> range(start: 1970-01-01T00:00:00.000000001Z)
  |> filter(fn: (r) => r["_measurement"] == "A")
```
