### ISSUE TITLE
influxdb_client.rest.ApiException: (401) Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'Cache-Control': 'must-revalidate', 'Www-Authenticate': 'Basic realm="Auth required"'

### ISSUE THREAD

**Issue by pradipneupane** [influxdata/influxdb-client-python#138]
Hello,
I am using influxdb 1.8 and flux is enabled. I am trying to connect to influx db using username and password by following this examples link:  https://github.com/influxdata/influxdb-client-python/blob/master/examples/influxdb_18_example.py , unfortunately, I get 401 error whenever I tried to use query to the client. 

I am connecting via https and using verify_ssl = False.  I am using this version of influxdb as Verify_ssl was available here.  : pip install git+https://github.com/influxdata/influxdb-client-python.git@master

I tried to use this way: https://username:password@url.com and also tried to pass this username and password to token parameter in InfluxdbClient like in the example provided in that link.  None of these seems to work. 

After that I tried to use directly from the python request library, and that seems to be working correctly, I was able to connect and get the proper status code. So, the problem seems to be from the influxdb_client. 

Any information, how can I connect to influxdb using username and password via https with this python client? 

p.s Before I was using old python influx client for 1.8 and it worked without any issues there with that username and password for https. https://github.com/influxdata/influxdb-python.

**Comment by bednar** [comment]
Hi @pradipneupane,

thanks for using our client.

Could you share an output from debug log? You could enable debug logging by `debug` property:

```python
client = InfluxDBClient(url="http://localhost:9999", token="my-token", org="my-org", debug=True)
```


Regards

**Comment by pradipneupane** [comment]
hello,
Thanks for the reply. I run in debug mode and there it contains:
`POST /api/v2/query?org='my-org',Host:'url.com'` and most important, for the token, it contains `Token username:password`

and this is what contains at the end:

```
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Cache-Control: must-revalidate
header: Www-Authenticate: Basic realm="Auth required"
header: Date: Fri, 31 Jul 2020 11:24:42 GMT
header: Content-Length: 14
header: Content-Type: text/plain; charset=utf-8
```

**Comment by bednar** [comment]
Do you have auth proxy before InfluxDB or the authentication is managed by InfluxDB? 
Could you share a configuration of InfluxDB (`influxdb.conf`)?

**Comment by pradipneupane** [comment]
`influxdb.conf` is the default generated configuration except ` enabled-flux =true`. 

```
[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  suppress-write-log = false
  write-tracing = false
  flux-enabled = true
  flux-log-enabled = true
  pprof-enabled = true
  pprof-auth-enabled = false
  debug-pprof-enabled = false
  ping-auth-enabled = false
  prom-read-auth-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  https-private-key = ""
  max-row-limit = 0
  max-connection-limit = 0
  shared-secret = ""
  realm = "InfluxDB"
  unix-socket-enabled = false
  unix-socket-permissions = "0777"
  bind-socket = "/var/run/influxdb.sock"
  max-body-size = 25000000
  access-log-path = ""
  max-concurrent-write-limit = 0
  max-enqueued-write-limit = 0
  enqueued-write-timeout = 30000000000
```
I am not sure about the auth proxy because I haven't configured anything there. I have the username and password and I think the authentication is managed by influxdb because it works without any issues with old version of influxdb python client:  `https://influxdb-python.readthedocs.io/en/latest/api-documentation.html`. I enter the username and password as it is there and it works without any issue.  I use `https `and for that, I use `verify_ssl = False`

**Comment by bednar** [comment]
Thanks for detail info. The client uses [compatibility api](https://docs.influxdata.com/influxdb/v1.8/tools/api#influxdb-2-0-api-compatibility-endpoints) that its different from v1 client.

Why is your HTTP authentication disabled by: `auth-enabled = false`?

- https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#auth-enabled-false

Could you test a simple request against compatibility endpoint? Something like:

```
curl -XPOST localhost:8086/api/v2/query -sS \
  -H 'Accept:application/csv' \
  -H 'Content-type:application/vnd.flux' \
  -H 'Authorization: Token username:password' \
  -d 'from(bucket:"telegraf")
        |> range(start:-5m)
        |> filter(fn:(r) => r._measurement == "cpu")'
```

**Comment by pradipneupane** [comment]
With this curl, I get 401, so basically unauthorized.

**Comment by bednar** [comment]
Did you change `username:password` to correct value?

**Comment by pradipneupane** [comment]
yes I did. I have a url of https I use python request library to send a request using Token username:password and it came back as 401.

**Comment by bednar** [comment]
Ok, if you got 401 then your `username` and `password` be probably wrong. Try to find correct username/password via CLI: https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization#authenticate-with-the-cli

**Comment by pradipneupane** [comment]
Thanks for you help I will look on that. But one question is that the same username and password works for the another old python client but it doesn't work for the new python client.  does `Token username:password` is different from the `username=username` and `password=password` from the old influxdb-python 5.3.0 ?

**Comment by pradipneupane** [comment]
Also, if I do this: this also works with the same username and password:

```
import requests

headers = {
    'Accept': 'application/csv',
    'Content-type': 'application/vnd.flux',
}

response = requests.post('https://url.com', headers=headers, data=query, verify=False,
                         auth=(username, password))
print(response.status_code)
```

**Comment by bednar** [comment]
@pradipneupane, yes there is a difference. 

The new client uses `Token` schema for authorization, but the old one uses authorization via `u` and `p` query parameters.

The following code uses authorization via HTTP basic which is not supported in InfluxDB 2:
> Also, if I do this: this also works with the same username and password:
> 
> ```
> import requests
> 
> headers = {
>     'Accept': 'application/csv',
>     'Content-type': 'application/vnd.flux',
> }
> 
> response = requests.post('https://url.com', headers=headers, data=query, verify=False,
>                          auth=(username, password))
> print(response.status_code)
> ```




- https://v2.docs.influxdata.com/v2.0/security/tokens/
- https://docs.influxdata.com/influxdb/v1.8/tools/api/#query-string-parameters-1
- https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#authenticate-requests

**Comment by pradipneupane** [comment]
Hi @bednar,
Thanks for the detail explanation.  This is  very clear and I know understand what is the problem. So, what option do I have for influx, 1.8 ?  Should I generate the token for 1.8 and use that token authorization process instead of using the username and password?

**Comment by bednar** [comment]
1. Configure your InfluxDB v1.8 to use authentication: https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#authentication
2. Test your configuration with this script (replace `username`, `password`, `telegraf`, `url` with correct values):
```python
import requests

headers = {
    'Accept': 'application/csv',
    'Content-type': 'application/vnd.flux',
    'Authorization': 'Token username:password',
}

data = {
  'from(bucket:"telegraf")\n        |> range(start:-5m)\n        |> filter(fn:(r) ': '> r._measurement == "cpu")\n```'
}

response = requests.post('http://localhost:8086/api/v2/query', headers=headers, data=data)
```
3. Use this client as is described here: https://github.com/influxdata/influxdb-client-python/blob/master/examples/influxdb_18_example.py

**Comment by pradipneupane** [comment]
Thank you for your help :)

**Comment by bednar** [comment]
You are welcome
