### ISSUE TITLE
Document a simple example of deleting measurement

### ISSUE THREAD

**Issue by MatinF** [influxdata/influxdb-client-python#146]
We're looking to use the API to delete specific measurements from an InfluxDB 2.0 cloud instance. 

We've set up a client as below, but I've been unable to find an example of how to delete a specific measurement based on this?

```
client = InfluxDBClient(
        url=inputs.influx_url, token=inputs.token, org=inputs.org_id, debug=False
    )
```

**Comment by bednar** [comment]
Hi @MatinF,

thanks for using our client. You could use something like:

```python
start = "1970-01-01T00:00:00Z"
stop = "2021-01-01T00:00:00Z"
delete_api = client.delete_api()
delete_api.delete(start, stop, '_measurement="sensorData"', bucket_id=bucket_id, org_id=organization_id)
```

Regards

**Comment by MatinF** [comment]
Perfection, thank you.

**Comment by MatinF** [comment]
Hi again,

This approach seems to not work consistently with the more recent InfluxDB cloud instances - is the syntax different for those?
