### ISSUE TITLE
where is the doc?

### ISSUE THREAD

**Issue by tcapelle** [influxdata/influxdb-client-python#155]
I see that there is no doc yet...
Please put an initial version so I can contribute filling it.

**Comment by bednar** [comment]
Hi @tcapelle,

the sources for doc are here: https://github.com/influxdata/influxdb-client-python/tree/master/docs and they are deployed to `readthedocs.io` - https://influxdb-client.readthedocs.io/en/latest/?badge=latest.

Regards

**Comment by tcapelle** [comment]
would you mind putting a link on the repo?

**Comment by bednar** [comment]
Docs are in this repo in directory `docs`.

**Comment by tcapelle** [comment]
I got it, but put a link in the `about` of this repo to the rendered docs.

**Comment by bednar** [comment]
This way?

![Screenshot 2020-09-17 at 07 15 29](https://user-images.githubusercontent.com/455137/93423166-a2a96180-f8b5-11ea-812c-8c6252a8215e.png)

**Comment by tcapelle** [comment]
yeah! :)

**Comment by bednar** [comment]
🎉  :)
