### ISSUE TITLE
Possibility to pass custom ssl cert

### ISSUE THREAD

**Issue by PhilippSelenium** [influxdata/influxdb-client-python#157]
__Proposal:__
Possibility to pass custom ssl cert like in the old API: https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L108

__Current behavior:__
Monkey patching
```
class _CustomConfiguration(client.influxdb_client._Configuration):
    def __init__(self):
        super().__init__()
        self.ssl_ca_cert = "custom_path"
client.influxdb_client._Configuration = _CustomConfiguration
```

__Desired behavior:__
Possibility to pass ssl cert

__Alternatives considered:__
Monkey patching

__Use case:__
Sitting behind a company proxy that requires you to use a custom CA

**Comment by bednar** [comment]
Hi @PhilippSelenium,

thanks for your proposal. I will take a look ASAP.

Regards

**Comment by bednar** [comment]
Hi @PhilippSelenium,

I've prepared PR #158.

If you would like to test it then install client via:

pip install git+https://github.com/influxdata/influxdb-client-python.git@feat/cert-configuration

Regards

**Comment by PhilippSelenium** [comment]
Thanks a lot for the quick fix. Works great!

**Comment by bednar** [comment]
You are welcome.
