### ISSUE TITLE
Failing to write DataFrame

### ISSUE THREAD

**Issue by wolfig** [influxdata/influxdb-client-python#162]
I am quite confident that this is not a bug, but maybe the documentation should be improved.

I run a Python unit test with the following code against my database:

Unit test calls method:

    def writeDataFrame(self, dataFrame: pd.DataFrame, measurement_name: str, tag_columns_names: list = [],
                       mode: str = 'SYNC', write_precision: WritePrecision = WritePrecision.NS):

        write_options = SYNCHRONOUS
        if mode == 'ASYNC':
            write_options = ASYNCHRONOUS

        try:
            return self._influxClient \ # influx client conecting to my server
                .write_api(write_options=write_options) \
                .write(bucket=self._databaseName, org=self._organization, record=dataFrame,
                       write_precision=write_precision, data_frame_measurement_name=measurement_name,
                       data_frame_tag_columns=tag_columns_names)
        except Exception as err:
            print('Error during write: ', err)
            exit()

Unit test:

    def testWriteDataFrameSynchronous(self):
        seed(2)

        theDataFrame: DataFrame = DataFrame()
        theIndex: list = list()

        # produce some data...
        for loop in range(20):
            dataDict = dict()
            for i in range(10):
                dataDict['random_' + str(i)] = random()
            dataDict['time'] = int(datetime.now().timestamp() * 10 ** 9)
            newSeries = Series(dataDict)

            theDataFrame = theDataFrame.append(newSeries, ignore_index=True)
            
        theDataFrame.set_index('time')
        writeDataFrame(theDataFrame, measurement_name='unit_test')

The code runs through without errors, `writeDataFrame(..)` returns None. However, I cannot see any data in my database (I am using Grafana to display data). I have a similar unit test using SYNC/ASYNC writing of a single influx Point or SYNC writing of a couple of Points, which work fine and leave traces in the DB.

__Steps to reproduce:__
Run code above against an InfluxDB 1.8.

__Expected behavior:__
Data should be visible in database.

__Actual behavior:__
Data written via DataFrame is not visible in DB

__Specifications:__
 - Client Version: influx_client 1.11.0
 - InfluxDB Version: 1.8
 - Platform: Python 3.7 on Windows10 calling influxDB self-hosted on Debian 9 server.

**Comment by bednar** [comment]
@wolfig thanks for issue, we will take a look

**Comment by bednar** [comment]
Hi @wolffcm,


DataFrame that you create doesn't have correctly specified `index`. Result of `theDataFrame.set_index('time')` should be used as `theDataFrame`. 

You could use something like:

```python
def testWriteDataFrameSynchronous(self):
        seed(2)

        theDataFrame: DataFrame = DataFrame()
        theIndex: list = list()

        # produce some data...
        for loop in range(20):
            dataDict = dict()
            for i in range(10):
                dataDict['random_' + str(i)] = random()
            #  
            # just use `datetime.now()`
            #
            dataDict['time'] =  datetime.now()
            newSeries = Series(dataDict)

            theDataFrame = theDataFrame.append(newSeries, ignore_index=True)
          
        #  
        # use dataframe with new `index`
        #
        theDataFrame = theDataFrame.set_index('time')
        writeDataFrame(theDataFrame, measurement_name='unit_test')
```

Regards
