### ISSUE TITLE
Asynchronous `writer_client.write(…)` loses data when program terminates normally

### ISSUE THREAD

**Issue by wolever** [influxdata/influxdb-client-python#165]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a script:

```python
#!/usr/bin/env python
client = InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org")
write_client = client.write_api()
write_client.write("my-bucket", "my-org", "example,foo=bar some_value=1.0 1")
```

2. Run the script

3. Notice that data is lost, as the write is never sent to the database 

__Expected behavior:__

Data should not be lost when the program terminates normally.

__Actual behavior:__

Data is lost when the program terminates normally (or, at very least, there is prominent documentation describing the conditions under which data can be lost in the course of normal operation when batch / async modes are being used).

Additionally, because of this `# TODO`, it is not straight forward to even work around this issue: https://github.com/influxdata/influxdb-client-python/blob/95988fbb31cbbdac13a9832548847a48d4845a61/influxdb_client/client/write_api.py#L260

__Specifications:__
 - Client Version: influxdb_client-1.11.0

**Comment by bednar** [comment]
Hi @wolever,

thanks for using our client. 

The default `batching` strategy uses inner buffer to writes data in batches (defined by [write_options](https://github.com/influxdata/influxdb-client-python/blob/master/README.rst#batching)). You have to call:
```python
"""
Close client
"""
_write_client.__del__()
_client.__del__()
```
or something like:
```python
def on_exit(db_client: InfluxDBClient, write_api: WriteApi):
    """Close clients after terminate a script.

    :param db_client: InfluxDB client
    :param write_api: WriteApi
    :return: nothing
    """
    write_api.__del__()
    db_client.__del__()

"""
Call after terminate a script
"""
atexit.register(on_exit, _db_client, _write_api)
```
before end of your script.

I am apologies for unclear documentation... we have to improve our docs to clarify how to dispose the client in batching strategy.

Regards
