### ISSUE TITLE
Agnostic way of writing to InfluxDB and other databases

### ISSUE THREAD

**Issue by MatinF** [influxdata/influxdb-client-python#167]
I'm currently using this API for writing data to my InfluxDB cloud instance. 

As part of the API script I'm developing, I would like to be able to easily switch from writing to InfluxDB to writing to other databases. While InfluxDB will be the default recommendation to our users, some may want to switch to other databases.

Is there a method/concept that we can use to implement this, similar to how the fsspec allows us to source data from different file systems (local, S3, ...) in an agnostic way?

Thank you,
Martin

**Comment by bednar** [comment]
Hi @MatinF,

currently we don't have implemented such thing. Maybe you should use `stream processing` library like [faust](https://faust.readthedocs.io/en/latest/index.html) to select correct destination.

Regards
