### ISSUE TITLE
How to get the most recent timestamp for a Measurement via Flux

### ISSUE THREAD

**Issue by MatinF** [influxdata/influxdb-client-python#172]
I need to get the highest (aka most recent) timestamp for a specific Measurement in InfluxDB 2.0 via the Flux query language using the Python API.  I have used the below query to get a timestamp (so I believe it's close to done), but I'm unsure how to ensure that the timestamp I extract via this method is indeed the most recent one. 

In particular, the indexing I use, `last_data[0]`, is arbitrary as `last_data` is a list of objects like `<influxdb_client.client.flux_table.FluxTable object at 0x00000193FA906AC8>`, which I am unsure how to interpret. The timestamps do not seem to be sorted. 

```
from influxdb_client import InfluxDBClient, WriteOptions

client = InfluxDBClient(url=self.influx_url, token=self.token, org=self.org_id, debug=False)

last_data = client.query_api().query(
    f'from(bucket:"{self.influx_bucket}") |> range(start: -100d) |> filter(fn: (r) => r["_measurement"] == "{devices[0]}") |> last()'
)
timestamp = last_data[0].records[0]["_stop"]
print(timestamp)
```

**Comment by bednar** [comment]
Hi @MatinF,

the `_stop` field is [the exclusive upper time bound of all records](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#from), I think that you look for `_time` field - "the time of the record".

I am not expert on Flux, but what about something like:

```flux
from(bucket: "my-bucket")
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r["_measurement"] == "my-measurement")
  |> keep(columns: ["_time"])
  |> last(column: "_time")
```

and Python code:

```python
bucket = self.influx_bucket
measurement = devices[0]

"""
Query
"""
query = f'from(bucket: "{bucket}")' \
  '|> range(start: 0, stop: now())' \
  f'|> filter(fn: (r) => r["_measurement"] == "{measurement}")' \
  '|> keep(columns: ["_time"])' \
  '|> last(column: "_time")' \

tables = client.query_api().query(query=query)

"""
Last Timestamps
"""
last_timestamp = tables[0].records[0]["_time"]
print(f'{last_timestamp}')
```

Regards

**Comment by MatinF** [comment]
Hi again,

Thanks a lot for the tip. I'm a bit confused, though, as it seems that when I run the query repeatedly, I get different results in seemingly randomly fashion.

The correct result that matches what I see in my data is `2020-11-02 15:38:47+00:00`. When I run the below query, I get that value in some cases. But if I then run it a couple of times, the result sometimes changes to `2020-09-01 17:50:03+00:00`. 

For my use case, it is critical that I can consistently query the correct time value, as I will be using this value as part of determining how much data I should push into InfluxDB. If the timestamp is incorrectly set 2 months back, I'll be overwriting old data, causing write costs that are unnecessary.

Am I doing something incorrect in my setup of the query?


```
last_data = client.query_api().query(
    f'from(bucket:"{self.influx_bucket}") |> range(range(start: 0, stop: now())) |> filter(fn: (r) => r["_measurement"] == "{devices[0]}") |> keep(columns: ["_time"]) |> last(column: "_time")'
)

last_time = last_data[0].records[0]["_time"]
print(last_time)

```

**Comment by bednar** [comment]
I think that `sorting` could be solution:

```flux
bucket = "my-bucket"
measurement = "my-measurement"
  
from(bucket: bucket)
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r["_measurement"] == measurement)
  |> keep(columns: ["_time"])
  |> sort(columns: ["_time"], desc: false)
  |> last(column: "_time")
```

There is also dedicated #flux channel in our Slack - https://influxcommunity.slack.com/archives/CH8RGRW4T

**Comment by MatinF** [comment]
Perfect, thank you so much - and thanks for the slack tip!

**Comment by shashi1iitk** [comment]
This is not working anymore!!

**Comment by Nirvana2211** [comment]
Adding something for the future. The query below works if you want to get the last timestamp for all the measurements from a given bucket.

from(bucket: "you_bucket")
  |> range(start: 2024-06-06T18:28:00Z)
  |> filter(fn: (r) => r["_field"] == "field")
  |> group(columns : ["_measurement"])
  |> last(column: "_time")
