### ISSUE TITLE
[Feature Request]: UDP Support

### ISSUE THREAD

**Issue by VeNoMouS** [influxdata/influxdb-client-python#173]
Can UDP support please be added?

**Comment by bednar** [comment]
Hi @VeNoMouS, 

thanks for your Feature Request.

Can you please share your motivation of why do you need UDP? The UDP ingestions is not supported by InfluxDB 2.

Regards

**Comment by VeNoMouS** [comment]
because 900+ sockets with TIME_WAIT's on tcp suck ;P

**Comment by bednar** [comment]
How do you use client? The client uses [PoolManager](https://urllib3.readthedocs.io/en/latest/reference/urllib3.poolmanager.html?highlight=PoolManager#urllib3.PoolManager) to cache connection and opened socket.

https://github.com/influxdata/influxdb-client-python/blob/31a3f1cdf24afd2c8837845b6ca0ac6b8d799bd7/influxdb_client/rest.py#L115

**Comment by VeNoMouS** [comment]
Monitoring / recording stats of jobs running in my cluster, which can be up to 10k+ a minute, influxdb itself doesnt close the socket all the way, its not so much a client side issue, hence why udp would be a better use case.

**Comment by bednar** [comment]
Thanks for clarification. 

What will be a destination for writes? Neither InfluxDB 2 OSS and InfluxDB 2 Cloud doesn't support UDP.

**Comment by VeNoMouS** [comment]
`InfluxDB v1.8.3 (git: 1.8 563e6c3d1a7a2790763c6289501095dbec19244e)`

**Comment by bednar** [comment]
This client supports `InfluxDB v1.8`  by [InfluxDB 2.0 API compatibility endpoints](https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-2-0-api-compatibility-endpoints), but there is no support for UDP.

If you would like to use `v1.8` with `UDP` you should use v1 client:

- https://github.com/influxdata/influxdb-python
- https://influxdb-python.readthedocs.io/en/latest/examples.html#tutorials-udp
