### ISSUE TITLE
InfluxDB client does not support providing or using HTTP/HTTPS proxy for connections

### ISSUE THREAD

**Issue by wojciechka** [influxdata/influxdb-client-python#176]
__Proposal:__
The client should allow providing the proxy settings, either using an option provided when initializing `InfluxDBClient` or the `http_proxy` / `https_proxy` environment variables.

__Current behavior:__
Currently even with `http_proxy` / `https_proxy` set, the connection is not made using proxy.

__Desired behavior:__
Either when `http_proxy` / `https_proxy` set and/or when a value is passed explicitly to the `InfluxDBClient`, the connection is made using proxy.

__Alternatives considered:__
N/A

__Use case:__
Running the client over a proxy is common practice in hardened environments where IP-level traffic whitelisting/blacklisting is not possible.

**Comment by bednar** [comment]
Closed by #177
