### ISSUE TITLE
query_data_frame severe performance problem in converting _time into datatime64.

### ISSUE THREAD

**Issue by max0x7ba** [influxdata/influxdb-client-python#187]
__Problem description:__
I query a dataset from a local InfluxDB which Data Explorer UI queries and plots in 0.02 seconds.

When I load exactly the same dataset into `pandas.DataFrame` using `query_data_frame` function it takes 184 seconds. 157 seconds of which `cProfile` attributes to `pandas.to_datetime` function, called by `PandasDateTimeHelper` for each and every row's timestamp. This performance problem seems to originate from the fact that the query receives `_time` column as text in format `%Y-%m-%dT%H:%M:%SZ`, which must then be parsed. [Complete cProfile output](https://drive.google.com/file/d/1uJvM2Bddl1-odv6pBrxLbo5kIxsvsSVz/view?usp=sharing).

It looks like this conversion of `_time` column represented as `uint64` number of nanoseconds to string in ISO datetime format in InfluxDB and then parsing that string back into `uint64` number of nanoseconds in `influxdb_client` is totally unnecessary, if I understand the dataflow correctly.

How do I get rid of these unnecessary conversions for `_time` column, please?

Is there a way to receive `_time` column as `uint64` number of nanoseconds, which I could cast to `pandas.datetime64` with one call to `pandas.to_datetime` on entire column?

__Specifications:__
 - Client Version: 1.13.0
 - InfluxDB Version: 2.0.3
 - Platform: Ubuntu 18.04.5 LTS, amd64

**Comment by bednar** [comment]
@max0x7ba thanks for using our client, we will take a look

**Comment by bednar** [comment]
Hi @max0x7ba,

Could you please share an information how your data looks like (cardinality, amount, example...)?

Which version of Python do you use. Did you try install a `ciso8601`?

https://github.com/influxdata/influxdb-client-python#installation

Regards

**Comment by max0x7ba** [comment]
> Could you please share an information how your data looks like (cardinality, amount, example...)?

From [Complete cProfile output](https://drive.google.com/file/d/1uJvM2Bddl1-odv6pBrxLbo5kIxsvsSVz/view?usp=sharing), the query returns a dataframe:
```
[1767791 rows x 2 columns]
Alice  float64
Bob    float64
dtype: object
```

> Which version of Python do you use. 

Python 3.6.9. 

The problem, as I reported, comes from calling `pandas.to_datetime` on every row, rather than on entire column. And, ultimately, from timestamps being strings, rather than nanosecond timestamps.

> Did you try install a ciso8601?

What is it and what problem does it solve?

**Comment by bednar** [comment]
> The query must return timestamp in uint64 nanosecond format, not as human readable date. So that no parsing of timestamps is needed. Ideally, in binary.

The InfluxDB doesn't support responses in binary format. You could change your query to:

```
from(bucket:"A")
 |> range(start: 1483228800, stop: 1609459200)
 |> filter(fn: (r) => r._measurement == "ABC")
 |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
 |> keep(columns: ["_time","Alice","Bob"])
 |> map(fn:(r) => ({ r with _time: uint(v:r._time) }))
```

a then `_time` will be returned as a `unsignedLong`.

The default `influxdb_client.client.query_api.QueryApi.query_data_frame` parse all rows into appropriate python types. If you want to skip this overhead you could do something like:

```python
import codecs
from io import StringIO

import pandas as pd

from influxdb_client import InfluxDBClient, Dialect
from influxdb_client.client.write_api import SYNCHRONOUS

url = "https://us-west-2-1.aws.cloud2.influxdata.com/"
token = "my-token"
org = "my-org"

client = InfluxDBClient(url=url, token=token, org=org)

write_api = client.write_api(write_options=SYNCHRONOUS)
query_api = client.query_api()

"""
Query: using Raw with custom Dialect
"""
query = """
from(bucket: "github")
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r["language"] == "Java")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> keep(columns: ["_time", "stars", "size"])
  |> map(fn:(r) => ({ r with _time: uint(v:r._time) }))
"""
response = query_api.query_raw(query, dialect=Dialect(delimiter=",", comment_prefix="#", annotations=[],
                                                      date_time_format="RFC3339"))

as_str = codecs.decode(response.data)

data_frame = pd.read_csv(StringIO(as_str), sep=",", header=0, names=["-", "result", "table", "_time", "stars", "size"])
data_frame = data_frame.drop(columns=["-", "result", "table"])
data_frame["_time"] = pd.to_datetime(data_frame["_time"])
print(data_frame)

"""
Close client
"""
client.__del__()

```

**Comment by max0x7ba** [comment]
Thanks a lot, Jakub, 

`map(fn:(r) => ({ r with _time: uint(v:r._time) })` followed by `df.index = pd.to_datetime(df._time)` fixed the problem. 

Now
```
df = influxdb_client.query_api().query_data_frame(query)
df.index = pd.to_datetime(df._time)
```
Takes 15 seconds.

**Comment by max0x7ba** [comment]
With `query_api.query_raw` method my query takes only 8 seconds. Thanks again.
