### ISSUE TITLE
Delete API Exposure

### ISSUE THREAD

**Issue by maxschommer** [influxdata/influxdb-client-python#188]
__Proposal:__
Add Delete functionality to the api, exposing the `/api/v2/delete` endpoint.

__Use case:__
For automated tests, I'd like to be able to send a series of test data to influx, and then clean up afterwards by deleting the data.

**Comment by maxschommer** [comment]
It appears that this exists, but is not exposed in the documentation?

```
delete_api = client.delete_api()
delete_api.delete(start, stop, '_measurement="sensorData"', bucket_id=bucket_id, org_id=organization_id)
```

**Comment by maxschommer** [comment]
The `README.md` has no reference to the delete api, and the `read_the_docs` has a `DeleteAPI` section, which is empty:

https://influxdb-client.readthedocs.io/en/latest/api.html#deleteapi

**Comment by bednar** [comment]
@maxschommer thanks for using our client, we will take a look

**Comment by zcattacz** [comment]
Could you make it clear in the doc how to delete from a open range? e.g. [2021-1-1, inf ) , I tried to pass none it didn't work.

**Comment by zcattacz** [comment]
Also it feels unreasonable the delete API use iso timestamp while the write API use datetime object.

**Comment by bednar** [comment]
> Could you make it clear in the doc how to delete from a open range? e.g. [2021-1-1, inf ) , I tried to pass none it didn't work.

The InfluxDB Delete API requires the `stop` parameter, there is no option how to pass `Infinity` as a `stop`. You can define `stop` as `2200-01-01T00:00:00.000000000Z`

- https://docs.influxdata.com/influxdb/v2.0/api/#tag/Delete

> Also it feels unreasonable the delete API use iso timestamp while the write API use datetime object.

Good catch. Can you please create new issue for that. Meanwhile you can use following workaround:

```python
from datetime import datetime
from influxdb_client.client.util.date_utils import get_date_helper
date_helper = get_date_helper()
start = date_helper.to_utc(datetime(1970, 1, 1, 0, 0, 0, 0))
stop = date_helper.to_utc(datetime(2200, 1, 1, 0, 0, 0, 0))

self.delete_api.delete(start, stop, "", bucket=bucket.id, org=organization.id)
```

**Comment by zcattacz** [comment]
hi @bednar, I dont know where to start so I tried 9999-12-30T23:59....  and got a error saying value needs to be before 2262-04-11T23:47:16.854775806Z. I guess it may be nice, if it can be sugar coated into a directive e.g. delete_api.max_date.
