### ISSUE TITLE
Documentation unclear on proper extended usage of WriteApi client 

### ISSUE THREAD

**Issue by markmnl** [influxdata/influxdb-client-python#190]
Does the WriteAPI client support context management? If so what does the context manager do - flush, close, wait for batch to complete? I cannot answer any of these queststions reading the doucmentation so I don't know if I should be creating a new instance of WriteApi client evey time I want to write a new batch.. 

>Important: The WriteApi in batching mode (default mode) is suppose to run as a singleton. To flush all your data you should call ``_write_client.close()`` at the end of your script.

This part of the documentation I find contradictory - singleton implies never create another instance - but it goes on to say I should close to flush?? What if I have a service continuously running? How can I flush what has already been written if I want to?  I don't feel confident reading the documentation using this library...

**Comment by bednar** [comment]
Hi @markmnl,

thanks for your comment.

> Does the WriteAPI client support context management?

Currently not, but It is a good suggestion 👍 and we will add support for this.
 
>  If so what does the context manager do - flush, close, wait for batch to complete?

I think the context manager will close the `WriteApi`. 

> What if I have a service continuously running? How can I flush what has already been written if I want to?

Currently We don’t have an explicit `flush` method. 😞. I will take a look too.

Anyway thanks for your comment! 


Regards

**Comment by lafrech** [comment]
Hi.

A context manager would be really nice indeed.

It is also unclear to me the difference between `write_api.close()` and `write_api.__del__()`.

Are the three following lines needed?

```py
    write_api.__close__()
    write_api.__del__()
    client.__del__()
```

I didn't dive into the internals but it sounds very strange to call `__del__` like this on an object. I never to that in Python as it should be done automatically by the garbage collector.

I wouldn't find it strange if I had to call a flush method manually, though.

Also, if `close` or `__del__` forces the flush of the `write_api`, how come we also need to call `__del __` on `client`? Is there anything else to flush?

In any case, a proper context manager should take care of all this.

**Comment by lafrech** [comment]
Answering myself.

For both `InfluxDBClient` and `WriteApi`, the `close` method is just a wrapper around `__del__`.

https://github.com/influxdata/influxdb-client-python/blob/a3e18ee93f68c1a6e155df16a8c2928390cd8c63/influxdb_client/client/write_api.py#L263-L265

https://github.com/influxdata/influxdb-client-python/blob/5eb4cdf9eec9840b0797c73360d200577c32e367/influxdb_client/client/influxdb_client.py#L165-L167

I guess we should use `close`, then, and the docs should advertise the use of `close`.

Definitely something nice hiding in a context manager.
