### ISSUE TITLE
No data in DB when writing a point

### ISSUE THREAD

**Issue by alehanderoo** [influxdata/influxdb-client-python#195]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

```
from influxdb_client import InfluxDBClient, Point, WritePrecision, BucketsApi, OrganizationsApi
from influxdb_client.client.write_api import SYNCHRONOUS

org = "-"
token = "-"
I_client = InfluxDBClient(url="http://localhost:8086", token=token, org=org, debug=True)
write_api = I_client.write_api(write_options=SYNCHRONOUS)

def gen_bucket(symbol, client, org_ID):
	# If the bucket doesn't exist yet.. Create one with the CSV file name
	BucketAPI = BucketsApi(client)
	bName = "_" + symbol
	bucket = BucketAPI.find_bucket_by_name(bucket_name=bName)
	if bucket is not None:
		print ("Bucket {} already exist".format(bName))
	else:
		print ("Bucket doesn't exist, creating bucket: {}".format(bName))
		newBucket = BucketAPI.create_bucket(bucket_name=bName, org_id=org_ID)
		return newBucket

org_ID = get_org_ID(I_client)
gen_bucket("SYMBOL", I_client, org_ID)

for kline in XX.get_historical_klines:
	point = Point("financial-analysis")		\
		.tag("type", "1m_kline")			\
		.field("Open", float(kline[1]))		\
		.field("High ", float(kline[2]))		\
		.field("Low", float(kline[3]))		\
		.field("Close ", float(kline[4]))		\
		.field("Vol", float(kline[5]))		\
		.field("Trades", float(kline[8]))		\
		.time(kline[0], WritePrecision.MS)
	write_api.write(bucket="SYMBOL", org=org, record=point)

write_api.__del__()

query = 'from(bucket:"SYMBOL")' \
				' |> range(start: -10m)' \
				' |> filter(fn: (r) => r._measurement == "financial-analysis")' \
				' |> max()'
result = I_client.query_api().query(query=query)
print (result)

```

__Expected behavior:__
Data injected in the database and then succesfully printed from the result variable

__Actual behavior:__
The result from debug. 
The [] is the final print

- thorization: Token xxxxN\r\nUser-Agent: influxdb-client-python/1.10.0\r\n\r\n'
- send: b'financial-analysis,type=1m_kline Close\\ =51708.7,High\\ =51727.36,Low=51680.28,Open=51686.5,Trades=566.0,Vol=15.290266 1613688240000'
- reply: 'HTTP/1.1 204 No Content\r\n'
- header: Date: Thu, 18 Feb 2021 21:42:09 GMT
- send: b'POST /api/v2/query?org=ARB HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 286\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Token xxxx\r\nUser-Agent: influxdb-client-python/1.10.0\r\n\r\n'
- send: b'{"query": "from(bucket:\\"SYMBOL\\") |> range(start: -10m) |> filter(fn: (r) => r._measurement == \\"financial-analysis\\") |> max()", "dialect": {"header": true, "delimiter": ",", "annotations": ["datatype", "group", "default"], 
- "commentPrefix": "#", "dateTimeFormat": "RFC3339"}}'
- reply: 'HTTP/1.1 200 OK\r\n'
- header: Content-Type: text/csv; charset=utf-8
- header: Vary: Accept-Encoding
- header: Date: Thu, 18 Feb 2021 21:42:09 GMT
- header: Transfer-Encoding: chunked
- []

__Specifications:__
 - Client Version: influxdb-client-python/1.10.0
 - InfluxDB Version: 2.0
 - Platform: Python 3.8.3 64-bit on Windows10 calling influxDB self-hosted docker container.

**Comment by bednar** [comment]
Hi @alehanderoo,

thanks for using our client.

If you look at debug output You could see that following LineProtocol was written into InfluxDB: `b'financial-analysis,type=1m_kline Close=51708.7,High=51727.36,Low=51680.28,Open=51686.5,Trades=566.0,Vol=15.290266 1613688240000'.
Is your time stamp correct? It should be time in UTC. What is content of `kline[0]`?

Regards

**Comment by alehanderoo** [comment]
Hi @bednar,

It's a wonderfull piece of code :D

kline[0] = 1613688240000

**Comment by bednar** [comment]
The timestamp `1613688240000 ` is "Thursday, 18 February 2021 22:44:00 GMT" but you are querying at "Thu, 18 Feb 2021 21:42:09 GMT".

So you are writing data from future... probably it is caused by different timezone of your timestamp. If it is a intention you could use `stop` parameter from `range` function - https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/range/#stop

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
