### ISSUE TITLE
[maintenance] Mark old repository influxdb-python as archived

### ISSUE THREAD

**Issue by 1oglop1** [influxdata/influxdb-client-python#212]
Hello,
would it be possible to mark [the old repository](https://github.com/influxdata/influxdb-python) as **archived** and point people here instead? 

I just spend 40 minutes reading there until I found this "client" by accident. 

Thank you

**Comment by bednar** [comment]
Hi @1oglop1,

I've updated README for the old  client with a link to the new client: https://github.com/influxdata/influxdb-python/pull/881.

Currently, we don't want to archive clients repositories for InfluxDB v1.

Regards

**Comment by 1oglop1** [comment]
@bednar Note is good as well :)
Thank you!
