### ISSUE TITLE
Information and examples for connecting to InfludData Cloud

### ISSUE THREAD

**Issue by TravisJoe** [influxdata/influxdb-client-python#22]
This is not necessarily the fault of the library, but documentation is lacking on how to properly find and use information to connect to the InfluxData Cloud instances. 

Please provide some resources for this.

**Comment by bednar** [comment]
Hi @TravisJoe,

I created an example that demonstrate a simplest way how to write and query date with the InfluxDB Cloud.

You could find it here: https://github.com/influxdata/influxdb-client-python#connect-to-influxdb-cloud

Regards
Jakub
