### ISSUE TITLE
Question: Getting measurements using the client

### ISSUE THREAD

**Issue by mrn-aglic** [influxdata/influxdb-client-python#223]
I'm using InfluxDB 1.8. I was wondering if there is a way to use influx python client to get a list of available measurements?
Something like you get when running the `show measurements` query?

**Comment by bednar** [comment]
Hi @mrn-aglic,

you can use [schema query](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/measurements/), something like:

```python
from influxdb_client import InfluxDBClient

client = InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org")

"""
Query all measurements in specified bucket
"""

query = '''
import "influxdata/influxdb/schema"

schema.measurements(bucket: "my-bucket")
'''
tables = client.query_api().query(query)
print('\n'.join([f"{record['_value']}" for records in tables for record in records]))

"""
Close client
"""
client.close()

```

Regards

**Comment by mrn-aglic** [comment]
I didn't get a chance to answer sooner.
Thank you for the reply, but I get an error stating that the import path is unknown. Is there something I should install or?

**Comment by bednar** [comment]
The [schema.measurements() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/measurements/) uses [schema.tagValues() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/tagvalues/) which is defined as:

```flux
package schema

tagValues = (bucket, tag, predicate=(r) => true, start=-30d) =>
  from(bucket: bucket)
    |> range(start: start)
    |> filter(fn: predicate)
    |> group(columns: [tag])
    |> distinct(column: tag)
    |> keep(columns: ["_value"])
```

so you can use something like:

```python
from influxdb_client import InfluxDBClient

username = 'username'
password = 'password'

database = 'telegraf'
retention_policy = 'autogen'

bucket = f'{database}/{retention_policy}'

client = InfluxDBClient(url='http://localhost:8086', token=f'{username}:{password}', org='-')

"""
Query all measurements in specified bucket
"""

query = f'''
from(bucket: "{bucket}")
    |> range(start: 0)
    |> group(columns: ["_measurement"])
    |> distinct(column: "_measurement")
    |> keep(columns: ["_value"])
'''
tables = client.query_api().query(query)
print('\n'.join([f"{record['_value']}" for records in tables for record in records]))

"""
Close client
"""
client.close()
```

_Tested on InfluxDB v1.8.4._

**Comment by mrn-aglic** [comment]
I get the following error from the example: "error":"expected float cursor type, got *reads.stringMultiShardArrayCursor"

It works when I remove the "group" function, but I get all of the measurements repeated several times.

**Comment by bednar** [comment]
I'm not expert to Flux, but what about something like:

```python
query = f'''
from(bucket: "{bucket}")
    |> range(start: 0)
    |> keep(columns: ["_measurement"])
    |> distinct(column: "_measurement")
'''
```

There is also dedicated channel for Flux in our Slack: [#flux](https://influxcommunity.slack.com/archives/CH8RGRW4T)

**Comment by mrn-aglic** [comment]
That works @bednar Thank you!

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
