### ISSUE TITLE
Additional example for importing large local files

### ISSUE THREAD

**Issue by mmigge** [influxdata/influxdb-client-python#224]
Hello!

__Proposal:__
It would be great if the documentation could be extended to include another example of importing large local files. 

The [existing example ](https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/examples/import_data_set_multiprocessing.py) for importing gigabytes of data uses a CSV file available via AWS. 

I am struggling to implement this for a locally located file, with millions of rows, with absolute path. 
In particular, lines 150-154 and 171-175 are somewhat cryptic and cause problems.

[https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/examples/import_data_set_multiprocessing.py](url)

__Current behavior:__
Importing a big CSV file available via AWS services

__Desired behavior:__
Importing a big local CSV file

**Comment by bednar** [comment]
> Hello!
> 
> **Proposal:**
> It would be great if the documentation could be extended to include another example of importing large local files.

You could use this example with a local file. Just uncomment following line and set correct path:

https://github.com/influxdata/influxdb-client-python/blob/4015c90214ee80ccf7e915bb8a969b54f6177098/examples/import_data_set_multiprocessing.py#L145


> The [existing example ](https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/examples/import_data_set_multiprocessing.py) for importing gigabytes of data uses a CSV file available via AWS.
> 
> I am struggling to implement this for a locally located file, with millions of rows, with absolute path.
> In particular, lines 150-154 and 171-175 are somewhat cryptic and cause problems.


- `150-154`- `ProgressTextIOWrapper`-  is capable to show progress of import for a file streamed from AWS
- `171-175` - creates batches by `10_000` rows and process them by `parse_rows` 

> [https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/examples/import_data_set_multiprocessing.py](url)
> 
> **Current behavior:**
> Importing a big CSV file available via AWS services
> 
> **Desired behavior:**
> Importing a big local CSV file

Did you try [import_data_set_sync_batching.py](https://github.com/influxdata/influxdb-client-python/blob/master/examples/import_data_set_sync_batching.py)? For big files you could increase batch to 10_000 - https://github.com/influxdata/influxdb-client-python/blob/4015c90214ee80ccf7e915bb8a969b54f6177098/examples/import_data_set_sync_batching.py#L46

**Comment by mmigge** [comment]
Thanks for your help, the first script works with a local file. Unfortunately it breaks when running it. 

I am working with a total of 350GB of data in CSV format, split into 70 files each 5GB in size. When I use the script just like that, the process stops after about 120GB.

Could it be that the machine with 8 cores and 32GB does not have enough power to write data with batch_size=50_000, flush_interval=10_000? How could I adjust the parameters so that the script doesn't abort? 

I haven't tried the second script you mentioned yet, since using more than one core is essential for such a amount of data, isn't it?

**Comment by bednar** [comment]
Which version of InfluxDB do you use?

**Comment by mmigge** [comment]
InfluxDB 2.0.4

**Comment by bednar** [comment]
> Thanks for your help, the first script works with a local file. Unfortunately it breaks when running it.

Is there an error or some detail information why it breaks?
 
> I am working with a total of 350GB of data in CSV format, split into 70 files each 5GB in size. When I use the script just like that, the process stops after about 120GB.

How your data looks like? Is a parsing into `Point` structure CPU heavy?

> Could it be that the machine with 8 cores and 32GB does not have enough power to write data with batch_size=50_000, flush_interval=10_000? How could I adjust the parameters so that the script doesn't abort?

It depends... Is your InfluxDB locally running? Do you have enough resources for InfluxDB - there is a sizing guide - https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/#influxdb-oss-guidelines

Is there any errors in InfluxDB log?

> I haven't tried the second script you mentioned yet, since using more than one core is essential for such a amount of data, isn't it?

It depends on your data. If you are able to quickly produce data for ingesting you could use approach from `import_data_set_sync_batching`.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
