### ISSUE TITLE
Docs don't say if influxdb-client-python is a backward compatible upgrade to influxdb-python 

### ISSUE THREAD

**Issue by bslade** [influxdata/influxdb-client-python#226]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. View the web page https://github.com/influxdata/influxdb-client-python/blob/master/README.rst
2. That page says, "Use this client library with InfluxDB 2.x and InfluxDB 1.8+. For connecting to InfluxDB 1.7 or earlier instances, use the influxdb-python client library."
3. That might imply that influxdb-client-python is the upgraded version of influxdb-python and therefore backward compatible.  Eg. is the "write_points" call still supported?

__Expected behavior:__
The README.rst should say whether influxdb-client-python is a backward compatible upgrade to influxdb-python or a new interface requiring a rewrite of applications written for influxdb-python

__Actual behavior:__
The https://github.com/influxdata/influxdb-client-python/blob/master/README.rst doesn't say  whether influxdb-client-python is a backward compatible upgrade to influxdb-python or a new interface requiring a rewrite of applications written for influxdb-python

__Specifications:__
 - Client Version: N/A
 - InfluxDB Version: N/A
 - Platform: N/A

**Comment by bednar** [comment]
@bslade, thanks for using our client.

What do you think about:

"Use this client library with InfluxDB 2.x and InfluxDB 1.8+. For connecting to InfluxDB 1.7 or earlier instances, use the influxdb-python client library (influxdb-client-python is not compatible with influxdb-python)."

?

**Comment by bslade** [comment]
Re:  influxdb-client-python is not compatible with influxdb-python

Yes, I think that makes it clear.

Thanks
Ben Slade
