### ISSUE TITLE
drop measurement

### ISSUE THREAD

**Issue by ahmadr4079** [influxdata/influxdb-client-python#228]
Is there a way to drop measurement?

**Comment by bednar** [comment]
Hi @ahmadr4079,

thanks for using our client. You could use something like:

```python
start = "1970-01-01T00:00:00Z"
stop = "2021-01-01T00:00:00Z"
delete_api = client.delete_api()
delete_api.delete(start, stop, '_measurement="sensorData"', bucket_id=bucket_id, org_id=organization_id)
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
