### ISSUE TITLE
TypeError: query() got an unexpected keyword argument 'params'

### ISSUE THREAD

**Issue by staeglis** [influxdata/influxdb-client-python#231]
Hi,

I'm trying to query some data according your example (Query: using Bind parameters). Instead of data  I'm getting the following error:
```
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    tables = query_api.query('''
TypeError: query() got an unexpected keyword argument 'params'
```

Best,
Stefan

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
