### ISSUE TITLE
Handle missing 'tags' key

### ISSUE THREAD

**Issue by tobias-schuele** [influxdata/influxdb-client-python#234]
__Steps to reproduce:__

Write a dictionary-style object without the `tags` key (e.g. because the tags are provided via default tags):

`client.write("my-bucket", "my-org", {"measurement": "h2o_feet", "fields": {"water_level": 1.0}, "time": 1})`

__Expected behavior:__

Either tolerate missing `tags` key or emit a self-explanatory error message / raise an exeception.

__Actual behavior:__

`'NoneType' object does not support item assignment`.

__Specifications:__

 - InfluxDB Version: 2.0.4
 - Platform: Linux Ubuntu 20.10

**Comment by bednar** [comment]
@tobias-schuele,  thanks for using our client, We will take a look.
