### ISSUE TITLE
Drop a Bucket and Create a Bucket

### ISSUE THREAD

**Issue by yareblo** [influxdata/influxdb-client-python#236]
Are there commands to drop a bucket and to create a bucket from the Python API, similar to the functions drop_database and create_catabase in the influxClient Version 1,8?

**Comment by bednar** [comment]
Hi @yareblo,

thanks, for using our client. Checkout this example: [buckets_management.py](https://github.com/influxdata/influxdb-client-python/blob/master/examples/buckets_management.py).

Regards

**Comment by yareblo** [comment]
Perfect, thanks a lot. Exactly what I was looking for!

**Comment by SuTart2** [comment]
I tried out the code and it worked great, but when I tried to incorporate it into my main code, I am getting "Invalid value for `api_client`, must be defined." I traced the code back and found the problem to be in the "organizations_api.py" . In lines 17 and 18, "influxdb_client.api_client" was returning "None" instead of the api client like it was in the original code. Is there a way to fix this?

Thank you so much!

**Comment by bednar** [comment]
@SuTart2 It’s strange. Can you share your code?

**Comment by SuTart2** [comment]
@bednar 

def Connect():
        load_dotenv()
        token = os.getenv('TOKEN')
        org = os.getenv('ORG')
        return token, org

token, org = Connect()
url = "my-url" #sample
with InfluxDBClient(url=url, token=token) as client:
    buckets_api = client.buckets_api()

#part of GUI
self.newBucketLabel = QLabel("Create New Bucket")
self.layout.addWidget(self.newBucketLabel)
self.newBucketEntry = QLineEdit()
self.newBucketEntry.setPlaceholderText("Enter bucket name")
self.layout.addWidget(self.newBucketEntry)
self.newBucketButton = QPushButton("Create Bucket", clicked=lambda: self.createBucket(self.newBucketEntry.text()))
self.layout.addWidget(self.newBucketButton)


def createBucket(self, bucketName):
        retention_rules = BucketRetentionRules(type="expire", every_seconds=0)
        created_bucket = buckets_api.create_bucket(bucket_name=bucketName,
                                               retention_rules=retention_rules,
                                               org=org)

I'm trying to integrate it into a GUI.
Thank you!

**Comment by SuTart2** [comment]
I found a solution to the problem. I defined all the parameters for the InfluxDB client inside the constructor of the GUI instead of outside the class. Also, I used:
        self.client = InfluxDBClient(url="my-url", token=token, org=org)
        buckets_api = BucketsApi(self.client)
to initialize the client.
