### ISSUE TITLE
Issue with bucket example?

### ISSUE THREAD

**Issue by garogan** [influxdata/influxdb-client-python#240]
From example to create,list,delete buckets - 

org_name = "redacted"
org = list(filter(lambda it: it.name == org_name, client.organizations_api().find_organizations()))[0]

produces error - "message": "id must have a length of 16 bytes"

**Comment by bednar** [comment]
Hi @garogan,

Can you please share a full stack trace? Is it value of `org` correct?

Regards

**Comment by russorat** [comment]
Similar issue. Here's the example code and the response:

```
#!/usr/local/bin/python3

from influxdb_client import InfluxDBClient, BucketRetentionRules

url = "https://us-west-2-1.aws.cloud2.influxdata.com/"
token = "XXXXXXXX"
org = "russ+cloud2's organization"

client = InfluxDBClient(url=url, token=token, org=org)
buckets_api = client.buckets_api()

print(f"------- Create -------\n")
retention_rules = BucketRetentionRules(type="expire", every_seconds=3600)
created_bucket = buckets_api.create_bucket(bucket_name="bucket-by-python",
                                           retention_rules=retention_rules)
print(created_bucket)
```

```
➜  tools-cluster git:(master) ✗ python3 create-bucket-test.py   
------- Create -------

Traceback (most recent call last):
  File "/Users/rsavage/workspace/pm-team/tools-cluster/create-bucket-test.py", line 14, in <module>
    created_bucket = buckets_api.create_bucket(bucket_name="bucket-by-python",
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/bucket_api.py", line 52, in create_bucket
    return self._buckets_service.post_buckets(post_bucket_request=bucket)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 1262, in post_buckets
    (data) = self.post_buckets_with_http_info(post_bucket_request, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/buckets_service.py", line 1334, in post_buckets_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/api_client.py", line 170, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/api_client.py", line 385, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/rest.py", line 302, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/rest.py", line 252, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 03 May 2021 22:35:27 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '97', 'Connection': 'keep-alive', 'trace-id': '6d0e198112d26356', 'trace-sampled': 'false', 'x-platform-error-code': 'invalid', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
HTTP response body: {
        "code": "invalid",
        "message": "failed to unmarshal json: id must have a length of 16 bytes"
}
```

**Comment by russorat** [comment]
in my example, it is sending the org name as the org id in https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/service/buckets_service.py#L1334

**Comment by bednar** [comment]
@russorat, the BucketAPI doesn't supports specify `org` as an organization name, because the InfluxDB doesn't allow that.

The `Write` and `Query` API takes `org` interchangeably - either the `ID` or `Name` could be specified. In the opposite the `Bucket` API needs to have specified the `ID`.

- https://docs.influxdata.com/influxdb/cloud/api/#tag/Write
- https://docs.influxdata.com/influxdb/cloud/api/#operation/PostQuery
- https://docs.influxdata.com/influxdb/cloud/api/#operation/PostBuckets 

The `buckets_management.py` uses `organizations_api` to find name of organization:  https://github.com/influxdata/influxdb-client-python/blob/f698030235c3eb1e189d614d81d72efe34a0e80d/examples/buckets_management.py#L20

**Comment by russorat** [comment]
Thanks! that means there's still a bug on this line where it tries to assign the org name to the org_id:
https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/bucket_api.py#L49

IMO, we should leverage the orgs api to get the id or return a better error message.

**Comment by bednar** [comment]
> Thanks! that means there's still a bug on this line where it tries to assign the org name to the org_id:
> https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/bucket_api.py#L49
> 
> IMO, we should leverage the orgs api to get the id or return a better error message.

Good Point. We can validate that the `self._influxdb_client.org` is valid ID and if not then use `orgs api` to get ID.

**Comment by deadmau6** [comment]
@bednar I came across this issue a while ago and came to the same conclusion as @russorat . Just wondering if a specific issue for this bug has been created? If so I have a few questions and some ideas to fix this potentially. So here is my current working solution:
```python
bucket_name = 'example'
myorg = None
orgs_api = client.organizations_api()
for org in orgs_api.find_organizations():
    if org.name == client.org:
        myorg = org
        break
buckets.create_bucket(bucket_name=bucket_name, org_id=myorg.id, retention_rules=rule)
```

So I think this can be implemented in the `create_bucket` method if the `org_id` is not provided. Or `client.org` could be an `Organization` object and then the code in `create_bucket` could simply reference `client.org.id`. Also it may be better to use an `Organization` object as an input parameter to `create_bucket` instead of `org_id`. 

However this might require that the `Organization` object validates itself with the `OrganizationsApi`. Thoughts?

**Comment by bednar** [comment]
> @bednar I came across this issue a while ago and came to the same conclusion as @russorat . Just wondering if a specific issue for this bug has been created?

No, we can continue with this issue.

> If so I have a few questions and some ideas to fix this potentially. So here is my current working solution:
> 
> ```python
> bucket_name = 'example'
> myorg = None
> orgs_api = client.organizations_api()
> for org in orgs_api.find_organizations():
>     if org.name == client.org:
>         myorg = org
>         break
> buckets.create_bucket(bucket_name=bucket_name, org_id=myorg.id, retention_rules=rule)
> ```
> 
> So I think this can be implemented in the `create_bucket` method if the `org_id` is not provided. Or `client.org` could be an `Organization` object and then the code in `create_bucket` could simply reference `client.org.id`. Also it may be better to use an `Organization` object as an input parameter to `create_bucket` instead of `org_id`.
> 
> However this might require that the `Organization` object validates itself with the `OrganizationsApi`. Thoughts?

Thanks for suggestion.

> Or `client.org` could be an `Organization` object

It is good idea, but we have to provide a solution that not breaks code for our existing users.

**Comment by bednar** [comment]
PR #264 fixes this issue. You are able test this PR via:

```
pip install git+https://github.com/influxdata/influxdb-client-python.git@feature/id-name-organization
```
