### ISSUE TITLE
Support write_precision in _write_client.write when record is a Pandas dataframe

### ISSUE THREAD

**Issue by jdaniel006** [influxdata/influxdb-client-python#245]
__Proposal:__
It may be me failing to find the documentation, but it'd be great to be able to specify a write precision other than nanoseconds when the data is in dataframe format.

__Current behavior:__
The dataframe serialize function creates timestamps in nanoseconds from the datetime index. If write_precision is different to 'ns', the action fails with time outside range.

__Desired behavior:__
The dataframe serialize function should use write_precision to format timestamp accordingly.

__Alternatives considered:__
My workaround at this time is to call data_frame_to_list_of_points to generate a list in line protocol and then modify each line to shorten the timestamp to the desired precision.

__Use case:__
Critical for whoever wants to write data from dataframe format and not use unneeded precision.

Influxdb version: 2.0.4
influxdb-client: 1.17.0

**Comment by bednar** [comment]
@jdaniel006, thanks for using our client, We will take a look.
