### ISSUE TITLE
Concurrent queries slower than serial queries

### ISSUE THREAD

**Issue by markoarnauto** [influxdata/influxdb-client-python#247]
__Steps to reproduce:__
I have several (different) long lasting queries (= `queries`). Each with an individual postprocessing procedure which is omitted for the sake of simplicity. But that's the reason why each query has to be done separately. 

1. I ran those queries in parallel using a `ThreadPoolExecutor`.
2. I ran those queries serially.

```python
import concurrent
import time
from concurrent.futures.thread import ThreadPoolExecutor
from influxdb_client import InfluxDBClient

def query():
    # a long lasting query
    return influx_query_client.query_data_frame(f'''
            from(bucket: "bucket")
              |> ....
        ''')

if __name__ == '__main__':

    influx_query_client = InfluxDBClient(url=..., org=..., token=...).query_api()
    queries = [query, query, query, query, query, query, query]

    ## multi threaded read
    t_0 = time.time()
    with ThreadPoolExecutor() as pool:
        futures = [pool.submit(query) for query in queries]
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
    print(f'multiple threads completed in {time.time() - t_0} sec.')

    ## single threaded read
    t_0 = time.time()
    for query in queries:
        result = query()
    print(f'single thread completed in {time.time() - t_0} sec.')
```

__Expected behavior:__
I expected the multi-threaded version to bee much faster.

__Actual behavior:__
The single threaded version is much faster. In my case, more than twice as fast.

__Specifications:__
 - Client Version: 1.17.0
 - InfluxDB Version: 2.0.4
 - Platform: Ubuntu

**Comment by bednar** [comment]
@markoarnauto thanks for issue, it is strange behaviour... we will take a look 👀

**Comment by bednar** [comment]
Hi @markoarnauto,

it is caused by GIL - Global Interpreter Lock. The Pandas uses library written in C which obtain/release the Global Interpreter Lock (GIL). The locking/unlocking is an overhead and causes the slowdown of process.

If you try: `influx_query_client.query`, `influx_query_client.query_csv`, `influx_query_client.query_raw`, the `multi-threaded` version will be faster.

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
