### ISSUE TITLE
How can I write in right order based on a list

### ISSUE THREAD

**Issue by Wapiti08** [influxdata/influxdb-client-python#248]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I have a list, I need to write them as points to influxdb
2. I want to make sure it is the order in the list when writing to influxdb

__Expected behavior:__
the points are written in the order of list

__Actual behavior:__
the order is a bit random when written to influxdb

__Specifications:__
 - Client Version: 2.0
 - InfluxDB Version: 2.x
 - Platform: debian

**Comment by Wapiti08** [comment]
Sorry. I just get your points. I will give it a go soon Thanks

**Comment by bednar** [comment]
You have to add unique timestamp for your data, something like:


```python

time_i = 0
for tag_dict, field_dict in zip(new_tag_dict_list, new_field_dict_list):
            # tag will be the unique key
            points.append({"measurement":meas,
                            "tags":tag_dict,
                            "fields":field_dict,
                            "time": time_i,
                        })
            time_i += 1
write_api.write(bucket=bucket, record=points)
```
