### ISSUE TITLE
How to paginate data?

### ISSUE THREAD

**Issue by abhi1693** [influxdata/influxdb-client-python#250]
We have a need to display about 2k entries in a table. Is there a way that we can paginate the query? Or do we have to implement our own logic for this?

__Steps to reproduce:__
NA

__Expected behavior:__
Paginate the query

__Actual behavior:__
2k entries returned at once

__Specifications:__
 - Client Version: 1.17.0
 - InfluxDB Version: 2.0.5
 - Platform: Linux

**Comment by bednar** [comment]
The `query_api` doesn't have a pagination supports. You have to use [limit() function](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/limit/) in your Flux query.

**Comment by abhi1693** [comment]
Thank you for the tip :)
