### ISSUE TITLE
Field type is set to `string` when writing `float32` type from Pandas DataFrame

### ISSUE THREAD

**Issue by markkvdb** [influxdata/influxdb-client-python#252]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create pandas DataFrame with field columns as type `float32`, e.g., `df.astype("float32")`
2. Write DataFrame using default write method (batching etc.), e.g., `write_api.write("bucket_name", record=df, data_frame_measurement_name="measurement", data_frame_tag_columns=["tag1", "tag2"])`

__Expected behavior:__
Expect python client to write data as `float` in the InfluxDB database. Note that converting the field columns with `df.astype(float)` does result in the expected behaviour with floats in the database.

__Actual behavior:__
Data is written as `string`. 

__Specifications:__
 - Client Version: 1.17.0
 - InfluxDB Version: 2.0.5
 - Platform: Linux (x86_64)

**Comment by bednar** [comment]
Hi @markkvdb,

thanks for using our client.

I've prepared PR #254. If you would like to use dev version of client then install client via:

```console
pip install git+https://github.com/influxdata/influxdb-client-python.git@fix/serialize-np-floats
```

Regards

**Comment by markkvdb** [comment]
Thanks @bednar. I just used the standard float type but good to know that future versions of the library support the Numpy floats :)
