### ISSUE TITLE
Add a get method to all values

### ISSUE THREAD

**Issue by jrbenito** [influxdata/influxdb-client-python#253]
There is no get for all values like Java language api.

```
def get_values(self):
        """Get field value."""
        return self._values
```

This is useful to manipulate results like a Python Dictionary.

**Comment by bednar** [comment]
Hi @jrbenito,

thanks for using our client. Y

You can use dot syntax to access all values from `FluxRecord`: `record.values`. See this example:

https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/examples/query.py#L29

Regards

**Comment by jrbenito** [comment]
Hi @bednar ,

I did realize it this morning. Next time would be better to open issues after a good night of sleep.

Sorry for bother and I do appreciate you fast answer!

Thanks.
