### ISSUE TITLE
Setting shard-group-duration when creating a bucket via the buckets_api?

### ISSUE THREAD

**Issue by yareblo** [influxdata/influxdb-client-python#256]
Hi,

I would like to set a custom shard group duration when creating a new bucket with buckets_api.create_bucket(...). This is possible when a bucket is created via the commandline:

https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/bucket/create/

How can this be done with the buckets_api?

Thanks!

**Comment by bednar** [comment]
Hi @yareblo,

> How can this be done with the buckets_api?

`shard_group_duration_seconds`: https://github.com/influxdata/influxdb-client-python/blob/0a785666f59eae6240f7a889a438c1b6f4855a8f/influxdb_client/domain/bucket_retention_rules.py#L46

You can use something like:


```python
from influxdb_client import InfluxDBClient, BucketRetentionRules

url = "http://localhost:8086"
token = "my-token"
org_id = "my-org"

with InfluxDBClient(url=url, token=token) as client:
    buckets_api = client.buckets_api()

    retention_rules = BucketRetentionRules(type="expire", every_seconds=2592000, shard_group_duration_seconds=172800)
    created_bucket = buckets_api.create_bucket(bucket_name="bucket-by-python",
                                               retention_rules=retention_rules,
                                               org_id=org_id)
    print(created_bucket)

```

Regards

**Comment by yareblo** [comment]
Thanks a lot, works perfectly!
