### ISSUE TITLE
Receive measurement data combined in a single table

### ISSUE THREAD

**Issue by joschanassenstein** [influxdata/influxdb-client-python#258]
__Proposal:__
We are currently querying our InfluxDB using the python library. While doing so, we did not find a solution to create a query and aggregate the result in a single table (the query includes several different tag / value combinations) to export it as csv.
The query we used was:
`from(bucket:"mydb") |> range(start: -60m) |> filter(fn:(r) => r._measurement == "<measurement>")`

We are using influxdb 1.8.5 and influxdb-client 1.17.0.

__Current behavior:__
The result is split into several tables, each one containing a specifically structured datapoint.

__Desired behavior:__
Using the InfluxDB CLI, we were able to achieve the desired result with the following command:
`influx -database mydb -execute 'SELECT * FROM "<measurement>"' -precision s -format csv > test.csv`

Example of desired result

time|flowrate|lat|long|sensor
----|--------|---|----|------
1621346627064773206|2.15|||flow
1621346627087677338|6.51|||flow
1621346627096719931||51.013464|6.983208|gps
1621346627119059794||52.013464|7.983208|gps

Is there currently a solution for our use case? I was reading the documentation, but did not come to a conclusion yet.

**Comment by bednar** [comment]
Hi @joschanassenstein,

thanks for using our client.

> The result is split into several tables, each one containing a specifically structured datapoint.

It is default behavior of Flux Lang. Did you try use something like: `… |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
|> drop(columns: ["_start", "_stop", "_measurement"]) |> group()`?

> **Desired behavior:**
> Using the InfluxDB CLI, we were able to achieve the desired result with the following command:
> `influx -database mydb -execute 'SELECT * FROM "<measurement>"' -precision s -format csv > test.csv`
> 
> Example of desired result
> 
> time	flowrate	lat	long	sensor
> 1621346627064773206	2.15			flow
> 1621346627087677338	6.51			flow
> 1621346627096719931		51.013464	6.983208	gps
> 1621346627119059794		52.013464	7.983208	gps
> Is there currently a solution for our use case? I was reading the documentation, but did not come to a conclusion yet.

The CLI supports querying by InfluxQL, but this client shall be used to use Flux queries. InfluxQL queries returns json data that are not recognized by this client.

Regards

**Comment by joschanassenstein** [comment]
Hi @bednar,

I will test your suggested addition to the Flux query soon. We currently use the CLI to be able to query using InfluxQL which is also working for us for the moment.

Thank you for the quick response!
