### ISSUE TITLE
Adding options for basic auth to API calls

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [influxdata/influxdb-client-python#262]
__Proposal:__
I'm seeing implementations where additional (basic) authentication proxies are being placed in front of InfluxDBs (mainly 1.8 versions where auth is disabled). This makes it difficult to use the compatibility API as basic auth headers cannot be added, only the ```Authorization: Token {user}:{pwd}``` would be added. As described [here](https://github.com/influxdata/influxdb-client-python/blob/master/examples/influxdb_18_example.py).
Would it be possible to also pass a Basic Auth header so that a auth proxy would be able to process the API requests in such cases?

__Current behavior:__
Writing to the compatibility API to a InfluxDb 1.8 which has auth disabled but uses a proxy with basic auth is not possible

__Desired behavior:__
It would be good to allow these special setups with authenticating proxies and influxdbs with not auth enabled

__Alternatives considered:__
Reverting to either not use the new influxdb-client or manual line protocol posting with basic auth (not very efficient)

__Use case:__
It would help in migrating solutions that need to write to both 1.8 (with special setups) and 2.0 influxDBs

**Comment by bednar** [comment]
@reinhard-brandstaedter, thanks for suggestion, We will take a look.
