### ISSUE TITLE
get_start() and get_stop() not giving the right behaviour?

### ISSUE THREAD

**Issue by lhuang61** [influxdata/influxdb-client-python#271]
The `get_start()` and `get_stop()` methods on the Flux object is supposed to return "the inclusive lower time bound of all records in the current table" and "the exclusive upper time bound of all records in the current table" respectively. However, it seems like they only return the range specified in the Flux query instead. 

e.g. If my flux table contains 5 records, I expect `get_start()` and `get_stop()` to give me the time of the 1st and the 5th record, but instead, I only get the the beginning and the end of the filter period in the Flux query. 

Just wondering if this is the expected behaviour. While the current result is technically still an upper and lower bound, but it does not seem to be as useful.

**Comment by bednar** [comment]
Hi @lhuang61,

thanks for using our client.

> Just wondering if this is the expected behaviour.

Yes, it is.

The `get_start()` and `get_stop()` is directly mapped to `_start` and `_stop` column in Flux response. For more info see: https://github.com/influxdata/flux/blob/master/docs/SPEC.md#from

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
