### ISSUE TITLE
Incompatibility between documentation and source code

### ISSUE THREAD

**Issue by buraketmen** [influxdata/influxdb-client-python#276]
__Expected behavior:__

For the same version (1.18.0), I was expecting the source code on Github and pypi to be the same as on my own computer.

__Actual behavior:__

When I download the current latest version 1.18.0, I see that there is an incompatibility between the documentation and the source code. I thought it might be because of the old version, I cleared the pip cache and downloaded it with --no-cache-dir but it didn't solve my problem. For example, the create_bucket function in BucketApi differs, so I cannot create a bucket without using org_id via python.

- The pypi version of the create_bucket function in the BucketApi class.

`
def create_bucket(self, bucket=None, bucket_name=None, org_id=None, retention_rules=None, description=None, org=None) -> Bucket:`

- On my computer

`
def create_bucket(self, bucket=None, bucket_name=None, org_id=None, retention_rules=None, description=None) -> Bucket:
`

__Specifications:__
 - Client Version: 1.18.0
 - InfluxDB Version: 2.0.7
 - Platform: Windows 10

If it's my problem, which I don't think it is, can you tell me how I can solve this problem?
Thanks.

**Comment by bednar** [comment]
Hi @buraketmen,

the source code on GitHub contains actual development version. The `pypi` contains actual production version.

Regards

**Comment by buraketmen** [comment]
Hi @bednar ,

Thank you for your answer. Your own API Reference document also includes "org" parameter for BucketApi - create_bucket module. Related link is below. This confused me a bit. Does the document in this link also include the development environment?

[BucketApi](https://influxdb-client.readthedocs.io/en/latest/api.html#influxdb_client.BucketsApi.create_bucket)

Regards.

**Comment by bednar** [comment]
> Hi @bednar ,
> 
> Thank you for your answer. Your own API Reference document also includes "org" parameter for BucketApi - create_bucket module. Related link is below. This confused me a bit. Does the document in this link also include the development environment?

Yes, because it is link to `latest` version of docs which is related to actual sources in GitHub. The correct link is: https://influxdb-client.readthedocs.io/en/stable/

I will change the link in our README to stable version of documentation.

Regards

**Comment by buraketmen** [comment]
> > Hi @bednar ,
> > Thank you for your answer. Your own API Reference document also includes "org" parameter for BucketApi - create_bucket module. Related link is below. This confused me a bit. Does the document in this link also include the development environment?
> 
> Yes, because it is link to `latest` version of docs which is related to actual sources in GitHub. The correct link is: https://influxdb-client.readthedocs.io/en/stable/
> 
> I will change the link in our README to stable version of documentation.
> 
> Regards

Yes, I can see it's changed. I hope we can use the feature I mentioned in the production version as soon as possible.

Thanks.
