### ISSUE TITLE
How to determine possible failures during write api

### ISSUE THREAD

**Issue by witanswer** [influxdata/influxdb-client-python#279]
Hello, I am working on a piece of code to send influxdb formatted files on the local filesystem to our influxdb server.
I would like to be able to assure that a file's data has been successfully sent to the server before removing the local file.

In example code, It seems that the return values of write are not checked (as far as i can tell):

https://github.com/influxdata/influxdb-client-python/blob/master/examples/import_data_set.py#L73

And from reading the api, It seems that if the request is synchronus, it returns None

https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/write_api.py#L257

I would like to have the option to take action in certain conditions, IE:

-A badly formatted line among a large number of well formed lines
-Timeout longer than configured has occured
-Incorrect authentication has been given

How would I go about detecting this in code?

Thank you!

**Comment by bednar** [comment]
Hi @witanswer,

thanks for using our client.

> Hello, I am working on a piece of code to send influxdb formatted files on the local filesystem to our influxdb server.
> I would like to be able to assure that a file's data has been successfully sent to the server before removing the local file.
> 
> In example code, It seems that the return values of write are not checked (as far as i can tell):
> 
> https://github.com/influxdata/influxdb-client-python/blob/master/examples/import_data_set.py#L73
> 
> And from reading the api, It seems that if the request is synchronus, it returns None
> 
> https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/write_api.py#L257

The `synchronous` version of api produces `error` if something fails. You can catch this error and determine what do you want to do.

> I would like to have the option to take action in certain conditions, IE:
> 
> -A badly formatted line among a large number of well formed lines
> -Timeout longer than configured has occured
> -Incorrect authentication has been given
> 

You can use something like:

```python
import json

import urllib3

from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.rest import ApiException

url = "http://localhost:8086"
token = "my-token"
bucket = "my-bucket"
org = "my-org"

with InfluxDBClient(url=url, token=token, org=org) as client:

    write_api = client.write_api(write_options=SYNCHRONOUS)

    """
    Write data
    """
    try:
        write_api.write(bucket=bucket, record="mem,location=aws-va523 value=1")
    except ApiException as e:
        # missing credentials
        if e.status == 401:
            raise Exception(f"Incorrect authentication...") from e
        # badly formatted
        if e.status == 400:
            message = json.loads(e.body)['message']
            raise Exception(f"Badly formatted... '{message}'.") from e
        raise
    except urllib3.exceptions.TimeoutError as e:
        raise Exception(f"Timeout...") from e

```

Regards

**Comment by witanswer** [comment]
Sounds good, thanks for the assistance.

**Comment by ronytesler** [comment]
But what if the write is not synchronous, for example when using batch write, how can I know if an error has occurred?

**Comment by bednar** [comment]
Hi @ronytesler,

thanks for using our client. 

The version `1.22.0` introduces possibility to handle batch events - https://github.com/influxdata/influxdb-client-python/pull/341.

For more info see docs: 

- https://github.com/influxdata/influxdb-client-python#handling-errors
- https://influxdb-client.readthedocs.io/en/latest/usage.html#handling-errors

Regards

**Comment by ronytesler** [comment]
@bednar Thanks. So I can use:
`try:
        client.write_api(write_options=ASYNCHRONOUS).write("my-bucket", record="mem,tag=a value=86")
    except InfluxDBError as e:
        if e.response.status == 401:
            raise Exception(f"Insufficient write permissions to 'my-bucket'.") from e
        raise`

I thought that if the call is ASYNCHRONOUS, I can't just catch the error like this.

**Comment by bednar** [comment]
The `ASYNCHRONOUS` write is suppose to run with `AsyncIO`. If you would like to get the result of write you have to call `get()`:

https://github.com/influxdata/influxdb-client-python#asynchronous-client
