### ISSUE TITLE
Using regex in queries

### ISSUE THREAD

**Issue by thojdid** [influxdata/influxdb-client-python#280]
Hi,
I would like to use a regex to filter tags in my query. I only want tags that contain a certain sub-string.

In the Flux docs, I found this example to filter fields that contain the string "_percent" (https://docs.influxdata.com/influxdb/cloud/query-data/flux/regular-expressions/) :

from(bucket: "example-bucket")
  |> range(start: -15m)
  |> filter(fn: (r) =>
    r._measurement == "mem" and
    r._field =~ /_percent/
  )

but the operator =~ does not seem to work with the client.

How could I achieve this?

Thanks in advance

**Comment by thojdid** [comment]
Hi Bednar,
I tried again and it's finally working. Something else seemed to have been the cause in my code. 
Thanks a lot!

**Comment by bednar** [comment]
@thojdid You are welcome

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
