### ISSUE TITLE
[BUG] Unable to parse cell data

### ISSUE THREAD

**Issue by abhi1693** [influxdata/influxdb-client-python#282]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
```python
from influxdb_client import CellsService
from influxdb_client.domain.create_cell import CreateCell

create_cell_request = CreateCell(name="test", h=3, w=12)
cell = CellsService().post_dashboards_id_cells(dashboard_id=dashboard_id, create_cell=create_cell_request)
print(cell.get('id'))
```

The issue is at https://github.com/influxdata/influxdb-client-python/blob/e34637dfd22a2b380fcb35a67c3ad1e51c025437/influxdb_client/service/cells_service.py#L378

The `response_type` should have been `object`.

PS: This issue is also in various other places of the code as well. The services should return `object` but they dont.

__Expected behavior:__
This should have returned a `dict` on which the `get` method can be used.

__Actual behavior:__
AttributeError: 'Cell' object has no attribute 'get'

__Specifications:__
 - Client Version: 1.18.0
 - InfluxDB Version: 2.0.5
 - Platform: Linux

**Comment by abhi1693** [comment]
@bednar Another issue with OpenAPI specification. Can you please take a look?

**Comment by abhi1693** [comment]
Ok, so my issue is reversed. `Cell` object being returned is fine. But the `Dashboard` returns a `dict` instead of an object. That seems inconsistent.

**Comment by bednar** [comment]
@abhi1693 thanks for using our client, we will take a look
