### ISSUE TITLE
Add support for serialise query response into Pandas Data Frame

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-python#29]
- [x] Serialisation
- [ ] Jupyter notebook

**Comment by Anaisdg** [comment]
Hey @bednar I've started some of this work here:
https://github.com/influxdata/influxdb-client-python-pandas 
It includes: 
-generating the flux query 
-converting the flux query to a dataframe

**Comment by bednar** [comment]
Hi @Anaisdg,

I am glad to hear about it. It's a nice piece a work :thumbsup:.

I am going to prepare support for streaming a query response (#30), so together we will be able to achieve something like this - https://matthewrocklin.com/blog/work/2017/10/16/streaming-dataframes-1
