### ISSUE TITLE
Is InfluxDB enough fast for query data inside a Pytorch Dataloader/Tensorflow Generator

### ISSUE THREAD

**Issue by TommasoBendinelli** [influxdata/influxdb-client-python#292]
Hello,
I would like to have a server running InfluxDB and running queries on the fly for training a machine learning algorithm. Do you think that performance-wise querying/influxDB will be the bottleneck? What is the lowest latency I can achieve? 

Best,
Tommaso

**Comment by bednar** [comment]
Hi @TommasoBendinelli,

thanks for using our client.

> Do you think that performance-wise querying/influxDB will be the bottleneck?

It depends on your data. How many data do you want to retrieve in every query?

> What is the lowest latency I can achieve?

Try to retrieve only data that you needs - use [drop() function](https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/) and optimize your query - https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/

Regards

**Comment by TommasoBendinelli** [comment]
Hi Bednar, 
Thank you for your reply. I would need to query 32 (batch size) * 1024 (Window length) * 32 (Number of channels) points for each batch. Retrieving data should be around 1/2 seconds for not being the bottleneck. Do you think it is possible?

**Comment by bednar** [comment]
>  Do you think it is possible?

Yes. I will be happy to help you with any problems

**Comment by TommasoBendinelli** [comment]
Cool! Then I will try and let you know

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
