### ISSUE TITLE
IndexError: list index out of range with query_data_frame | InfluxDB v1.9

### ISSUE THREAD

**Issue by apogre** [influxdata/influxdb-client-python#295]
I am using influxdb-client with flux query to get results as a data frame. 

I am getting the error as follows.

```
2021-07-29 16:57:08,441 Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2021-07-29 16:57:08,441 Starting new HTTP connection (1): url:80
send: b'POST /api/v2/query?org=xxx HTTP/1.1\r\nHost: url\r\nContent-Length: 482\r\nAccept: application/json\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\nAuthorization: Token token==\r\nUser-Agent: influxdb-client-python/1.19.0\r\n\r\n'
send: b'{"extern": {"imports": [], "body": []}, "query": "from(bucket:\\"bucket\\")|> range(start: 2019-03-09T10:28:52Z, stop: 2021-03-09T10:28:52Z) |> filter(fn: (r) => r._measurement == \\"M\\")|> filter(fn: (r) => r.tag == \\"tag\\")|> filter(fn: (r) => r[\\"_field\\"] == \\"field1\\") |> max()", "dialect": {"header": true, "delimiter": ",", "annotations": ["datatype", "group", "default"], "commentPrefix": "#", "dateTimeFormat": "RFC3339"}}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 29 Jul 2021 23:57:08 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 336
header: Connection: keep-alive
header: Accept-Ranges: bytes
header: Cache-Control: public, max-age=3600
header: Content-Security-Policy: script-src 'self'; object-src 'self'
header: Etag: "33628162924"
header: Last-Modified: Wed, 21 Jul 2021 00:01:55 GMT
header: Vary: Accept-Encoding
header: X-Chronograf-Version: 1.9.0
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-Xss-Protection: 1; mode=block
2021-07-29 16:57:08,582 http://url:80 "POST /api/v2/query?org=xxx HTTP/1.1" 200 336
2021-07-29 16:57:08,582 Query from(bucket:"bucket")|> range(start: 2019-03-09T10:28:52Z, stop: 2021-03-09T10:28:52Z) |> filter(fn: (r) => r._measurement == "M")|> filter(fn: (r) => r.tag == "tag")|> filter(fn: (r) => r["_field"] == "field1") |> max() Error: list index out of range
Traceback (most recent call last):
  File "/Users/ap/Projects/intermediate_loader/utils/influxdb_query_util.py", line 106, in get_min_max_dts_time
    max_result = self.client.query_api().query_data_frame(query=max_dts_query)
  File "/Users/ap/Projects/intermediate_loader/.venv/lib/python3.9/site-packages/influxdb_client/client/query_api.py", line 147, in query_data_frame
    _dataFrames = list(_generator)
  File "/Users/ap/Projects/intermediate_loader/.venv/lib/python3.9/site-packages/influxdb_client/client/flux_csv_parser.py", line 71, in generator
    yield from parser._parse_flux_response()
  File "/Users/ap/Projects/intermediate_loader/.venv/lib/python3.9/site-packages/influxdb_client/client/flux_csv_parser.py", line 89, in _parse_flux_response
    if "error" == csv[1] and "reference" == csv[2]:
IndexError: list index out of range

```

**Comment by bednar** [comment]
Hi @apogre,

thanks for using our client.

Could you share how looks like the output of your query in Influx UI or CSV file? Currently I am not able to reproduce this error.

Regards

**Comment by apogre** [comment]
Hi @bednar 
Here is the csv output:
```
#group,false,false,true,true,false,false,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,session
,,0,2018-10-07T10:42:08Z,2020-10-07T10:42:08Z,2019-10-07T18:21:59.225Z,27494.3,field_x,measurement_x,session_x


```

**Comment by bednar** [comment]
@apogre, thanks for detail information. 

The issue is fixed in PR #297. If you would like to use a dev version then install the client via:

```console
pip install git+https://github.com/influxdata/influxdb-client-python.git@fix/csv_parser
```

Regards

**Comment by apogre** [comment]
Thanks @bednar 
However, got this error with the update:

`Traceback (most recent call last):
  File "/Users/ap/Projects/intermediate_loader/main.py", line 88, in <module>
    dts_start, dts_stop = query_obj.get_min_max_dts_time(session_name=session_name)
  File "/Users/ap/Projects/intermediate_loader/utils/influxdb_query_util.py", line 107, in get_min_max_dts_time
    max_result = self.client.query_api().query_data_frame(query=max_dts_query)
  File "/Users/ap/Projects/intermediate_loader/.venv/lib/python3.9/site-packages/influxdb_client/client/query_api.py", line 147, in query_data_frame
    _dataFrames = list(_generator)
  File "/Users/ap/Projects/intermediate_loader/.venv/lib/python3.9/site-packages/influxdb_client/client/flux_csv_parser.py", line 71, in generator
    yield from parser._parse_flux_response()
  File "/Users/ap/Projects/intermediate_loader/.venv/lib/python3.9/site-packages/influxdb_client/client/flux_csv_parser.py", line 115, in _parse_flux_response
    raise FluxCsvParserException("Unable to parse CSV response. FluxTable definition was not found.")
influxdb_client.client.flux_csv_parser.FluxCsvParserException: Unable to parse CSV response. FluxTable definition was not found.`

**Comment by bednar** [comment]
@apogre thanks for your testing, currently I am not able to simulate this exception even with your output from Chronograph UI.

Can you share an output from “raw” query?

```python
raw = query_api.query_raw('your query')
print(raw)
```

**Comment by apogre** [comment]
Hi @bednar 

Please find below:

```
from influxdb_client import InfluxDBClient
from pprint import pformat

db_client = InfluxDBClient(
    url="https://{url}/",
   token={token})

query = 'from(bucket:"{bucket}")|> range(start: 2019-10-05T10:42:08Z, stop: 2019-10-09T10:42:08Z) |> filter(fn: (r) => r._measurement == "{measurement_x}")|> filter(fn: (r) => r.session == "{SESSION_x}")|> filter(fn: (r) => r["_field"] == "{field_x}") |> max()'

output = db_client.query_api().query_raw(query)

print(output)

print(pformat(output.__dict__))
```

Output:
<urllib3.response.HTTPResponse object at 0x101a89d90>

`{'_body': None,
 '_connection': <urllib3.connection.HTTPSConnection object at 0x10b2c4b20>,
 '_decoder': None,
 '_fp': <http.client.HTTPResponse object at 0x10b2c4cd0>,
 '_fp_bytes_read': 0,
 '_original_response': <http.client.HTTPResponse object at 0x10b2c4cd0>,
 '_pool': <urllib3.connectionpool.HTTPSConnectionPool object at 0x10b2c4550>,
 '_request_url': 'https://{url}/api/v2/query?org=None',
 'auto_close': True,
 'chunk_left': None,
 'chunked': False,
 'decode_content': True,
 'enforce_content_length': False,
 'headers': HTTPHeaderDict({'Date': 'Fri, 06 Aug 2021 19:07:28 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '336', 'Connection': 'keep-alive', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=3600', 'Content-Security-Policy': "script-src 'self'; object-src 'self'", 'Etag': '"33628162924"', 'Last-Modified': 'Wed, 04 Aug 2021 01:08:00 GMT', 'Vary': 'Accept-Encoding', 'X-Chronograf-Version': '1.9.0', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block'}),
 'length_remaining': 336,
 'msg': None,
 'reason': 'OK',
 'retries': Retry(total=False, connect=None, read=None, redirect=0, status=None),
 'status': 200,
 'strict': 0,
 'version': 11}`

**Comment by bednar** [comment]
@apogre it looks like that your url points to `Chronograf` instead to InfluxDB. See header response: 'X-Chronograf-Version': '1.9.0'

Is your `url` correctly configured?

**Comment by bednar** [comment]
You are welcome
