### ISSUE TITLE
ReadTimeoutError  - always after 40m

### ISSUE THREAD

**Issue by ot3** [influxdata/influxdb-client-python#296]
I'm migrating from a bare metal ubuntu instance running InfluxDB 1.8 to a ProxMox virtualized server running InfluxDB 2.07. The Python code captures a MQTT message once per second and stores the resulting data in InfluxDB. This invariably fails after approx. 40 minutes. Here's part of the output:

```
2021-08-02 13:33:59  MONITOR             MainThread  PAYLOAD: '1627904031', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.05', ' 0', ' 3460', ' 10029.261', ' 1627903800'
2021-08-02 13:34:08  MONITOR             MainThread  PAYLOAD: '1627904032', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.051', ' 0', ' 3462', ' 10029.261', ' 1627903800'
2021-08-02 13:34:10  WARNING ThreadPoolExecutor-0_0  The retriable error occurred during request. Reason: 'HTTPConnectionPool(host='192.168.178.221', port=8086): Read timed out. (read timeout=0)'.
2021-08-02 13:34:12  MONITOR             MainThread  PAYLOAD: '1627904033', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.052', ' 0', ' 3467', ' 10029.261', ' 1627903800'
2021-08-02 13:34:17  MONITOR             MainThread  PAYLOAD: '1627904034', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.053', ' 0', ' 3467', ' 10029.261', ' 1627903800'
2021-08-02 13:34:18  MONITOR             MainThread  PAYLOAD: '1627904035', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.054', ' 0', ' 3465', ' 10029.261', ' 1627903800'
2021-08-02 13:34:21  WARNING ThreadPoolExecutor-0_0  Retrying (WritesRetry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.178.221', port=8086): Read timed out. (read timeout=0)",)': /api/v2/write?org=Araminta+Station&bucket=energy&precision=s
2021-08-02 13:34:23  MONITOR             MainThread  PAYLOAD: '1627904036', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.055', ' 0', ' 3447', ' 10029.261', ' 1627903800'
2021-08-02 13:34:23  MONITOR             MainThread  PAYLOAD: '1627904037', ' 10841.152', ' 6296.465', ' 11708.444', ' 26161.056', ' 0', ' 3460', ' 10029.261', ' 1627903800'

```

To debug this issue I tried many different options and combinations:

- old API v.s. new API
- synchronous v.s. asynchronous
- batched v.s. non-batched
- InfluxDB 2.07 v.s. InfluxDB 1.8
- bare metal v.s. virtualized

The result is always that all scenarios with the new API fail and all scenarios with the old API succeed. Failure in this case means the above error message followed after a few seconds with the program becoming unresponsive and the CPU load going to 100%.

I can't determine if the problem is in my code or in the APi or somewhere else. Here are the relevant parts of the code:

```
def on_p1_received(client, obj, msg):  # convert MQTT message to InfluxDB points
    payload = msg.payload.decode().strip('[').strip(']').split(',')
    logging.monitor('PAYLOAD: %s', str(payload)[1:-1])

    points = []
    point = {  # format is JSON
        'measurement': 'electricity',
        'time': int(payload[0]),  # every 1s
        'fields': {
            'cT1': float(payload[1]),   # ELECTRICITY_USED_TARIFF_1
            'cT2': float(payload[2]),   # ELECTRICITY_USED_TARIFF_2
            'fT1': float(payload[3]),   # ELECTRICITY_DELIVERED_TARIFF_1
            'fT2': float(payload[4]),   # ELECTRICITY_DELIVERED_TARIFF_2
            'Pc' : int(payload[5]),     # CURRENT_ELECTRICITY_USAGE
            'Pf' : int(payload[6]),     # CURRENT_ELECTRICITY_DELIVERY
        },
    }
    points.append(point)
    point = {  # format is JSON
        'measurement': 'gas',
        'time': int(payload[8]),  # every 300s
        'fields': {
            'gas': float(payload[7]),   # HOURLY_GAS_METER_READING (ACTUAL: once per 300s)
        },
    }
    points.append(point)
    write_options = WriteOptions(
        SYNCHRONOUS,
        batch_size=5,
        flush_interval=5000,
        jitter_interval=500,
        retry_interval=1000,
        max_retries=3,
        max_retry_delay=10000,
        exponential_base=2
                                 )
    try:
        result = influx_client.write_api().write(
            record=points,
            bucket=influx.bucket,
            write_options=write_options,
            write_precision=WritePrecision.S,
        )
    except ApiException as e:
        # missing credentials
        if e.status == 401:
            raise Exception(f"Incorrect authentication...") from e
        # badly formatted
        if e.status == 400:
            message = json.loads(e.body)['message']
            raise Exception(f"Badly formatted... '{message}'.") from e
        raise
    except urllib3.exceptions.TimeoutError as e:
        raise Exception(f"Timeout...") from e
    logging.debug('RESULT: %s', result)

```
and

```
def receive_p1():
    logging.monitor('TOPIC: %s', influx.topic)
    client = mqtt.Client()
    client.connect(settings.broker, 1883, 120)
    client.message_callback_add(influx.topic, on_p1_received)
    client.subscribe([(influx.topic, 0)])
    client.loop_forever()
```

and

```
    with InfluxDBClient(url=influx.url, token=influx.token, org=influx.org, debug=False) as influx_client:
        receive_p1()
```

__Specifications:__
 - Client Version: 1.19.0
 - InfluxDB Version: 2.07
 - Platform: Ubuntu 20.04 virtualized on ProxMox

**Comment by bednar** [comment]
Hi @ot3,

thanks for using our client.

You have to use the `write_options` as a parameter for `write_api()`:

```python
result = influx_client.write_api(write_options=write_options).write(
            record=points,
            bucket=influx.bucket,
            write_precision=WritePrecision.S,
        )
```

Regards

**Comment by ot3** [comment]
Hi @bednar,

Thanks for the quick reply. I changed the code as per your suggestion and can report that it has been running now for over an hour without problems. 

This does raise a few question though:

1. can you kindly point me to the relevant section in the documentation so I can avoid this kind of problem in the future?
2. I obviously used the wrong syntax originally. But it strikes me as problematic that it takes 40m for this to become apparent and that there's no feedback whatsoever until the CPU goes to 100% load. Is there a way to get more useable and timely feedback in case of API syntax errors like this?

**Comment by bednar** [comment]
> 1. can you kindly point me to the relevant section in the documentation so I can avoid this kind of problem in the future?

Probably the best sources are [README.md](https://github.com/influxdata/influxdb-client-python#getting-started) and [examples](https://github.com/influxdata/influxdb-client-python/tree/master/examples#examples).
 
> 2. I obviously used the wrong syntax originally. But it strikes me as problematic that it takes 40m for this to become apparent and that there's no feedback whatsoever until the CPU goes to 100% load. Is there a way to get more useable and timely feedback in case of API syntax errors like this?

You can enable a debug mode for tuning your script by:

```python
_client = InfluxDBClient(url="http://localhost:8086", token="my-token", debug=True, org="my-org")
```

**Comment by bednar** [comment]
Re: 1 - We have these docs:

* [Product documentation](https://docs.influxdata.com/influxdb/v2.0/tools/client-libraries/), [Getting Started](https://github.com/influxdata/influxdb-client-python/blob/master/README.rst#getting-started)
* [Examples](https://github.com/influxdata/influxdb-client-python/tree/master/examples)
* [API Reference](https://influxdb-client.readthedocs.io/en/stable/api.html)
* [Changelog](https://github.com/influxdata/influxdb-client-python/blob/master/CHANGELOG.md)

Re: 2: The [API Reference](https://influxdb-client.readthedocs.io/en/stable/api.html) is useful here. Because of the dynamic nature of Python we are not able provide syntax checking.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
