### ISSUE TITLE
Using query_api, is there a way to know if a returned column is a tag or a field type? 

### ISSUE THREAD

**Issue by merwync** [influxdata/influxdb-client-python#298]
I can see data-type, default value, etc per column in a flux request (returning fluxTable), but is there a way to know if a key is a tag or a field without having to import the schema package, make an initial call to identify tags, then a second to get all the values and cross reference with those tags? 

So, is it possible to have 'field' or 'tag' value somewhere in one query?

**Comment by bednar** [comment]
Hi @merwync,

thanks for using our client. 

The `tag` column has `group` set to `True` - https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/flux_table.py#L44

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
