### ISSUE TITLE
no data written when providing .time in Point

### ISSUE THREAD

**Issue by yosiasz** [influxdata/influxdb-client-python#307]
List the minimal actions needed to reproduce the behavior.

Greetings,

Using python and trying to push data to influxdb
1. Sample data

2. The following does not work (with .time)
```
    r = Point("packets") \
        .tag("radiotype", "X") \
        .field("allocation", 5.32) \
        .time(1627883568357) --I have tried all kinds of dates and the shown seconds
    write_api.write(bucket=bucket, record=r)
```
3. The following does work (without time)
```
    r = Point("packets") \
        .tag("radiotype", "X") \
        .field("allocation", 5.32) \
    write_api.write(bucket=bucket, record=r)
```

__Expected behavior:__
I would expect that it would write to db with provided time stamp

__Actual behavior:__
Does not write any of the data when provided with time value

__Specifications:__
 - Client Version: Python 3.9
 - InfluxDB Version: 2
 - Platform: Windows 10
 
Hope I have provided enough details

Thanks!

**Comment by bednar** [comment]
Hi @yosiasz,

thanks for using our client. The timestamp `1627883568357` is `Monday, 2 August 2021 05:52:48.357` with **milliseconds** precision.

The default precision for the client are `nonoseconds`, so you have to use something like:

```python
from influxdb_client import WritePrecision, InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org") as client:
    write_api = client.write_api(write_options=SYNCHRONOUS)
    r = Point("packets") \
        .tag("radiotype", "X") \
        .field("allocation", 5.32) \
        .time(1627883568357, write_precision=WritePrecision.MS)
    write_api.write(bucket="my-bucket", record=r)
```

Regards

**Comment by yosiasz** [comment]
That was it!
