### ISSUE TITLE
How to get all dashboards for a list of labels?

### ISSUE THREAD

**Issue by abhi1693** [influxdata/influxdb-client-python#308]
Suppose, I have 100 dashboards and most of them have 2 or more labels. Let say I want to filter all the dashboards with the labels `system`, `performance` and `user:abc`. Is there any method that I can use? Or, should I create my own methods to do filtering tasks?

**Comment by bednar** [comment]
Hi @abhi1693,

unfortunately, the [Dashboard API](https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetDashboards) doesn't supports filtering by `labels`. You have to write your own method.

Regards

**Comment by abhi1693** [comment]
Thanks for the information. I wrote my filter for this but shouldn't this be added to library?

**Comment by bednar** [comment]
> Thanks for the information. I wrote my filter for this but shouldn't this be added to library?

We are not able to supports all possible use-cases for API, but every PR welcome. Please feel free to create PR with this function and we will be happy to accept it.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
