### ISSUE TITLE
Is there any way to check if client has finished batch insertion?

### ISSUE THREAD

**Issue by zcattacz** [influxdata/influxdb-client-python#309]
I am using the latest lib from pypi. The client is doing batch insertion as suggested in the document in a separate background thread in my code. Every time the job queue is cleared, the main thread exit, the script always drop a few errors like this

'''
 ThreadPoolExexutor-0_0[write_api]: The batch item wasn't processed successfully because cannot schedule new futures after interpreter shutdown.
'''
I assume the insertion has not actually finished yet,  The documentation doesn't seem to have covered this, I would like to ask if there is any way to check if the batch insertion has actually finished, so that the main thread could wait for it.

**Comment by bednar** [comment]
Hi @zcattacz,

thanks for using our client.

> I would like to ask if there is any way to check if the batch insertion has actually finished, so that the main thread could wait for it.

You can call the `close()` function on the `write_api`. Something like following code should works:

```python
self.write_api.close()
```

Regards

**Comment by zcattacz** [comment]
thank you that seems to have fixed the problem.

**Comment by hf-kklein** [comment]
I ran into the suggestion to call `close()` on the write_api fixed it for me, too.
However I wonder why calling `client.close()` alone doesn't properly close the write_api which is part of the client?

**Comment by atsag** [comment]
In my case I was trying to insert values to Influxdb using batching, from within another Handler-type execution context (i.e not executing on the main thread but inside an on_message function) and calling write_api.close() was not enough - I had to bring the code to the main thread.

**Comment by zcattacz** [comment]
That makes sense: the main thread is blocked by close() to avoid early exit.
