### ISSUE TITLE
Many timeout message, do I need to adjust insertion parameters?

### ISSUE THREAD

**Issue by zcattacz** [influxdata/influxdb-client-python#310]
Following last question, my script use default logger at debug level I saw many many timeout messages eg.
’’’
ThreadPoolExecutor-0_0[eventloopscheduler]: timeout: 1.902
’’’
Is this normal?  does it mean my bulk insertion parameters are not in tune ?

bulk size 5000
flush interval 10 000
jitter interval 2 000
retry interval 5 000
max retry 5
max retry delay 30 000
exponential base 2

basically direct copy from doc.
Its inserting slow though (imho).

**Comment by zcattacz** [comment]
I updated the parameters to the following now it reduced to  5 timeouts between each batch insertion

bulk size 50 000
flush interval 20 000

Also gzip is enabled, now for a day long archive, the insertion takes about 20s compared to prev 1min+, not too bad 😀

**Comment by bednar** [comment]
Hi @zcattacz,

it could be caused by HTTP Timeout. Try to increase the HTTP timeout:

```
from influxdb_client import WritePrecision, InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", timeout=20_000) as client:
    pass
```

also the `jitter` interval is useless if you ingesting data only from one "source".

There is also an example how to use synchronous WriteApi to one-time import of data - [import_data_set_sync_batching.py](https://github.com/influxdata/influxdb-client-python/blob/master/examples/import_data_set_sync_batching.py)

**Comment by zcattacz** [comment]
Thanks for the explanation.

**Comment by mprudek** [comment]
Thanks a lot for this Q&A. It saved me a lot of desperate searching.

There should be definitely an example of `timeout` usage in the `README.md` anyway.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
