### ISSUE TITLE
Make FluxTable and FluxRecord json serializable

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-client-python#311]
it would be really handy for debugging if the objects returned from the write_api were json serializable by default (FluxTable and FluxRecord). this would avoid the need to do stuff like `json.dumps(record.__dict__)`

I think for this you would simply need to supply a `toJSON` function in those classes.

**Comment by bednar** [comment]
@russorat thanks for suggestion to enhancement, I will take a look.

**Comment by bednar** [comment]
@russorat, unfortunately  the `toJSON` is not enough. Because `json.dumps` needs to have defined  a `default` parameter that returns a serializable object.

I have prepared a `FluxStructureEncoder` encoder which simplifies usage of json encoder to:

```python
import json
from influxdb_client.client.flux_table import FluxStructureEncoder

output = json.dumps(tables, cls=FluxStructureEncoder, indent=2)
print(output)
```
