### ISSUE TITLE
Nanosecond Precision

### ISSUE THREAD

**Issue by dkasianov** [influxdata/influxdb-client-python#314]
https://github.com/influxdata/influxdb-client-python/blob/f455a87d6813c91b0354717d8d8e717bfacb1cdc/influxdb_client/client/write/point.py#L209

It seems that python client not support insert of nanosecond precision, I try to use standard timestamp precision and found out that it doesn't support nanoseconds precision to achieve that I use pandas, it seems your client depends on standard one and its cut off nanoseconds precision.

Maybe this not the case (I am not experienced in Python) but I can't write down pandas timestamp with nanosecond precision into client.

Thanks,
Daniil

**Comment by bednar** [comment]
Hi @dkasianov,

thanks for using our client.

The Python's [datetime](https://docs.python.org/3/library/datetime.html) doesn't support precision with nanoseconds so the library during writes and queries ignores everything after microseconds.

If you would like to use `datetime` with nanosecond precision you should use `pandas.Timestamp` that is replacement for python `datetime.datetime` object and also you should set a proper `DateTimeHelper` to the client.

for more info see - https://github.com/influxdata/influxdb-client-python#nanosecond-precision

Regards

**Comment by dkasianov** [comment]
Thanks, I did goggle that but answer was under my nose.
