### ISSUE TITLE
InfluxDBClient throws NewConnectionError without timeout  

### ISSUE THREAD

**Issue by stefanbie** [influxdata/influxdb-client-python#323]
Hi! Im using Python 3.8.10 and influxdb-client 1.17.0 

I have disconnected my local network connection and I do 

```
client = InfluxDBClient(url=url, token=token, org=org, timeout=10000)
write_api = self.client.write_api(write_options=SYNCHRONOUS)
try:
  self.write_api.write(bucket=bucket, org=org, record=points)
except NewConnectionError as exc:
  print(exc)

```
... then the NewConnectionError is thrown immediately, without waiting for the 10 second timeout. Have I misunderstood something?

**Comment by bednar** [comment]
I am not sure if i understood correctly, but If you would like to retry write attempt on the `NewConnectionError` exception then you have to configure `Retry Strategy`. For more info see - https://github.com/influxdata/influxdb-client-python#http-retry-strategy

**Comment by stefanbie** [comment]
Hi Jacub! My interpretation of the documentation was that the connection establishment during (for example) a write would wait 10 seconds before throwing a NewConnectionError exception, especially since I specify that in the InfluxDBClient. Have I misunderstood?

**Comment by bednar** [comment]
The `timeout` is applied to socket connecting between the client and server. Because there is no socket connection the timeout cannot be apply.

For more info see - https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html?highlight=timeout#urllib3.util.Timeout

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
