### ISSUE TITLE
Suggestion for multiple inserts

### ISSUE THREAD

**Issue by stefanoromanello** [influxdata/influxdb-client-python#325]
Hi all, I'm using the influxdb_client python library to manage my db. Is it possible to edit the value of a field without creating a new one? Or is it better to write a new record every time and use the aggregate function of influx to sum the values?
I'm planning to update the values every 2 minutes..
Also, I need to insert/update every 2 minutes about 2000 measurements. Do I run
p = influxdb_client.Point("measurementName").tag("target", "Google").field("fieldName", value)
write_api.write(bucket=bucket, org=org, record=p)
2000 times or is there a better function?

**Comment by bednar** [comment]
Hi @stefanoromanello,

thanks for using our client.

The best strategy for you will be use the synchronous `write_api`: 

```python
from influxdb_client.client.write_api import SYNCHRONOUS
write_api = client.write_api(write_options=SYNCHRONOUS)
```

and write all your data in one bulk:

```python
var points = []
p = influxdb_client.Point("measurementName").tag("target", "Google").field("fieldName", value)

points.add(p)
...

write_api.write(bucket=bucket, org=org, record=points)
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
