### ISSUE TITLE
write api lost data if points exceeding 1000.

### ISSUE THREAD

**Issue by helldragonx** [influxdata/influxdb-client-python#332]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1.  prepared over 1000 points to write.
2. calling such python codes:
    if len(points) > 0:
                                print("ETF write_api beg, size=", len(points),listdbtime)
                                ret = write_api.write(writebucket, writeorg, points) # first time will lost all points outside 1000 position
                                print("ETF write_api end", ret)
                                ret = write_api.write(writebucket, writeorg, points) # second time with same points can fix the lost.
                                print("ETF write_api end", ret) 
                                # print(dict_ticker)
                                points.clear()

__Expected behavior:__
shall not lost any points.

__Actual behavior:__

__Specifications:__
 - Client Version:
    current release version v1.21.0
 - InfluxDB Version:
    v2.0.8 Open Source
 - Platform:
   Windows server 2012 R2

**Comment by thanhdat6716** [comment]
Hi, Can I ask you something?

1. How can you prepare 1000 points?
2. Did you your data point along with the time parameter?
3. If yes, what is the time value you attached with? 
```
.time(datetime.utcnow(), WritePrecision.NS)
```
or given time? 
```
.time(datetime.datetime(abc))
```

**Comment by bednar** [comment]
Hi @helldragonx,

thanks for using our client.

How do you initialize the `write_api`? 

The default behaviour of `write_api` is asynchronous background batching mode. So you should wrap the execution using `with client.write_api(…) as write_api:` statement or call `_write_client.close()` at the end of your script.

If you want only ingest data without underlaying batching, you can use `synchronous` mode of client - https://influxdb-client.readthedocs.io/en/stable/usage.html#synchronous-client.

Regards

**Comment by bednar** [comment]
Hi @thanhdat6716,

here are examples how to write large amount of data: https://github.com/influxdata/influxdb-client-python/blob/8539a9bc79c5bcf6f39fd549f163f0176b5664b4/examples/README.md#writes

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
