### ISSUE TITLE
Write DataPoint with specific time

### ISSUE THREAD

**Issue by thanhdat6716** [influxdata/influxdb-client-python#333]
I have a sensor MSSQL database, and I want to write these things to InfluxDB.

__Steps to reproduce:__

1. Read sensor data line by line.
[**(4893172, 'K-311227', 17, datetime.datetime(2021, 7, 28, 8, 23, 34, 993000), 4, 5, 14, 0, 0.0, 0.0, 62.587481, 0, 22710, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'SERVER')**]
2. Extract data to point and write. The is no error but I **can not** get the data in "Data Explorer" in InfluxDB UI.
```
point = Point(name)\
            .tag("host",            row[25])\
            .tag("sender",          sender)\
            .tag("Heat_No",         row[1])\
            .field("event_code",    row[2])\
            .field("step_no",       row[4])\
            .field("process_no",    row[5])\
            .field("tap_no",        row[6])\
            .field("voltage_value", row[7])\
            .field("current_value", row[8])\
            .field("insert_amount", row[9])\
            .field("pwr_factor",    row[10])\
            .field("temperature",   row[11])\
            .field("total_power",   row[12])\
            .time(row[3])
write_api.write(bucket, org, point)
```
3. But when I write with **.time(datetime.utcnow(), WritePrecision.NS)**. It works. I **can** get data in "Data Explorer".
```
point = Point(name)\
            .tag("host",            row[25])\
            .tag("sender",          sender)\
            .tag("Heat_No",         row[1])\
            .field("event_code",    row[2])\
            .field("step_no",       row[4])\
            .field("process_no",    row[5])\
            .field("tap_no",        row[6])\
            .field("voltage_value", row[7])\
            .field("current_value", row[8])\
            .field("insert_amount", row[9])\
            .field("pwr_factor",    row[10])\
            .field("temperature",   row[11])\
            .field("total_power",   row[12])\
           .time(datetime.utcnow(), WritePrecision.NS)
write_api.write(bucket, org, point)
```

__Expected behavior:__
I want to write data with the specific time

__Actual behavior:__

__Specifications:__
 - Client Version: Latest
 - InfluxDB Version: 2.0.8
 - Platform: Anaconda/Python 3.8/Windows 10. IDE: Spyder, Jupyter.

**Comment by thanhdat6716** [comment]
When I try to debug the library (**write_api.py**), I added  _print_ in function **def write_payload(payload):** definition
```
249:  _async_req = True if self._write_options.write_type == WriteType.asynchronous else False
250:  
251:          def write_payload(payload):
252:              final_string = b'\n'.join(payload[1])
253:              print(_async_req)
254:              print(bucket)
255:              print(org)
256:              print(final_string)
257:              print(payload[0])
258:              return self._post_write(_async_req, bucket, org, final_string, payload[0])
```
The result with **utcnow()** is: 
```
False
IPC61
ABCD
b'Event,Heat_No=K-311253,host=IPC60_SERVER,sender=python_thanh current_value=0,event_code=16i,insert_amount=0,process_no=0i,pwr_factor=100,step_no=4i,tap_no=12i,temperature=1624i,total_power=29230i,voltage_value=0i 1632717805389544000'
ns
```
The result with **specific time (row[3])** is: 
```
False
IPC61
ABCD
b'Event,Heat_No=K-311253,host=IPC60_SERVER,sender=python_thanh current_value=0,event_code=16i,insert_amount=0,process_no=0i,pwr_factor=100,step_no=4i,tap_no=12i,temperature=1624i,total_power=29230i,voltage_value=0i 1627533747997000000'
ns
```
The difference is only timestamping, 1632717805389544000 vs 1627533747997000000.

**Comment by thanhdat6716** [comment]
I found the problem is that update python and IDE versions.

**Comment by thanhdat6716** [comment]
Client debug=True output
send: b'POST /api/v2/write?org=OCST&bucket=IPC61&precision=ns HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 233\r\nContent-Encoding: identity\r\nContent-Type: text/plain\r\nAccept: application/json\r\nAuthorization: Token Gg0dCkiib8M6Y9dAiiYkbL7y9MxDXt8Y20lp6dak2H8SFEM3oE1THEplvoRcru9ZePPS5FcoBl8qdBj6CNaRQg==\r\nUser-Agent: influxdb-client-python/1.21.0\r\n\r\n'
send: b'Event1,Heat_No=K-311286,host=SERVER,sender=python_thanh current_value=0,event_code=44i,insert_amount=0,process_no=0i,pwr_factor=100,step_no=4i,tap_no=12i,temperature=1669i,total_power=28100i,voltage_value=0i 1627631031997000000'
reply: 'HTTP/1.1 204 No Content\r\n'
header: Date: Tue, 28 Sep 2021 02:11:57 GMT
Heater K-311286 - 2021-07-30 07:43:51.997000

**Comment by thanhdat6716** [comment]
I also try to write data points by C# and try to write in ubuntu OS, InfluxCloud but the same thing occurred. Could it be something wrong when installing influxdb?

**My installation step:**

1. Download and extract data to directory: 'C:\Program Files\InfluxData\influxdb\'
2. Start PowerShell (I tried admin and non-admin), then start influxdb: .\influxd.exe
3. Then write data points.

**Comment by thanhdat6716** [comment]
It works normally with Influx v1.7.
So I think this is an influxdb bug.

**Comment by bednar** [comment]
Hi @thanhdat6716,

thanks for using our client.

Your timestamp: `1627533747997000000` is `Thursday, 29 July 2021 04:42:27.997`. Do you have correct time range in UI?

![Screenshot 2021-09-29 at 7 19 17](https://user-images.githubusercontent.com/455137/135207848-5ce68123-0b97-4031-8444-231f0c332b81.png)


Regards

**Comment by thanhdat6716** [comment]
> Hi @thanhdat6716,
> 
> thanks for using our client.
> 
> Your timestamp: `1627533747997000000` is `Thursday, 29 July 2021 04:42:27.997`. Do you have correct time range in UI?
> 
> ![Screenshot 2021-09-29 at 7 19 17](https://user-images.githubusercontent.com/455137/135207848-5ce68123-0b97-4031-8444-231f0c332b81.png)
> 
> Regards

Hi bednar,
That's reason.
Thank you sooo much!
Awesome 👍
