### ISSUE TITLE
Cannot write to the bucket --> Reason: SSLError [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)

### ISSUE THREAD

**Issue by BerniZindel** [influxdata/influxdb-client-python#337]
__Steps to reproduce:__

script worked fine and last successful write was @ 2021-09-24. I trigger the script manually out of PyCharm on anaconda environment so I just know, that between 09-24 and today 09-30 something went broken.
I already did a search but did not find anything helpful to that issue.

code snippet:

```
[...]
p = influxdb_client.Point("EH").tag("id",df_dist.loc[element][1]).field("distance",df_dist.loc[element][0]).time(element,)
client = influxdb_client.InfluxDBClient(url="https://eu-central-1-1.aws.cloud2.influxdata.com/", token=token, org=organization)
write_api = client.write_api(write_options=SYNCHRONOUS)
write_api.write(bucket="bzi",record=p)
```

__Expected behavior:__
Write values into bucket "bzi", 

__Actual behavior:__
Get following error:
```
(0)
Reason: SSLError
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
```

__Specifications:__
 - Client Version: python 3.8, influxdb-client 1.21.0
 - InfluxDB Version: 2.0 
 - Platform: (influxdb cloud, aws eu-central-1-1)

**Comment by bednar** [comment]
Hi @BerniZindel,

thanks for using our client.

It is probably caused by new Let's Encrypt root certificate. You have to install this certificate in your keychain.

For more info see - https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

You can try connection to InfluxDB Cloud by:

```python
import ssl
import urllib3

http = urllib3.PoolManager(cert_reqs=ssl.CERT_REQUIRED)
resp = http.request('GET', 'https://us-west-2-1.aws.cloud2.influxdata.com/ping')

print(resp.headers)
```

Regards

**Comment by BerniZindel** [comment]
hi @bednar thanks for your support. I checked my certificates and, if I understood right, the certificate ISRG Root X1 is installed. Your code returns me that error:
```
MaxRetryError: HTTPSConnectionPool(host='us-west-2-1.aws.cloud2.influxdata.com', port=443): Max retries exceeded with url: /ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
```

--> do you know, have I to remove the outdated DST Root CA X3?


best regards

**Comment by sh-git-repo** [comment]
@bednar thanks for all the help,  @BerniZindel I was able to figure it out, in the client just pass in certifi.where()
```
client = InfluxDBClient(
    url="https://eu-central-1-1.aws.cloud2.influxdata.com",
    org=config['org'],
    bucket=config['bucket'],
    token=config['token'],
    ssl_ca_cert=certifi.where()
)
```

**Comment by BerniZindel** [comment]
wow, big thanks @sh-git-repo works! 🚀

**Comment by bednar** [comment]
@sh-git-repo thanks for nice workaround
