### ISSUE TITLE
timeout when query massive data using query_raw

### ISSUE THREAD

**Issue by helldragonx** [influxdata/influxdb-client-python#349]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. when data is a little hudge , e.g. 100,000 points.
2. query as upper
3. .return timeout, but if minimize the data scope , return normal 

__Expected behavior:__
query_raw using streaming mode, so shall not timeout.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version:
 - InfluxDB Version:
    InfluxdB 2.0 
 - Platform:
   Windows.

**Comment by bednar** [comment]
> query_raw using streaming mode, so shall not timeout.

Even though it is a streaming API, the HTTP timeout is respected.
