### ISSUE TITLE
InfluxQL Supported in influxdb_client

### ISSUE THREAD

**Issue by helldragonx** [influxdata/influxdb-client-python#353]
__Proposal:__

Support InfluxQL Query feature:

__Current behavior:__

Very slow in query, e.g. the following logs show the slow query performance:
cost 3.38 seconds setup streams and 12.27 seconds to download (7555, 7)results 
cost 3.20 seconds setup streams and 7.88 seconds to download (4683, 7)results 
cost 0.23 seconds setup streams and 19.63 seconds to download (12517, 7)results

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
