### ISSUE TITLE
Error in creating buckets

### ISSUE THREAD

**Issue by malwinweiler** [influxdata/influxdb-client-python#354]
- **InfluxDB version:** 2.0.9
- **InfluxDB-python version:** 1.22.0
- **Python version:** 3.8.6
- **Operating system version:** Docker Container 1. FROM python:latest/3.8

Dear Influx Team,

I am having a very strange issue with the buckets API that I cannot solve:

On my local machine (Win 10, Docker for Windows) everything works fine. I can create buckets without problems and see the changes immediately reflected in the DB.

However, on my Ubuntu host running the same docker container I am running into serious problems:

> Error in creating bucket for influx1: list index out of range

```
def init_database(self, new_bucket, client):
    try:
        if self.bucket_api[client].find_bucket_by_name(new_bucket) != None:
            self.logger.debug(f'Bucket {new_bucket} already exists in InfluxDB, not changing anything')
        else:
            self.bucket_api[client].create_bucket(bucket_name=new_bucket)
            self.logger.info(f'Created Bucket {new_bucket} in InfluxDB')
        return new_bucket

    except Exception as err:
        self.logger.error('Error in creating bucket for {}: {}'.format(client, err))
        return None
```

> new_bucket == "logs"
> client == "influx1"
> self.bucket_api[client] == <influxdb_client.client.bucket_api.BucketsApi object at 0x7fac51d4de20>
> self.bucket_api = dictionary object

The Error does not really make sense to me as there is no list being used in this code snippet, it is all dictionaries. I know that the _create_bucket_ function causes the error but am unable to debug further into the code of the influxdb_client library.

Do you have any what causes this error?

Best regards and thanks in advance,
M. Weiler

Edit:
I just remember the traceback module, here is the output:

```
    self.bucket_api[client].create_bucket(bucket_name=new_bucket)
  File "/lib/python3.8/site-packages/influxdb_client/client/bucket_api.py", line 55, in create_bucket
    org_id=get_org_query_param(org=(org_id if org is None else org),
  File "/lib/python3.8/site-packages/influxdb_client/client/util/helpers.py", line 35, in get_org_query_param
    return client.organizations_api().find_organizations(org=_org)[0].id
IndexError: list index out of range
```

**Comment by bednar** [comment]
Hi @malwinweiler,

thanks for using our client.

How do you define the destination organization for bucket? If you don't specify the `org` parameter in `create_bucket`, then is used the `org` from initialization of client.

Is the `org` specified in client initialization valid? Is it name or id?

Regards

**Comment by malwinweiler** [comment]
Hi @bednar,

thanks for your feedback, it got me thinking again about the initialization.

The error was that the token I provided only had _bucket read and write_ access and was not an _all-access_ token. Changing the token solved the issue immediately.

It would be great if the error message could be amended to incorporate such issues :)

Best regards and thanks for your help,
M. Weiler
