### ISSUE TITLE
Name not property of TaskCreateRequest class

### ISSUE THREAD

**Issue by perzizzle** [influxdata/influxdb-client-python#355]
__Steps to reproduce:__
When creating a new task you don't know the id yet so you can't use the task object (https://github.com/influxdata/influxdb-client-python/blob/f851303692f25596bca7d495ae383d05bb4c050e/influxdb_client/domain/task.py#L153) but the TaskCreateRequest class doesn't have a name property (https://github.com/influxdata/influxdb-client-python/blob/f851303692f25596bca7d495ae383d05bb4c050e/influxdb_client/domain/task_create_request.py)

You can get around this by creating a Task object with id=0 and passing it to the create_task method. The response will contain the real task id.

__Expected behavior:__
I would expect TaskCreateRequest to have a name property so that you can set the name of the task you are creating.

**Comment by bednar** [comment]
Hi @perzizzle,

thanks for using our client.

Our API mimic the InfluxDB API and there is no specification for `name` in a [Create a new task](https://docs.influxdata.com/influxdb/cloud/api/#operation/PostTasks) request.

You have to specify the name of your task in task option. Something like:

```python
flux = '''option task = { 
        name: "my-task-name",
        every: 1h
    }
    from(bucket: "my-bucket") |> range(start: -2m) |> last()
    '''

request = TaskCreateRequest(org_id=self.organization.id, flux=flux, status="active",
                            description="Task Description")

task = self.tasks_api.create_task(task_create_request=request)
```

Regards

**Comment by perzizzle** [comment]
Thanks for the explanation, this makes some sense. It's confusing to me to pass description as a parameter but not name.
