### ISSUE TITLE
Delete a single measurement

### ISSUE THREAD

**Issue by tonioo** [influxdata/influxdb-client-python#36]
Hi,
I see it is possible to delete data from a specific bucket using this client but I'd like to know if it is possible to delete a single measurement?
Thank you.

**Comment by bednar** [comment]
Hi @tonioo 

You could specify a [predicate](https://github.com/influxdata/influxdb-client-python/blob/1e2fae1f6e36c8c0205b6ce112974edad56452bd/influxdb_client/client/delete_api.py#L12) as is described here: 

https://v2.docs.influxdata.com/v2.0/reference/syntax/delete-predicate/#delete-points-with-a-specific-measurement

and uses in the client:

```python
self.delete_api.delete(start, stop, '_measurement="sensorData"', bucket_id=bucket_id, org_id=organization_id)
```

Regards

**Comment by tonioo** [comment]
Thank you @bednar !
