### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by dineshrboson** [influxdata/influxdb-client-python#360]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version:
 - InfluxDB Version:
 - Platform:

**Comment by dineshrboson** [comment]
![Screenshot from 2021-11-10 18-01-07](https://user-images.githubusercontent.com/77951479/141114001-fc426f9c-c972-4659-8cd3-45b2b8e97389.png)

**Comment by dineshrboson** [comment]
I installed lets encrypt in my ubuntu machine

**Comment by dineshrboson** [comment]
I tied couple of ways to resolve the issue can you look into it once.

**Comment by dineshrboson** [comment]
tried with this syntax certifi.where()

**Comment by bednar** [comment]
Hi @dineshrboson,

thanks for using our client.

Try to init the client with: `certifi.where()`.

```python
client = InfluxDBClient(
    url="https://eu-central-1-1.aws.cloud2.influxdata.com",
    org=config['org'],
    bucket=config['bucket'],
    token=config['token'],
    ssl_ca_cert=certifi.where()
)
```

Do you have detail validation message why the validation fails? 

Regards

**Comment by dineshrboson** [comment]
Thanks working
