### ISSUE TITLE
Use influxdb-client as a python native logging handler that writes to InfluxDB.

### ISSUE THREAD

**Issue by strom-und-spiele** [influxdata/influxdb-client-python#364]
## :sparkles: Feature request 
I'd like to use the `influxdb-client` with the [python native logging](https://docs.python.org/3/library/logging.html) module.

## :previous_track_button: What happend so far
Four years ago there was an [attempt](https://github.com/Teamworksapp/influxdb_logging) to do this, however this project never really took off and seems to be incompatible with the latest version of influx (v2).

## :bulb: Idea and reasoning
The goal would be to have a class within `influxdb-client` that can be passed as a handler to `logging`. To me this seems reasonable as it centralizes logging, freeing the individual modules from "knowing" about influx and allowing to make decisions on how to use the log output depending on the context the module is used.
If I'm missing something, I'd really like to hear about it.

## :factory_worker: Work
I'd like to make this work for a project at my day job, so I have some resources to make this happen anyway. If you think it makes sense, I'll go the extra mile and integrate it directly into this repo.

**Comment by bednar** [comment]
Hi @strom-und-spiele,

thanks for using our client.

Every PR is welcome, so feel free to implement this feature and we will be happy to accept its.

Regards

**Comment by strom-und-spiele** [comment]
Hi @bednar,

happy to hear this. 

I'm not quite sure I understood the code structure right:
I guess I'd put the code inside of `/influxdb_client/client/loggingHandler.py` exposing a `InfluxLoggingHandler` through the `__init__.py` file in said folder. The place for tests and examples is obvious ;)

**Comment by bednar** [comment]
> I guess I'd put the code inside of `/influxdb_client/client/loggingHandler.py` exposing a `InfluxLoggingHandler` through the `__init__.py` file in said folder. The place for tests and examples is obvious ;)

Sounds good.

**Comment by ronytesler** [comment]
Do you know when this will be ready? Now the logger writes to the console, I want it to write to a file so I can use code to search for errors.

**Comment by strom-und-spiele** [comment]
Hey, 

sorry for bringing this up and not doing anything for so long. As always life and important customers came in the way.

Anyhow; I reserved some time next week to push a (working) first draft.

**Comment by bednar** [comment]
@strom-und-spiele 👍 awesome news, thanks
