### ISSUE TITLE
influxdb_client.version() returns empty string

### ISSUE THREAD

**Issue by mm0** [influxdata/influxdb-client-python#366]
https://github.com/influxdata/influxdb-client-python/blob/922477ff2499165ad2018106ad7cb5a72ddb59d9/influxdb_client/client/influxdb_client.py#L446

`version()` method returns empty str.  Should this be returning the value set in the header `X-Influxdb-Build` instead?  

This is a typical response for this method request:
![image](https://user-images.githubusercontent.com/4008256/142712951-b6586c57-f7d3-4928-89a3-02f8f5863c24.png)

**Comment by bednar** [comment]
Hi @mm0,

thanks for using our client.

In your example the `X-Influxdb-Version` header is empty, so this looks like a problem with InfluxDB Cloud. What is the `url` of your InfluxDB?

If I try the `version()` with `https://us-west-2-1.aws.cloud2.influxdata.com/` everything works correctly:

```python
from influxdb_client import InfluxDBClient

with InfluxDBClient(url="https://us-west-2-1.aws.cloud2.influxdata.com", token="my-token", org="my-org") as client:
    print(client.version())

```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
