### ISSUE TITLE
Pandas outputs warning when calling dataframe.append in flux_csv_parser._prepare_data_frame

### ISSUE THREAD

**Issue by mm0** [influxdata/influxdb-client-python#367]
https://github.com/influxdata/influxdb-client-python/blob/922477ff2499165ad2018106ad7cb5a72ddb59d9/influxdb_client/client/flux_csv_parser.py#L190

This method should return :
```
return self._data_frame.append(_temp_df, sort=True)
```

Pandas outputs warning when calling `dataframe.append` in `flux_csv_parser._prepare_data_frame()`.

The output is:
```
pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.
```

Description of the issue can be found here: 
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.23.0.html#concatenation-will-no-longer-sort

**Comment by bednar** [comment]
Hi @mm0,

thanks for using our client.

We don't need to set the `sort` to `True` because the columns of `_data_frame` and `_temp_df ` are aligned. Your pandas version is `v0.23.0` which is very old, if you update to latest version the warning disapper.

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
