### ISSUE TITLE
query_api.query_data_frame returns list[DataFrame] instead of DataFrame with same flux query on different bucket

### ISSUE THREAD

**Issue by nlnjnj** [influxdata/influxdb-client-python#368]
query_api.query_data_frame returns list[DataFrame] instead of DataFrame with same flux query on different bucket

__Steps to reproduce:__
```flux query
        from(bucket: "*****")
          |> range(start: 2021-06-01T00:00:00+00:00
                  , stop: 2021-06-30T23:59:59+00:00)
          |> filter(fn: (r) => r["_measurement"] == "************"
                           and r["******_id"] == "1006"
                           and r["******"] == "******"
                           and r["******_id"] == "5"
                           and r["******_id"] == "12020001"
                           and r["_field"] == "******"
            )
          |> group(columns: ["inst******", "ins******", "sc******", "_value"])
          |> count(column: "user_id")
          |> rename(columns: {user_id: "count"})
          |> map(fn: (r) => ({
              r with
              inst******: if exists r["inst******"] then r["ins******"] else " - ",
              ins******: if exists r["ins******"] then r["ins******"]
                                   else " - "
            }))
          |> pivot(rowKey:["inst******", "ins******", "sca******"], columnKey: ["_value"], valueColumn: "count")
```

__Expected behavior:__
returns DataFrame

__Actual behavior:__
returns list[DataFrame]
![ar](https://user-images.githubusercontent.com/5831940/143165977-cfb685ae-8a95-441d-92fc-72a70ab0aec0.png)

__Specifications:__
 - Client Version: 1.18.0
 - InfluxDB Version: bitnami/influxdb:2.0.9-debian-10-r25 (helm deployed using bitnami's chart)
 - Platform: Python 3.9.2 on Windows 10

**Comment by bednar** [comment]
Hi @nlnjnj,

thanks for using our client.

The `DataFrame` is bound to Flux table and your Flux Query returns more than one table. Try to change your Flux query to returns only one table.

You can also concat `DataFrames` into one by `concat` function, for more info see - https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#concatenating-objects

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Comment by Francesko90** [comment]
Hello! I have the same problem, what do you mean with flux table? for example I have this measurements 

                                                                                     
```
> SHOW MEASUREMENTS
name: measurements
name
----
app1
app1_temp
app2_auxiliary
app2_tec_map
app3
app4a
app4b
products
```

and the following query return three data frame
```
start="2020-01-16T00:00:00Z"
stop="2020-01-17T00:00:00Z"

data_frame = client.query_api().query_data_frame('from(bucket:"xxxx") '
                                        '|> range(start: '+start+', stop: '+stop+') '
                                        '|> filter(fn:(r) => r._measurement == "app3") '
                                        '|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") ' )
```

**Comment by bednar** [comment]
@Francesko90, thanks for using our client

> Hello! I have the same problem, what do you mean with flux table? for example I have this measurements
> 

The InfluxDB returns response as a stream of tables. This tables are mapped to the DataFrames. For more info see:

- https://docs.influxdata.com/flux/v0.x/get-started/data-model/#stream-of-tables

**Comment by Francesko90** [comment]
Thank you bednar for the link to documentation! Now I understand!
