### ISSUE TITLE
Latency writing on influxdb cluster

### ISSUE THREAD

**Issue by tdimitch** [influxdata/influxdb-client-python#369]
Hi, I have a kubernetes cluster with and influxdb instance for some metrics with
          image: influxdb:2.1
          resources: 
            limits:
              cpu: '1'
              memory: 700Mi
            requests:
              cpu: 700m
              memory: 500Mi

I have about 20 python script writing data to influx continuously, with configuration
client.write_api(write_options=ASYNCHRONOUS)
We have also tried SYNCHRONOUS, but not BATCHING just yet.

Each script but one writes about 3 - 5 times a second, with no problem. One script, though, writes at least 10 - 15 times a second. This script has an influxdb_client and overtime it drifts from original time... In two days, the latency is 90 minutes!!!
I have checked that the times at which the data is created and ready to ship are ok, the resources on influxdb (viewed with prometheus) are within range, but the visualization in grafana shows that the timestamps in those records are off.

Here a glimpse at data:

[prices.pdf](https://github.com/influxdata/influxdb-client-python/files/7601777/prices.pdf)

The grey line shows the actual data (price of a given market), while the yellow one is the price written with the aforementioned script.

The following table shows time difference between same data:

[prices2.pdf](https://github.com/influxdata/influxdb-client-python/files/7601815/prices2.pdf)

Take into account that: _time is the time at which the data was written in UTC, realPrice is the actual value and update_time is the time at which the data was produced in UTC-1. Thus, the time difference between the data being produced and the data being written in influx has a delay of about 1,5h.

__Expected behavior:__
As the rest of the scripts, to write data without delay.

Thanks in advance for the magnificent software and for taking the time of reading.

__Actual behavior:__
Accumulating delay writing records to influxdb.

__Specifications:__
 - Client Version: 1.20.0
 - InfluxDB Version: 2.1
 - Platform: Kubernetes

**Comment by bednar** [comment]
Hi @tdimitch,

thanks for using our client.

Can you share little bit more about your problem?

Regards

**Comment by tdimitch** [comment]
Yesterday I created a script that wrote 10**6 records with a delay in between of .1s, the results are not bad. Towards the end there is about half a second of delay (columns _time and _update_time, again, with 1h difference).
[test.pdf](https://github.com/influxdata/influxdb-client-python/files/7607160/test.pdf)

In any case, yesterday we provided more resources to influx
          resources: 
            limits:
              cpu: '2'
              memory: 1500Mi
            requests:
              cpu: '1'
              memory: 1000Mi
And the problem does seem to be solved, although it is quite strange since Prometheus reported that influxdb had enough with previous resources (sorry I can not share the image, since the metrics where deleted when updating the deployment).

**Comment by bednar** [comment]
There is a document for hardware sizing for InfluxDB - https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/#influxdb-oss-guidelines. The hardware recommendations for InfluxDB 2.0 should be the same, since 2.0 OSS uses the same data storage engine as 1.8.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
