### ISSUE TITLE
Bind parameters inside strings for more complex query

### ISSUE THREAD

**Issue by greenenvy** [influxdata/influxdb-client-python#372]
__Steps to reproduce:__

In a bit more complex query, like for in the example where you join a table that is a result from a sql query, when the same is parametrized, there seems to not be any way to bind parameters inside quotes. 

    params = {
          '_POSTGRES_DB': get_variable('POSTGRES_DB', 'example'),
          '_POSTGRES_USER': get_variable('POSTGRES_USER', 'example'),
          '_POSTGRES_PASSWORD': get_variable('POSTGRES_PASSWORD', 'example'),
          '_POSTGRES_HOST': get_variable('POSTGRES_HOST', 'pg_example'),
          '_lat_min': 40,
          '_lat_max': 50,
          '_lng_min': 10,
          '_lng_max': 20,
          '_INFLUX_DB_BUCKET': get_variable('INFLUXDB_BUCKET', 'example')
      }
    query_api = influxdb_client.query_api()
    tables = query_api.query('''
        import "sql"

        example = sql.from(
          driverName: "postgres",
          dataSourceName: "postgresql://$_POSTGRES_USER:_POSTGRES_PASSWORD@_POSTGRES_HOST?sslmode=disable",
          query:"SELECT example.source_address src_addr, ST_Y(example.geo_location) latitude, ST_X(example.geo_location) longitude
                 FROM example_table example
                 WHERE example.geo_location && ST_MakeEnvelope(
                     _lng_min, _lat_min,
                     _lng_max, _lat_max
                 )"
        )
        
       example_metrics = from(bucket: _INFLUX_DB_BUCKET)
          |> range(start: -1h)
          |> last() 
          |> filter(fn: (r) => r._measurement == "example" and (r._field == "bri"))
          |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
          
        join(tables: {example: example, example_metrics: example_metrics}, on: ["src_addr"])
          |> map(fn: (r) => ({src_addr: r.src_addr, bri: r.bri}))
    ''', params=params)

__Expected behavior:__
There should be a way to bind _POSTGRES_USER, _POSTGRES_PASSWORD, _POSTGRES_HOST, _lat_min, _lat_max, _lng_min, _lng_max that are inside quotes

__Actual behavior:__
The response that is being returned: An internal error has occurred

__Specifications:__
 - Client Version: 1.24.0
 - InfluxDB Version: 2.0.9
 - Platform: macOS Big Sur 11.5.2
 - Python: 3.9.7

**Comment by bednar** [comment]
Hi @greenenvy,

thanks for using our client.

Can you share the full error response? 

It looks like problem at server side. Is there something interest in the InfluxDB's logs? ... something like: `ts=2021-12-02T07:05:07.776796Z lvl=warn msg="internal error not returned to client" log_id=0YAV6zTW000 handler=error_logger error="dial tcp: lookup _POSTGRES_HOST on 127.0.0.11:53: no such hos`

Regards

**Comment by greenenvy** [comment]
Hi,

Unfortunately, i can't see any of these kinds of logs in the docker container where InfluxDB is running. Probably there is some misconfiguration from my side about the query logs.

When i replace _POSTGRES_USER, _POSTGRES_PASSWORD, _POSTGRES_HOST, _lat_min, _lat_max, _lng_min, _lng_max from the query with hardcoded values, the query works totally fine. The only parameter that can be in place is _INFLUX_DB_BUCKET. I assume the placehoders are not replaced with the params values because they are used inside quotes "...._POSTGRES_USER...."

**Comment by bednar** [comment]
> I assume the placehoders are not replaced with the params values because they are used inside quotes "...._POSTGRES_USER...."

You can concats arguments by `+`. Try something like:
```
dataSourceName: "postgresql://" + _POSTGRES_USER + ":" + _POSTGRES_PASSWORD + "@" + _POSTGRES_HOST + "?sslmode=disable"
```

**Comment by greenenvy** [comment]
Works. Thank you very much.

Did not know you can do that in the query itself. 

I assume this is safe from any kind of sql injection?

**Comment by bednar** [comment]
> I assume this is safe from any kind of sql injection?

I will prefer to pass `dataSourceName` as a parameter to avoid concats in query.

**Comment by greenenvy** [comment]
I got all the answers i wanted so we can close the issue. Thank you very much.
