### ISSUE TITLE
Add group data to FluxTable

### ISSUE THREAD

**Issue by BernatGalmes** [influxdata/influxdb-client-python#373]
__Proposal:__
It should be useful to add a function to query the common values for all table records when grouping.

__Current behavior and Desired behavior:__
The next code illustrate with an example the feature requested grouping by time. When we are querying multiple fields grouped by time we can't get the time of each group without iterating the records. It should be very useful to get that information from the FluxTable object.

```{python}
query = f"""from(bucket: "{bucket}")
          |> range(start: {start_datetime.isoformat()}Z, stop: {end_datetime.isoformat()}Z)
          |> filter(fn: (r) => r["_measurement"] == "sensor" and r["_field"] != "color" and r["sensorID"] == "84")
          |> group(columns: ["_time"])
        """
tables = client.query_api().query(query, org=org)
print(tables)
for table in tables:
    # Here you should can get the time value common for all table records. Now it's impossible
    for record in table.records:
        ... # Currently you only can get the time inside this loop accessing record attributes
```
The same problem appears grouping for any other field or tag.

__Use case:__
This feature will be very useful when processing the queried data. It will allow to process the records according to the group data

**Comment by bednar** [comment]
Hi @BernatGalmes,

thanks for using our client and your proposal.

The `FluxTable` object is directly map to [Annotated CSV's table](https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/#tables), so there is no information about the used grouping. 

How would the implementation of this feature look like? Is this something you might be willing to help with?

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
