### ISSUE TITLE
Parameter `location` for the `aggregateWindow` function

### ISSUE THREAD

**Issue by Yaronn44** [influxdata/influxdb-client-python#376]
I'm trying to use the new `location` attribute for the `aggregateWindow` function.
https://docs.influxdata.com/flux/v0.x/stdlib/universe/aggregatewindow/

I tried to give the parameter like this : 
`aggregateWindow(every: 1m, fn: mean, location: "UTC")` 

But the following error occured : 
`{"code":"invalid","message":"error @1:324-1:396: expected {zone:string, offset:duration} but found string (argument location)"}`

So I tried like this (from [this doc](https://docs.influxdata.com/flux/v0.x/stdlib/timezone/#constants)) :
`aggregateWindow(every: 1m, fn: mean,location: {zone: "UTC", offset: 0h})`  and even like this
`aggregateWindow(every: 1m, fn: mean,location: {"zone": "UTC", "offset": 0h})` 

but a `KeyError: 'zone'` occured in both cases.

Is it failing because it's not yet implemented in the library or because I use it with the wrong syntax ?
As it's a new parameter it's not yet documented in this library but the first error suggested that the parameter is available so I'm a bit confused here.

__Specifications:__
 - Client Version: 1.24.0
 - Platform: Windows

**Comment by bednar** [comment]
Hi @Yaronn44,

thanks for using our client.

It looks like problem with the InfluxDB, try to use [timezone.location() function](https://docs.influxdata.com/flux/v0.x/stdlib/timezone/location/). Something like following code will works:

```python
from datetime import datetime

from influxdb_client import WritePrecision, InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
    point = Point("my-measurement") \
        .tag("location", "Prague") \
        .field("temperature", 25.3) \
        .time(datetime.utcnow(), WritePrecision.MS)

    write_api = client.write_api(write_options=SYNCHRONOUS)
    write_api.write(bucket="my-bucket", record=point)

    query_api = client.query_api()

    query = 'import "timezone"' \
            '' \
            'from(bucket: "my-bucket") ' \
            '|> range(start: 0) ' \
            '|> filter(fn: (r) => r["_measurement"] == "my-measurement") ' \
            '|> aggregateWindow(every: 10s, fn: mean, createEmpty: false, location: timezone.location(name: "UTC"))'

    for table in query_api.query(query):
        print(table)
        for record in table.records:
            print(record.values)

```

Regards

**Comment by Yaronn44** [comment]
Thank you a lot ! I just  didn't figured out that the `import "timezone"` should be done directly in the query !
