### ISSUE TITLE
Regression: invalid field format with NaN values

### ISSUE THREAD

**Issue by maxcarrel** [influxdata/influxdb-client-python#377]
I noticed a regression in the way NaN values are handled when working with pandas dataframes. Could it be a result of [500835](https://github.com/influxdata/influxdb-client-python/commit/500835f3b1d3b2b87214ede830b750a6018c0ca9#diff-02179d31a524332a9b64b57d464f6a56c0725daf636a4a410a20ed2aa71a43e0)? The bug is not observed on 1.23.0.

__Steps to reproduce:__

```
import pandas as pd
import numpy as np
from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS

client = InfluxDBClient(url="http://localhost:8086", token="...", org="...")

write_api = client.write_api(write_options=SYNCHRONOUS)

df = pd.DataFrame({
    'a': np.arange(0.,3.),
    'b': [0., np.nan, 1.],
}).set_index(pd.to_datetime(['2021-01-01 0:00','2021-01-01 0:01','2021-01-01 0:02']))

write_api.write(
    bucket='test',
    record=df,
    data_frame_measurement_name='test',
)
```

__Expected behavior:__

Data points successfully written to database.

__Actual behavior:__

Exception is raised:

```
ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Platform-Error-Code': 'invalid', 'Date': 'Mon, 06 Dec 2021 17:00:47 GMT', 'Content-Length': '128'})
HTTP response body: {"code":"invalid","message":"unable to parse 'test a=1.0,_EMPTY_LINE_PROTOCOL_PART_ 1609459260000000000': invalid field format"}
```

__Specifications:__
 - Client Version: 1.24.0
 - InfluxDB Version: 2.0.7
 - Platform: linux/windows

**Comment by bednar** [comment]
Hi @maxcarrel,

I have prepared a fixed version within #378. If you would like to use this fixed version before regular release, please install client via:

```
pip install git+https://github.com/influxdata/influxdb-client-python.git@fix/serialization
```

Regards

**Comment by maxcarrel** [comment]
Hi @bednar,

Thank you for your reactivity. That's great, I'll wait for the next release then.

Best regards

**Comment by bednar** [comment]
@maxcarrel, Thank you for your detailed description and I apologize for any problems caused by this regression.
