### ISSUE TITLE
query_data_frame returns object data type for all columns

### ISSUE THREAD

**Issue by buraketmen** [influxdata/influxdb-client-python#379]
__Steps to reproduce:__

1. Transferring data types (numeric, object etc.) to dataframe

__Expected behavior:__

Returning the data types of the data pulled from the database with __query_api__ as it should be. 

__Actual behavior:__

When I use the following query with the __query_data_frame__ module in the __query_api__, all columns except _time are returned as objects; even though the data stored in the database is not string.

```console
query_api = influxdb_client.query_api()
bucket, measurement, start, stop ="test", "test", "0", "now()"

query = 'import \"influxdata/influxdb/schema\"' \
  f' from(bucket:\"{bucket}\")' \
  f' |> range(start: {start}, stop: {stop})' \
  f' |> filter(fn: (r) => r._measurement == \"{measurement}\")' \
  f' |> drop(columns: ["_start", "_stop","_measurement"])' \
  f' |> schema.fieldsAsCols()'

result = query_api.query_data_frame(query=query)
print(result.dtypes)

_time           datetime64[ns, UTC]
attribute_1                  object
attribute_2                  object
attribute_3                  object

```

When I transform the data with the code below, I can see that the data is numeric, not object. The data which is saved in the database is as follows:
```console
result = json.loads(result.to_json(orient='records'))
print(result)

[{
  "_time": 1638959688782,
  "attribute_1": 1,
  "attribute_2": 2,
  "attribute_3": "test_message",
}]
```

__Specifications:__
 - Client Version: 1.23.0
 - InfluxDB Version: 2.2.1
 - Platform: Windows 10 & Python3.8.11 (running on Docker)

**Comment by bednar** [comment]
Hi @buraketmen,

thanks for using our client.

I have prepared a fixed version within #380. If you would like to use this fixed version before regular release, please install client via:

```
pip install git+https://github.com/influxdata/influxdb-client-python.git@fix/pandas-data-types
```

Regards
