### ISSUE TITLE
query data with specified precision

### ISSUE THREAD

**Issue by ebrahimkarimi** [influxdata/influxdb-client-python#387]
1. write data to the database with nanosecond precision (OK)
2. query data with default nanosecond precision (OK)
3. try to add parameter epoch set to `s` to get data with `unix_s` precision based on [docs](https://docs.influxdata.com/influxdb/v1.3/guides/querying_data/#timestamp-format)
so my code:
```
    ...
    result = query_api_price.query_data_frame(query, params={'epoch': 's'})
```

Expected behavior:
expected to get all rows time column with `unix_seconds` but it has no effect!

Actual behavior:
all the rows time is unix_ms time

Specifications:
 - Client Version: 1.24.0
 - InfluxDB Version: 2.1
 - Platform: Influxdb docker container

UPDATE
to get the job done i had to use map in my query to calculate each row's time like this:
`|>map(fn: (r)=> ({ r with time: int(v:  r.time)/1000000000}))`

**Comment by bednar** [comment]
Hi @ebrahimkarimi,

thanks for using our client.

The Query API for InfluxDB v2 doesn't supports the `epoch` parameter -  https://docs.influxdata.com/influxdb/v2.1/query-data/flux/.

> UPDATE to get the job done i had to use map in my query to calculate each row's time like this: `|>map(fn: (r)=> ({ r with time: int(v: r.time)/1000000000}))`

This is the valid solution 👍.

Regards
