### ISSUE TITLE
New Connection Error

### ISSUE THREAD

**Issue by amirft1374** [influxdata/influxdb-client-python#390]
Hi.
I am getting the following error when I run the first couple of codes you mentioned.
The error is related to the last line of the code : 
`NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000016FED750940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it`

 And the code is :

```
from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

bucket = "my-bucket"

client = InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org")

write_api = client.write_api(write_options=SYNCHRONOUS)
query_api = client.query_api()

p = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3)

write_api.write(bucket=bucket, record=p)
```

I would appreciate your suggestions.

**Comment by bednar** [comment]
Hi @amirft1374,

thanks for using our client.

It looks like that there isn’t the InfluxDB listening on the specified port, or there is a firewall stopping you.

Can you double check that InfluxDB is running?

Regards

**Comment by amirft1374** [comment]
Thank you Bednar for answering my issue. 
I am not sure exactly what version and how I should run the InfluxDB. Could you help me with that?
Thanks,
Amir

**Comment by bednar** [comment]
@amirft1374 

You can use OSS version of InfluxDB - https://docs.influxdata.com/influxdb/v2.1/install/, or Cloud version - https://docs.influxdata.com/influxdb/cloud/sign-up/

Regards
