### ISSUE TITLE
Add stacks and template APIs.

### ISSUE THREAD

**Issue by DriesSchaumont** [influxdata/influxdb-client-python#396]
__Proposal:__
First of all, thanks for creating this library!
I am looking for a way to manage stacks and templates. However, they seem to be missing from this library.
They seem to be available in the OSS api specification, though: https://github.com/influxdata/openapi/blob/master/contracts/oss.yml
Would it be possible to add these APIs to this library?

__Current behavior:__
Stacks and template specifications are currently not being generated in this library.

__Desired behavior:__
I would like to 

__Alternatives considered:__
The workaround atm is to directly call the API directly.

__Use case:__
I want to create an manage templates and stacks using python.

**Comment by bednar** [comment]
Hi @DriesSchaumont,

thanks for using our client.

> Would it be possible to add these APIs to this library?

Yes, we can add these APIs into library.

Can you describe your use case little bit more? It will be helpful to us to be sure that we covers your requirements.

Regards

**Comment by DriesSchaumont** [comment]
Sure! I am creating a webserver application for reading serial data for a specific sensor. The data is parsed and verified (checksum), before being written to influxdb. I would like to minimize the impact of potentials bugs on the database by using a template for the ingested data. Also, I would like to be able check that such a template exists on application startup, and update/create it if necessary.

**Comment by bednar** [comment]
@DriesSchaumont thanks for detail info. One more question... What will be a source of the template? Is it community template or do you want to use yours own template?

**Comment by bednar** [comment]
I've prepared PR #399 with possibility to use `Stacks` and `Templates` API. If you would like to use dev version of client then install client via:

```console
pip install git+https://github.com/influxdata/influxdb-client-python.git@open_api_update
```

Here is an example for `Stacks` and `Templates` API: https://github.com/influxdata/influxdb-client-python/blob/open_api_update/examples/templates_management.py

Regards

**Comment by DriesSchaumont** [comment]
Thank you, greatly appreciated!
