### ISSUE TITLE
Unable to get data frame using query api

### ISSUE THREAD

**Issue by Pragatibs** [influxdata/influxdb-client-python#398]

**Comment by Pragatibs** [comment]
I am trying to use simple syntax of reading data using fluxql query in query api and get a data frame. The query doesn't seem to get accepted since the AttributeError: 'NoneType' object has no attribute 'data' is thrown while printing data frame.

**Comment by bednar** [comment]
Hi @Pragatibs,

thanks for using our client.

> AttributeError: 'NoneType' object has no attribute 'data'

Can you share your Python script and full stack trace?

Here is an example how to query data into DataFrame: https://github.com/influxdata/influxdb-client-python/blob/138024204994ff36456b9e15c54b4046a45f0934/examples/query.py#L109

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
