### ISSUE TITLE
Cannot create new bucket

### ISSUE THREAD

**Issue by jimazikerlan** [influxdata/influxdb-client-python#401]
I am trying to create a new bucket with the API but it throws **ValueError: Invalid value for `org_id`, must not be `None`** error if I do not insert the "org_id" param. 

Code: 
```python
from influxdb_client import InfluxDBClient, BucketRetentionRules
url = "http://localhost:8086"
token = "my-token"
org = "my-org"

with InfluxDBClient(url=url, token=token) as client:
    buckets_api = client.buckets_api()

    """
    Create Bucket with retention policy set to 3600 seconds and name "bucket-by-python"
    """
    print(f"------- Create -------\n")
    retention_rules = BucketRetentionRules(type="expire", every_seconds=3600)
    created_bucket = buckets_api.create_bucket(bucket_name="bucket-by-python",
                                               retention_rules=retention_rules,
                                               org=org)
```
Even if I put the org_id param it continues throeing the same error. 

influx_db_client version: '1.25.0'
influx_db version:1.8.10

**Comment by bednar** [comment]
Hi @jimazikerlan,

thanks for using our client.

Does your InfluxDB have an organization named 'my-org'? Try to something like following script to list all orgs and create bucket for first of them:

```python
from influxdb_client import InfluxDBClient, BucketRetentionRules
url = "http://localhost:8086"
token = "my-token"

with InfluxDBClient(url=url, token=token) as client:

    """
    Find All organizations
    """
    organizations = client.organizations_api().find_organizations()
    print(f"\n------- Organizations -------\n")
    print("\n".join([f" ---\n ID: {org.id}\n Name: {org.name}\n"
                     for org in organizations]))
    print("---")

    buckets_api = client.buckets_api()

    """
    Use first organization to create a Bucket
    """
    org = organizations[0]
    
    """
    Create Bucket with retention policy set to 3600 seconds and name "bucket-by-python"
    """
    print(f"------- Create -------\n")
    retention_rules = BucketRetentionRules(type="expire", every_seconds=3600)
    created_bucket = buckets_api.create_bucket(bucket_name="new-bucket",
                                               retention_rules=retention_rules,
                                               org=org)
    print(created_bucket)

```

Regards

**Comment by jimazikerlan** [comment]
Hello @bednar,
Thank you for your response. As it shows in the documentation of influxdb: **org: In InfluxDB 1.x, there is no concept of organization. The org parameter is ignored and can be left empty**

When I execute the **_client.organizations_api().find_organizations()** code it appears the following error: 
_ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Tue, 01 Feb 2022 09:34:17 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found_

**Comment by bednar** [comment]
@jimazikerlan You cannot create the bucket in InfluxDB 1.x. You have to use old one client to create database - https://github.com/influxdata/influxdb-python

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
