### ISSUE TITLE
create_bucket trigger IndexError: list index out of range

### ISSUE THREAD

**Issue by Bugazelle** [influxdata/influxdb-client-python#403]
__Steps to reproduce:__
run any of the following code, the error triggered
```client.buckets_api().create_bucket(bucket_name='my-bycket')```
```client.buckets_api().create_bucket(bucket_name='my-bycket', org='my-org')```

only working if:
```client.buckets_api().create_bucket(bucket_name='my-bycket', org='the org id here')```
```client.buckets_api().create_bucket(bucket_name='my-bycket', org_id='the org id here')```

But, seems there is no way from this python client to get the org id

__Actual behavior:__
The error triggered as bellow
```
Traceback (most recent call last):
  File "/Users/mr.banana/Bugazelle/export-csv-to-influx/src/ExportCsvToInflux/influx_object.py", line 161, in <module>
    influxdb.create_influx_db_if_not_exists(bucket='ken')
  File "/Users/mr.banana/Bugazelle/export-csv-to-influx/src/ExportCsvToInflux/influx_object.py", line 119, in create_influx_db_if_not_exists
    client.buckets_api().create_bucket(bucket_name=bucket)
  File "/Users/mr.banana/PythonVM3/lib/python3.8/site-packages/influxdb_client-1.25.0-py3.8.egg/influxdb_client/client/bucket_api.py", line 55, in create_bucket
    org_id=get_org_query_param(org=(org_id if org is None else org),
  File "/Users/mr.banana/PythonVM3/lib/python3.8/site-packages/influxdb_client-1.25.0-py3.8.egg/influxdb_client/client/util/helpers.py", line 35, in get_org_query_param
    return client.organizations_api().find_organizations(org=_org)[0].id
IndexError: list index out of range
```

__Specifications:__
 - Client Version: 1.25.0
 - InfluxDB Version: 2.1.1
 - Platform: MacOS

**Comment by bednar** [comment]
Hi @Bugazelle,

thanks for using our client.



> `client.buckets_api().create_bucket(bucket_name='my-bycket')` `client.buckets_api().create_bucket(bucket_name='my-bycket', org='my-org')`
> ```
> Traceback (most recent call last):
>   File "/Users/mr.banana/Bugazelle/export-csv-to-influx/src/ExportCsvToInflux/influx_object.py", line 161, in <module>
>     influxdb.create_influx_db_if_not_exists(bucket='ken')
>   File "/Users/mr.banana/Bugazelle/export-csv-to-influx/src/ExportCsvToInflux/influx_object.py", line 119, in create_influx_db_if_not_exists
>     client.buckets_api().create_bucket(bucket_name=bucket)
>   File "/Users/mr.banana/PythonVM3/lib/python3.8/site-packages/influxdb_client-1.25.0-py3.8.egg/influxdb_client/client/bucket_api.py", line 55, in create_bucket
>     org_id=get_org_query_param(org=(org_id if org is None else org),
>   File "/Users/mr.banana/PythonVM3/lib/python3.8/site-packages/influxdb_client-1.25.0-py3.8.egg/influxdb_client/client/util/helpers.py", line 35, in get_org_query_param
>     return client.organizations_api().find_organizations(org=_org)[0].id
> IndexError: list index out of range
> ```

It looks like that your organization name isn't correct. 

Can you check presents the organization by:
```python
orgs = client.organizations_api().find_organizations(org='my-org')
print(orgs)
```
?

Regards

**Comment by Bugazelle** [comment]
Hi @bednar ,

thank you for the suppport

I have find the root cause: because of my token is the read & write token for all bucket. 
If I used admin token, everything works fine

when using the non-admin token, I got the following result:
```
orgs = client.organizations_api().find_organizations(org='my-org')
print(orgs)
# []
```
