### ISSUE TITLE
deprecated calls in flux_csv_parser.py

### ISSUE THREAD

**Issue by jimwhitfield** [influxdata/influxdb-client-python#406]
I am using "the latest" "influxdb_client" and "the latest" "pandas" (and python 3.8)
$  python3 -m pip show pandas
Name: pandas
Version: 1.4.1

When running code, I get a warning message in my output:
/home/jupyter/.voila_env/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py:
190: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
line 190: return self._data_frame.astype(_temp_df.dtypes).append(_temp_df)

Mitigation attempt: I changed influxdb_client/client/flux_csv_parser.py line 190
        # Append data
        return self._data_frame.astype(_temp_df.dtypes).concat(_temp_df)
Alas, this did not solve the problem.  Instead,  I had this execution error:
AttributeError: 'DataFrame' object has no attribute 'concat'

I'd welcome any advice or update.  I'll probably spend some time on this before I pull pandas back down to an earlier release.
Thanks

**Comment by bednar** [comment]
Hi @jimwhitfield,

thanks for using our client. 

As a workaround you can use the Pandas `1.3.5`:

```
pip install pandas==1.3.5
```

Regards

**Comment by zengbiao** [comment]
i found the same issue with pandas==1.4.1, correct it: 
        self._data_frame=pd.concat([self._data_frame, _temp_df]) #zb
        return self._data_frame

**Comment by jimwhitfield** [comment]
Thanks for that quick turnaround.  I'm happily using that change @bednar posted.
