### ISSUE TITLE
query_api.query_data_frame results in AttributeError: type object 'object' has no attribute 'dtype'

### ISSUE THREAD

**Issue by JaegerStephan** [influxdata/influxdb-client-python#416]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install the latest influxdb_client (1.26.0)
2. Try to run the example from the docs in the section [Pandas DataFrame](https://influxdb-client.readthedocs.io/en/stable/usage.html#id1) to read data to pandas dataframe

```python
from influxdb_client import InfluxDBClient, Point, Dialect
from influxdb_client.client.write_api import SYNCHRONOUS

client = InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org")

write_api = client.write_api(write_options=SYNCHRONOUS)
query_api = client.query_api()

"""
Prepare data
"""

_point1 = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3)
_point2 = Point("my_measurement").tag("location", "New York").field("temperature", 24.3)

write_api.write(bucket="my-bucket", record=[_point1, _point2])

"""
Query: using Pandas DataFrame
"""
data_frame = query_api.query_data_frame('from(bucket:"my-bucket") '
                                        '|> range(start: -10m) '
                                        '|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") '
                                        '|> keep(columns: ["location", "temperature"])')
print(data_frame.to_string())

"""
Close client
"""
client.close()
```

__Expected behavior:__
The example would work fine and print queried data

__Actual behavior:__
AttributeError: type object 'object' has no attribute 'dtype'
<pre>
Traceback (most recent call last):
  File ".\write_query_influxdb.py", line 25, in <module>
    data_frame = query_api.query_data_frame('from(bucket:"evospbv1") '
  File "C:\KBApps\Python38\lib\site-packages\influxdb_client\client\query_api.py", line 150, in query_data_frame
    _dataFrames = list(_generator)
  File "C:\KBApps\Python38\lib\site-packages\influxdb_client\client\flux_csv_parser.py", line 71, in generator
    yield from parser._parse_flux_response()
  File "C:\KBApps\Python38\lib\site-packages\influxdb_client\client\flux_csv_parser.py", line 137, in _parse_flux_response
    self._data_frame = pd.DataFrame(data=[], columns=labels, index=None)
  File "C:\KBApps\Python38\lib\site-packages\pandas\core\frame.py", line 490, in __init__
    mgr = init_dict({}, index, columns, dtype=dtype)
  File "C:\KBApps\Python38\lib\site-packages\pandas\core\internals\construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "C:\KBApps\Python38\lib\site-packages\pandas\core\dtypes\cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
</pre>

__Specifications:__
 - Client Version: 1.26.0
 - InfluxDB Version: 2.1.1
 - Platform: 
   - Client: Windows 10
   - Server: Docker 20.10.12 on Linux Ubuntu 20.04LTS

**Comment by bednar** [comment]
Hi @JaegerStephan,

thanks for using our client.

It looks like problem caused by version of `pandas` and `numpy` - https://github.com/pandas-dev/pandas/issues/39520. Can you try update the `pandas` and `numpy` package?

```console
pip install pandas --upgrade
pip install numpy --upgrade
```

Regards

**Comment by JaegerStephan** [comment]
OK, thank you very much for the very fast response. :-) 
That solved the issue.
I wondered because I've installed both packages one (or few) days ago.
Nevertheless, now the `print(data_frame.to_string())` does not work anymore. One have to remove the `.to_string()` to get some output
