### ISSUE TITLE
use multiprocessing to write pandas.dataframe into influxdb

### ISSUE THREAD

**Issue by grant-zhang666** [influxdata/influxdb-client-python#417]
I met a problem when I try to use multiprocessing to write pandas.dataframe into influxdb.
The first thing is that, I use multiprocessing and in every subprocess I create a write_client and use it write many dataframes into influxdb, but when all the dataframes have been writeen into influxdb, I try to close the write_client use `write_client.close()`, the subprocess wii be stuck here for  a very long time, and i need to shutdown it manually. 

Then I write some code to kill the subprocess when all dataframes have been writeen, which leads to losses of some datarames when I query the measurement list of bucket.

So I want to know what happened here, could you give any advice, could python client support this kind of operation?

Any advice will be appreciated.

the main procedure of subprocesses can refrence here:
```python
    while True:
        if not q.qsize():
            # write_client.close()
            # client.close()
            os.kill(os.getpid(), signal.SIGKILL)
            return
        idx, f = q.get()
        mdf = MDF(f)
        filename = os.path.split(f)[1][:-4]
        # print("{}: {}".format(idx, filename))
        logger.critical("{}: {}".format(idx, filename))

        tic = time.time()
        count = 0
        for item in mdf.iter_groups():
            if len(item):
                if 'CAN_DataFrame.CAN_DataFrame.ID' in item.columns:
                    item['CAN_DataFrame.CAN_DataFrame.ID'] = item['CAN_DataFrame.CAN_DataFrame.ID'].astype(int)  # make sure  the data type

                # logger.critical(item.shape)
                item.index = pd.to_datetime(pd.Series(item.index), unit='s')
                measurement_name = filename + '_' + str(count)
                write_client.write(bucket, org, record=item, data_frame_measurement_name=measurement_name)
                count += 1
        toc = time.time()
        time_cost = toc - tic
...

**Comment by bednar** [comment]
Hi @grant-zhang666,

thanks for using our client.

> The first thing is that, I use multiprocessing and in every subprocess I create a write_client and use it write many dataframes into influxdb, but when all the dataframes have been writeen into influxdb, I try to close the write_client use write_client.close(), the subprocess wii be stuck here for a very long time, and i need to shutdown it manually.

How do you initialise the `write_client`? The default behaviour for the `write_client` is batching mode which ingesting data at the background thread. So the `write_client.close()` process remains data which isn't inserted into database, this is a reason for `stuck`.

For more info see https://github.com/influxdata/influxdb-client-python#writes

> So I want to know what happened here, could you give any advice, could python client support this kind of operation?
>
> Any advice will be appreciated.

You can follow this example to see how to correctly use multiprocessing for ingesting data: https://github.com/influxdata/influxdb-client-python/blob/master/examples/import_data_set_multiprocessing.py

Regards

**Comment by grant-zhang666** [comment]
@bednar thanks for your reply.
I initialise the `write_client` as follows:
```python
client = InfluxDBClient(url=url, token=token, org=org)
    write_client = client.write_api(write_options=WriteOptions(batch_size=1000,
                                                               flush_interval=10_000,
                                                               jitter_interval=2_000,
                                                               retry_interval=5_000,
                                                               max_retries=5,
                                                               max_retry_delay=30_000,
                                                               exponential_base=2))
```
I get the general idea of the multiprocessing example, that it uses a single subprocess to ingest *line protocol datapoinits* into Influxdb bucket, and uses other parallel subprocesses to create *line protocol datapoinits* for the ingesting subprocess. So the multiprocesing operation is used to create datapoints, but not used to ingest data into Influxdb. 
Therefore, I have another question: Is it feasible to use multiprocessing to ingest data into influxdb? Specifically, I create a `write_client` for every single subprocess which is used both for creating and ingesting datapoints. Does Influxdb support such operation? Or does it require only a single process ingesting data? Will multiprocessing data ingesting help improve the ingesting speed?

wish for your reply.
Regards

**Comment by bednar** [comment]
> Therefore, I have another question: Is it feasible to use multiprocessing to ingest data into influxdb? 

Yes, but your _line protocol_ has to have defined a `timestamp` for correct order of your data.

> Specifically, I create a write_client for every single subprocess which is used both for creating and ingesting datapoints.  Does Influxdb support such operation? 

Yes, with proper hardware sizing. For more info see - https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/#influxdb-oss-guidelines

> Or does it require only a single process ingesting data? 

No, the InfluxDB doesn't requires only one single process for ingesting data.

> Will multiprocessing data ingesting help improve the ingesting speed?

Yes, with proper hardware sizing at server side.

**Comment by grant-zhang666** [comment]
@bednar thanks for your reply.
> Yes, with proper hardware sizing. For more info see - https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/#influxdb-oss-guidelines
I have seen the hardware sizing guidelines. The good thing is that more cores and momery truely help improve the write performance of influxdb. And the guidelines recommand using **cluster with Influxdb Enterprise**. But I don't need a cluster, what I have is a high performance workstation with 64 cores and 252GB RAM, and I want to use all the hardware resouces to improve the wrting speed of influxdb efficiently. Do I need to do any configurations? If so, how to set the configuration to do the writing or ingesting data parallelly with multiprocessing utilizing all the hardware resources? 
I do not find enough info to achieve this. Could give me any advice or info?

**Comment by bednar** [comment]
> I have seen the hardware sizing guidelines. The good thing is that more cores and momery truely help improve the write performance of influxdb. And the guidelines recommand using **cluster with Influxdb Enterprise**. But I don't need a cluster, what I have is a high performance workstation with 64 cores and 252GB RAM, and I want to use all the hardware resouces to improve the wrting speed of influxdb efficiently. Do I need to do any configurations?

I am not export to operation of InfluxDB, but try to look at configuration options - https://docs.influxdata.com/influxdb/v2.1/reference/config-options/

> If so, how to set the configuration to do the writing or ingesting data parallelly with multiprocessing utilizing all the hardware resources? I do not find enough info to achieve this. Could give me any advice or info?

The main benefit of `python multiprocessing` is utilise the hardware resources on the client side.

**Comment by grant-zhang666** [comment]
@bednar Thanks a lot.

Best regards.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
