### ISSUE TITLE
Inconsistent Write Time

### ISSUE THREAD

**Issue by thanhdat6716** [influxdata/influxdb-client-python#418]
__Expected behavior:__

Hi Sir/Madam,

I have 5657 fields with various datatype: Boolean, Int, Float as a dictionary. I have three main threads to write my dictionary to InfluxDB.

1. Thread 1: Read data from OPC Server.
2. Thread 2: Update dictionary on OPC Server data changes.
3. Thread 3: Read dictionary and write to InfluxDB every 50ms.

As a test, I do not update my dictionary(fixed value) => on this test, my program only executes thread 3. The string size is 120200 bytes (line protocol). On every write, I write a log with Interval, Writing time, prepare data time.

__Actual behavior:__
This is the data result which I sorted in desc (write time): 142.81, 81.58, 73.14, 67.07, 66.28, 66.18, 65.63, 65.21, ..., 15.11, ...., 11.11,

As the log result, the writing time is not consistent, sometimes it takes really long execution time. I have no information about what impact affects the writing time.
As a consequence of the long execution time, my data on InfluxDB is also longer period.
I created a public GitHub repository for my source code which contains Python source, pickle dictionary, log file.
Resipotory: https://github.com/thanhdat6716/InfluxDB_Inconsistent

__Question:__

1. Could you help me to figure out why the writing time is inconsistent for the same data?
2. Is there any solution for stabilizing writing time?
4. Is there any solution for writing data faster?
5. As I divide the 5657 fields into multiple smaller group, the writing time is faster(the writing time take a long execution time at some datapoint). In this case, do multiple clients write to influxDB at the same time cause a bottleneck?

__Specifications:__
 - Client Version: 2.1.1
 - InfluxDB Version: 1.24.0
 - Platform: Windows 10
 - DB directory: defaut on SSD (SKHynix_HFM512GD3HX015N 512.1 GB) (Sequential Read	2,091 MBytes/Sec. Sequential Write	1,690 MBytes/Sec)
 - CPU: i7-1165G7
 - Memory: 40GB

Thanks & Best Regards!

**Comment by bednar** [comment]
Hi @thanhdat6716,

Thanks for using our client.

Just for quick clarification... Did you try python's `multiprocessing`?

The Python is not thread-safe and has to use `GIL` to switch context to second thread for processing generated writes. If you want to completely separate the "generation" and "writing" you have to use Python's multiprocessing. 

The client contains `influxdb_client.client.util.multiprocessing_helper.MultiprocessingWriter` to help user to write data in separate OS process - it is useful for latency sensitive use-cases.

For more info see: https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/util/multiprocessing_helper.py

Regards

**Comment by thanhdat6716** [comment]
Hi @bednar,
That's really helpful.
Thank you so much and have a great day!!
