### ISSUE TITLE
Chunk issue 

### ISSUE THREAD

**Issue by er-rahul-git** [influxdata/influxdb-client-python#420]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. If lower chunk size, we have to combine the result.
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version:
 - InfluxDB Version:
 - Platform:

**Comment by bednar** [comment]
Hi @er-rahul-git,

thanks for using our client.

> If lower chunk size, we have to combine the result.

Can you share a little bit more about your problem? Is there a way how to simulate it? Do you have a running code?

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
