### ISSUE TITLE
2 Quetions about query: "import" and query lots of fields

### ISSUE THREAD

**Issue by tk996958** [influxdata/influxdb-client-python#422]
Hello, I have 2 quetions about the query:

**1. If the influxdb-client-python support the "import"?**
In Flux, there some package, to use these package it needs import in Flux language. Something like below:

**_import "experimental/query"
query.inBucket(
    bucket: "example-bucket",
    start: -1h,
    stop: now(),
    measurement: "example-measurement",
    fields: ["exampleField1", "exampleField2"],
    predicate: (r) => r.tagA == "foo" and r.tagB != "bar",
)_**

But I try in python, it could not work. If in the influxdb-client-python 2.0 support the "import"? 
And if it support, how to use it correctly? Any simple example for test?

**2. How to query lots of fields?**
As the scripts below showing, that it could filter 3 fields:

_**from(bucket: stringParam)
  |> range(start: -5m, stop: now())
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r._field == "available" or r._field == "free" or r._field == "used")**_

But, if I want to filter 300 fields, if I must set a string like:

  **_|> filter(fn: (r) => r._field == "AA" or r._field == "BB" or r._field == "CC" or r._field =="DD" or or r._field =="EE"......)_**

You see, in such way, I need to write the **_r._field == "AA" or......_** 300 times, I think this is not vary convinient or is low efficiency. Are there any easy way to do this? Something like below? (like python use a in [list], so that I could just give the filter a list, that it could filter the item in the list for me):
 **_|> filter(fn: (r) => r._field in [AA, BB, CC, DD, EE......]_**

**Comment by bednar** [comment]
Hi @tk996958,

thanks for using our client.

> But I try in python, it could not work. If in the influxdb-client-python 2.0 support the "import"?
And if it support, how to use it correctly? Any simple example for test?

You can use Python's multiline string:

```python
from datetime import datetime

from influxdb_client import WritePrecision, InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
    query_api = client.query_api()

    p = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3).time(datetime.utcnow(),
                                                                                          WritePrecision.MS)
    client.write_api(write_options=SYNCHRONOUS).write(bucket="my-bucket", record=p)

    query = '''
            import "experimental/query"
            
            query.inBucket(
                bucket: "my-bucket",
                start: -1h,
                stop: now(),
                measurement: "my_measurement",
                fields: ["temperature"],
                predicate: (r) => r.location == "Prague",
            )
        '''

    tables = query_api.query(query)
    for table in tables:
        print(table)
        for record in table.records:
            # process record
            print(record.values)

```

> You see, in such way, I need to write the _r.field == "AA" or...... 300 times, I think this is not vary convinient or is low efficiency. Are there any easy way to do this? Something like below? (like python use a in [list], so that I could just give the filter a list, that it could filter the item in the list for me):
_|> filter(fn: (r) => r.field in [AA, BB, CC, DD, EE......]

You can use [contains() function](https://docs.influxdata.com/flux/v0.x/stdlib/universe/contains/). For more info about Flux, try to ask at our dedicated Slack channel: https://influxcommunity.slack.com/archives/CH8RGRW4T

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
