### ISSUE TITLE
The create_bucket method from buckets_management.py example doesn't work as documented

### ISSUE THREAD

**Issue by AbhigyaShridhar** [influxdata/influxdb-client-python#424]
__Steps to reproduce:__
Steps followed:

1. Import the relevant modules:
    `from influxdb_client import InfluxDBClient, BucketRetentionRules`
2. Declare the required fields:
    `
    url = "http://localhost:8086"
    token = "my-token"
    org = "my-org"
    ` 
3. Attempt creating a new bucket:
    `
    client = InfluxDBClient(url=url,token=token)
    `
    `
    retention_rules = BucketRetentionRules(type="expire",every_seconds=3600)
    `
    #create the bucket
    `
    created_bucket = client.buckets_api().create_bucket(bucket_name="bucket-by-python",retention_rules=retention_rules, org=org)
    `

Link to the example followed: https://github.com/influxdata/influxdb-client-python/blob/master/examples/buckets_management.py

__Expected behavior:__
A new bucket is created

__Actual behavior:__
Console threw the following error:
>raise ValueError("Invalid value for `org_id`, must not be `None`")  # noqa: E501
>ValueError: Invalid value for `org_id`, must not be `None`

__Specifications:__
 - Client Version: 1.27
 - InfluxDB Version: 2.1.1-alpine
 - Platform: Ubuntu 20.04.3 LTS

**Comment by bednar** [comment]
Hi @AbhigyaShridhar,

thanks for using our client.

The error is cause by missing organization with name 'my-org' in your InfluxDB database. The error message is not clear... so I will prepare PR to clarify problem.

Regards
