### ISSUE TITLE
Return useful feedback on successful write using write_options=SYNCHRONOUS via write_api

### ISSUE THREAD

**Issue by alexanderkjones** [influxdata/influxdb-client-python#431]
__Proposal:__
Provide return response on synchronous write through write_api. Currently I cannot find a way to check success of a write when `write_options=SYNCHRONOUS`.

__Current behavior:__
Currently the write_api only returns none when a write is performed synchronously while self._post_write appears to return the http response. 

write_api.py
```        
def write_payload(payload):
    final_string = b'\n'.join(payload[1])
    return self._post_write(_async_req, bucket, org, final_string, payload[0])

results = list(map(write_payload, payloads.items()))
    if not _async_req:
        return None
    elif len(results) == 1:
        return results[0]
    return results
```

__Desired behavior:__
The asynchronous write methods allow for a success callback and it would be ideal to have some success feedback from the write_api either as a callback that could be configured or simply http success response including data written. 

__Alternatives considered:__
Currently the only way I found around this issue is to use InfluxDBError to catch any exceptions, but this is not explicitly representing a successful write which would be preferred

```
with InfluxDBClient(url=self.url, token=self.token, org=self.org, enable_gzip=self.gzip) as client:
            with client.write_api(write_options=SYNCHRONOUS) as write_api:
                try:
                    write_api.write(self.bucket, self.org, lines, write_precision='ms')
                except InfluxDBError as e:
                    return {'status': 'error', 'message': 'Unable to write influx data', 'data': e}
                else:
                    return {'status': 'success', 'message': f'Influx data succesfully written to {self.bucket}', 'data': True}
``` 

__Use case:__
Why is this important (helps with prioritizing requests)?

I believe having a return on a a write request is important to instill confidence that the write has succesfully completed and for testing purposes to ensure proper operation. Currently in our tests we query the db to see if data was actually written which increase requests on the influx service and testing execution time.

**Comment by bednar** [comment]
Hi @alexanderkjones,

thanks for using our client.

The InfluxDB API returns HTTP code `204` as a result of write request without any additional information.

Why not use the following simplified code?

```python
with InfluxDBClient(url=self.url, token=self.token, org=self.org, enable_gzip=self.gzip) as client:
   try:
      client.write_api(write_options=SYNCHRONOUS).write(self.bucket, self.org, lines, write_precision='ms')
      return {'status': 'success', 'message': f'Influx data succesfully written to {self.bucket}', 'data': True}
   except InfluxDBError as e:
      return {'status': 'error', 'message': 'Unable to write influx data', 'data': e}
```

For more info see: https://docs.influxdata.com/influxdb/v2.2/write-data/troubleshoot/

Regards

**Comment by alexanderkjones** [comment]
Hi @bednar, 

Thanks for the response. It makes sense that a discrete return is not supported in the client as it appears not be supported by the API itself. The doc you linked was helpful as noted below partial rejections appear not to be returned in the API response which I believe is the root issue we're experiencing. 

> [Troubleshoot rejected points](https://docs.influxdata.com/influxdb/v2.2/write-data/troubleshoot/#troubleshoot-rejected-points)
InfluxDB may reject points even if the HTTP request returns “Success”. If some of your data did not write to the bucket, check for [field type](https://docs.influxdata.com/influxdb/v2.2/reference/key-concepts/data-elements/#field-value) differences between the missing data point and other points that have the same [series](https://docs.influxdata.com/influxdb/v2.2/reference/key-concepts/data-elements/#series). For example, did you attempt to write string data to an int field?

> InfluxDB` rejects points for the following reasons:

> The batch contains another point with the same series, but one of the fields has a different value type.
The bucket contains another point with the same series, but one of the fields has a different value type.
