### ISSUE TITLE
records with set time don't show up with flux

### ISSUE THREAD

**Issue by atticus-sullivan** [influxdata/influxdb-client-python#432]
Hi,
I'm trying to insert data while manually setting the date field. I'm doing so as explained in
https://github.com/influxdata/influxdb-client-python/blob/20c867d6516511fe73b0cae36c1705131cfa92f7/influxdb_client/client/write/point.py#L158
(but with `datetime.now()`)

The trouble is that such entries doesn't show up in `flux` queries (in `influxQL` queries they do). As I'm using `influx 1.8`
```bash
$ apt show influxdb
Package: influxdb
Version: 1.8.10-1
Priority: extra
Section: default
Maintainer: support@influxdb.com
Installed-Size: 148 MB
Depends: curl
Homepage: https://influxdata.com
License: Proprietary
Vendor: InfluxData
Download-Size: 50,7 MB
APT-Manual-Installed: yes
APT-Sources: https://repos.influxdata.com/debian bullseye/stable arm64 Packages
Description: Distributed time-series database.
```
I'm not sure if this might be a reason for the problem (nevertheless this python lib should work with `InfluxDB 1.8+`...).

I've created a small example below.

This is the python code first checking if the database is emtpty, then inserting a record with time set and then a record where the time isn't set.
```py
from datetime import datetime

from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

def printRes(query_api, bucket):
    tables = query_api.query(f'from(bucket:"{bucket}") |> range(start: -10m)')
    for table in tables:
        print(table)
        for row in table.records:
            print (row.values)

client = InfluxDBClient.from_config_file("config.ini")
query_api = client.query_api()
bucket = "test"

with client.write_api(write_options=SYNCHRONOUS) as write_api:
    print("before:")
    printRes(query_api, bucket)

    print("\ninsert with time set")
    now = datetime.now()
    print(now)
    p = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3).time(now)
    write_api.write(bucket=bucket, record=p)
    printRes(query_api, bucket)

    print("\ninsert without time set")
    now = datetime.now()
    print(now)
    p = Point("my_measurement").tag("location", "Prague").field("temperature", 30.0)
    write_api.write(bucket=bucket, record=p)
    printRes(query_api, bucket)

client.close()
```
Here's the output of that python code. You can see the first record that was inserted isn't visible.
```py
before:

insert with time set
2022-04-22 23:44:23.622783

insert without time set
2022-04-22 23:44:23.711761
FluxTable() columns: 9, records: 1
{'result': '_result', 'table': 0, '_start': datetime.datetime(2022, 4, 22, 21, 34, 23, 724684, tzinfo=datetime.timezone.utc), '_stop': datetime.datetime(2022, 4, 22, 21, 44, 23, 724684, tzinfo=datetime.timezone.utc), '_time': datetime.datetime(2022, 4, 22, 21, 44, 23, 701321, tzinfo=datetime.timezone.utc), '_value': 30.0, '_field': 'temperature', '_measurement': 'my_measurement', 'location': 'Prague'}
```
Now on the influx server I checked with `influxQL`. And oh now both records are visible.
```
> select * from my_measurement
name: my_measurement
time                location temperature
----                -------- -----------
1650663863701321959 Prague   30
1650671063622783000 Prague   25.3
```
To double check, I queried the database on the server with `flux` and this time the first record is missing as well.
```
> from(bucket:"test") |> range(start: -100m)
Result: _result
Table: keys: [_start, _stop, _field, _measurement, location]
                   _start:time                      _stop:time           _field:string     _measurement:string         location:string                      _time:time                  _value:float
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------
2022-04-22T20:09:12.413264374Z  2022-04-22T21:49:12.413264374Z             temperature          my_measurement                  Prague  2022-04-22T21:44:23.701321959Z                            30

```
So I obviously the record is stored in the database, but somehow `flux` queries aren't able to show them.

I'm not quite sure what's the problem here. I guess one possibility is that querying with `flux` is somehow buggy, but it might also be possible that somehow is wrong with this library and it's insertion routine.

To be honest, I don't have much  experience with `influx` (only discovered it today). So maybe someone of you can help me on this (and if the bug, if it is one and I'm not doing something wrong, isn't in this library, maybe you can help me finding the place where to report it to `influxdb`)

PS: Don't wonder why I wanted to manually set the time, I just wanted entries to have the same timestamp (for some reason)

**Comment by atticus-sullivan** [comment]
Switched to
```bash
$ sudo apt show influxdb2
Package: influxdb2
Version: 2.2.0
Priority:
Section:
Maintainer: support@influxdb.com
Installed-Size: 193 MB
Depends: curl
Recommends: influxdb2-cli
Conflicts: influxdb
Homepage: https://influxdata.com
Vendor: InfluxData
Download-Size: 110 MB
APT-Manual-Installed: yes
APT-Sources: https://repos.influxdata.com/debian bullseye/stable arm64 Packages
Description: Distributed time-series database.
```
Problem still remains.
(Since this was a problem with `mean()`, maybe it is relevant that I'm running `influxdb` on a Raspberry Pi 4)

**Comment by bednar** [comment]
Hi @atticus-sullivan,

thanks for using our client.

The `datetime.now()` is date in your local timezone but the InfluxDB expects dates in the UTC. The [range() function](https://docs.influxdata.com/flux/v0.x/stdlib/universe/range/) has `stop` parameter with default value to `now()` and this is a reason why you don't see the first point. The first point has timestamp in future.

![image](https://user-images.githubusercontent.com/455137/165030951-09b9c353-94d2-4022-8462-0a2659fe0a30.png)

Instead of `datetime.now()` use `datetime.utcnow()`.

Regards

**Comment by atticus-sullivan** [comment]
Well, thanks for explaining, my bad. Makes sense now (and sorry for bothering)
