### ISSUE TITLE
Feature Request: make working with pandas dataframe timestamps easier

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/influxdb-client-python#438]
Currently users have to do a bit of timestamp manipulation in order to write pandas DataFrames, for example:
![image](https://user-images.githubusercontent.com/30506042/168647474-e84ccf9a-013b-426a-a2ee-f4a416af622e.png)

The following features could make working pandas DataFrames easier:
- The ability to specify the timestamp column/not set the timestamp column as an index 
- The ability to specify the timestamp type and automatic conversation (like from ISO or rfc3339 timestamps to datetime objects).

**Comment by bednar** [comment]
Hi @Anaisdg,

thanks for the suggestion, we'll take a look. Do you have a sample data?

Regards

**Comment by rslippert** [comment]
In order to use a wider variety of time and date formats,
there should also be a timezone parameter specified.
It would help if the InfluxDb could generate a json template like what my software uses, 
it could generate this json data like it does when generating a token, see below:
{
    "influx_bucket": "rslippert's Bucket", 
    "influx_org": "d9ae8eef6f1bd6da", 
    "influx_token": "E3zGsMqgMrDYthxjfT921FXhipsOfGOIOxpcfvn61SnBE4D1mdgYKF5aYefaCbroy0UpBIsOEEMZr2XM96dtFg==", 
    "influx_url": "https://us-east-1-1.aws.cloud2.influxdata.com", 
    "timezone": "EST",
    "influx_version": "1.0"
}

**Comment by rslippert** [comment]
Attached is some sample data as requested:
[1dSCCOPLMCOPX.csv](https://github.com/influxdata/influxdb-client-python/files/8710982/1dSCCOPLMCOPX.csv)

**Comment by bednar** [comment]
@rslippert thanks for sharing your data

**Comment by bednar** [comment]
Hi @rslippert,

with upcoming #440 you will be able to use the following code:

```python
import pandas as pd

from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS

url = "http://localhost:8086"
token = "my-token"
org = "my-org"

with InfluxDBClient(url=url, token=token, org=org) as client:

    data_frame = pd.read_csv("path/to/1dSCCOPLMCOPX.csv")
    client \
        .write_api(write_options=SYNCHRONOUS) \
        .write(bucket="my-bucket",
               record=data_frame,
               data_frame_measurement_name="scco",
               data_frame_timestamp_column="Date",
               data_frame_timestamp_timezone="EST")
```

Regards

**Comment by rslippert** [comment]
I’m impressed by the speed and completeness of this pandas timestamp change. Great job Influx!

**Comment by Anaisdg** [comment]
Same thanks @bednar and @rhajek!!!
