### ISSUE TITLE
Wrap the for loops for table structure query or CSV library query

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/influxdb-client-python#445]
__Proposal:__
Create an option with the query api that allows the user to return the table structure values or CSV query directly without having to iterate over all of the tables and records. 

Having to iterate over the table structure as is can be useful to developers because it gives them the power to construct whatever object they need. However, I believe the iteration over the rows for the CSV library could be wrapped. 

__Current behavior:__
Currently if you want to use the table structure or CSV library when querying the data, you have to iterate across all of the tables and rows to return values. 
```
## using Table structure
tables = query_api.query('from(bucket:"my-bucket") |> range(start: -10m)')

for table in tables:
    print(table)
    for row in table.records:
        print (row.values)
```

```
## using the CSV library
csv_result = query_api.query_csv('from(bucket:"my-bucket") |> range(start: -10m)')
val_count = 0
for row in csv_result:
    for cell in row:
        val_count += 1
```

__Desired behavior:__
Describe what you want.
The ability to directly return a value or values in an array for the table structure. I don't think that this proposal should replace the current table structure but a helper function could simplify the UX for some users. 
```
## using Table structure
results = query_api.query('from(bucket:"my-bucket") |> range(start: -10m)').return(values)
## where results = [value1, value2, value3]
```
The ability to just return a CSV without having to iterate through rows for the CSV library. 
```
## using the CSV library
csv_result = query_api.query_csv('from(bucket:"my-bucket") |> range(start: -10m)')
## where csv_result returns the csv directly 
```

__Alternatives considered:__
The addition of a JSON library where you could return a JSON directly. Perhaps data is automatically pivoted with the fieldsAsCols() function so that key value pairs are derived from the column names.  
```
json_result = query_api.query_json('from(bucket:"my-bucket") |> range(start: -10m)')
[{_measurement: "<my measurement>",
_start: <start time>,
_stop: <stop time>, 
_time: <time1>, 
<field key>: <field value>, 
<tag key>: <tag value>}, 
{_measurement: "<my measurement>",
_start: <start time>,
_stop: <stop time>, 
_time: <time2>, 
<field key>: <field value>, 
<tag key>: <tag value>}]
```

__Use case:__
This is a UX enhancement to make returning data easier for the users. Just brainstorming for @sjwang90

**Comment by bednar** [comment]
Hi @Anaisdg,

thanks for your suggestions.

> ```
> ## using Table structure
> results = query_api.query('from(bucket:"my-bucket") |> range(start: -10m)').return(values)
> ## where results = [value1, value2, value3]
> ```

What is the `value1`? 

```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,location
,,0,2022-05-27T08:08:47.313914422Z,2022-05-27T08:18:47.313914422Z,2022-05-27T08:15:23.967Z,25.3,temperature,my_measurement,Prague
,,0,2022-05-27T08:08:47.313914422Z,2022-05-27T08:18:47.313914422Z,2022-05-27T08:15:31.139Z,27.3,temperature,my_measurement,Prague
```
 
Is it array of values?

```python
results = [
   [0, datetime(...), datetime(...), datetime(...), 25.3, "temperature", "my_measurement", "Prague"],
   [0, datetime(...), datetime(...), datetime(...), 27.3, "temperature", "my_measurement", "Prague"]
]
```

or content of `_value` column?

```python
results = [25.3, 27.3]
```

> The ability to just return a CSV without having to iterate through rows for the CSV library.
> 
> ```
> ## using the CSV library
> csv_result = query_api.query_csv('from(bucket:"my-bucket") |> range(start: -10m)')
> ## where csv_result returns the csv directly 
> ```

Can you please specify what the type of `csv_result` would be?

> **Alternatives considered:** The addition of a JSON library where you could return a JSON directly. Perhaps data is automatically pivoted with the fieldsAsCols() function so that key value pairs are derived from the column names.
> 
> ```
> json_result = query_api.query_json('from(bucket:"my-bucket") |> range(start: -10m)')
> [{_measurement: "<my measurement>",
> _start: <start time>,
> _stop: <stop time>, 
> _time: <time1>, 
> <field key>: <field value>, 
> <tag key>: <tag value>}, 
> {_measurement: "<my measurement>",
> _start: <start time>,
> _stop: <stop time>, 
> _time: <time2>, 
> <field key>: <field value>, 
> <tag key>: <tag value>}]
> ```
> 

It sound good 👍 

> **Use case:** This is a UX enhancement to make returning data easier for the users. Just brainstorming for @sjwang90

**Comment by Jayclifford345** [comment]
I like the idea of both the CSV and JSON return. For CSV return I would hope we could have two options a bit like CSV in Flux. Return raw CSV and return annotated. I do find our annotated flux CSV quite a mouthful so having the option to just spit out headers and values is also great. 

The JSON object I guess would almost be a JSON.dumps() if we followed the current raw table structure, We would just have to provide conversions for the returned DateTime maybe?

**Comment by rhajek** [comment]
The return type of `query_api.query_csv('...')` is iterable reader, which can iterate/stream response without need to keep all data in memory. It you want to load the result into memory as an array, you can use `csv_array = list(csv_result)`
