### ISSUE TITLE
Return data pivoted by default with option not to for pandas dataframes 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/influxdb-client-python#446]
__Proposal:__
Add the [fieldsAsCol() function](https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/fieldsascols/) to any query when the user is using the query_data_frame method. 

__Current behavior:__
Currently the fieldsAsCol() function is not added. Users have to do a lot of work with Pandas to manipulate the resulting dataframe into a shape that is compatible with most pandas libraries or they have to pivot their data beforehand. Not all users are aware of this option. 

__Desired behavior:__
The query_data_frame method adds the fieldsAsCol() function to your query by default. You can set this option to false. 
```
data_frame = query_api.query_data_frame('from(bucket:"my-bucket") '
                                        '|> range(start: -10m) '
                                        '|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") '
                                        '|> keep(columns: ["location", "temperature"])', pivoted= true)
```

__Alternatives considered:__
Documentation to encourage users to use the fieldAsCol() function. 

__Use case:__
This is a UX enhancement.

**Comment by Jayclifford345** [comment]
I second this! A great example was working with the [Solar dataset](https://github.com/Jayclifford345/Sunspots). It makes sense that the data comes back in the roundabout format it was sent in. I also like the ability to be able to toggle this feature on and off as I could see usecases where you want to return the data as is.

**Comment by bednar** [comment]
I am little bit afraid about this because it is a breaking change which break the users scripts. What do you think about default settings to `pivoted=false` and warning if the query doesn't contains the `schema.fieldsAsCols()` or `pivot(...)`?

**Comment by rhajek** [comment]
I agree that automatic pivoting is very common use case and also popular newcomer issue. But I think this UX enhancement is related more to Flux Language engine and Query API itself. 

Modify the Flux query snippet that is represented as a string on background in client library is not consistent, I am not sure if it is safe to simply append `schema.fieldsAsCols()` to all kinds of queries. Breaking backward compatibility in this case will cause that practically all existing scripts/examples/notebooks that uses pandas query will be broken.
