### ISSUE TITLE
Drop dependency on pytz in favor of zoneinfo

### ISSUE THREAD

**Issue by aDramaQueen** [influxdata/influxdb-client-python#447]
__Proposal:__
Hi, pytz is/was a good llibrary. But it's obsolete since [PEP 615](https://peps.python.org/pep-0615/). In the long run, you should not use this 3rd party package, but the language integrated functionality.
Even big frameworks like [Django](https://docs.djangoproject.com/en/4.0/releases/4.0/#what-s-new-in-django-4-0) start dropping pytz.

__Current behavior:__
Dependent from pytz

__Desired behavior:__
Independent from pytz

__Alternatives considered:__
Ignore it and hope pytz will be supported as long as possible.

__Use case:__
Dropping unnecessary dependencies leads to cleaner & less code. This reduces your effort to keep your dependencies up to date.

**Comment by bednar** [comment]
Hi @aDramaQueen,

thanks for suggestion. We will take a look.

Regards
