### ISSUE TITLE
Flux query issue python

### ISSUE THREAD

**Issue by Cosmingld** [influxdata/influxdb-client-python#451]
When using the code below, i get a typerror, error is the second output. I suspect there must be some issue with the query, any ideas?

```
from influxdb_client import Point, InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS
import os
from IPython.display import display
import pandas as pd
from IPython import display

INFLUX_ADDR = 'http://localhost:8086'
ORG = 'ORG'
BUCKET = 'BUCKET2'
TOKEN = '-A9oV1e7H3bEixtjv3f2q9APCRm83G7ypwi82d8LKixEiiyJ4vyysGT5kAlC9fWRSTVEnIqWuZlVEKqENvFMCA=='

client = InfluxDBClient(url=INFLUX_ADDR, token=TOKEN, org=ORG, debug=False)

query = '''
from(bucket: "BUCKET2")
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r["_measurement"] == "trades-BINANCE" or r["_measurement"] == "trades-FTX")
  |> filter(fn: (r) => r["_field"] == "price")
  |> filter(fn: (r) => r["symbol"] == "WAVES-USD-PERP")
'''
system_stats = client.query_api().query_data_frame(org=ORG, query=query)
display(system_stats.head())
```

```
Traceback (most recent call last):
  File "C:/Users/Cosimo/PycharmProjects/untitled/testredgears.py", line 29, in <module>
    display(system_stats.head())
TypeError: 'module' object is not callable
Exception ignored in: <function InfluxDBClient.__del__ at 0x09D596E8>
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\influxdb_client\client\influxdb_client.py", line 265, in __del__
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 84, in __del__
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 661, in _signout
TypeError: 'NoneType' object is not callable
Exception ignored in: <function ApiClient.__del__ at 0x09E1DE38>
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 84, in __del__
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 661, in _signout
TypeError: 'NoneType' object is not callable

Process finished with exit code 1
```

Also when i remove the display function, this is the error i get.

```
Exception ignored in: <function InfluxDBClient.__del__ at 0x0A0E9730>
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\influxdb_client\client\influxdb_client.py", line 265, in __del__
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 84, in __del__
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 661, in _signout
TypeError: 'NoneType' object is not callable
Exception ignored in: <function ApiClient.__del__ at 0x0A1ACE80>
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 84, in __del__
  File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 661, in _signout
TypeError: 'NoneType' object is not callable
```

**Comment by bednar** [comment]
Hi @Cosmingld,

thanks for using our client.

> When using the code below, i get a typerror, error is the second output. I suspect there must be some issue with the query, any ideas?
> 
> ```
> from influxdb_client import Point, InfluxDBClient
> from influxdb_client.client.write_api import SYNCHRONOUS
> import os
> from IPython.display import display
> import pandas as pd
> from IPython import display
> ```

I think the correct import of the `display` function is:

```
from influxdb_client import Point, InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS
import os
from IPython.display import display
import pandas as pd
```

> INFLUX_ADDR = 'http://localhost:8086'
> ORG = 'ORG'
> BUCKET = 'BUCKET2'
> TOKEN = '-A9oV1e7H3bEixtjv3f2q9APCRm83G7ypwi82d8LKixEiiyJ4vyysGT5kAlC9fWRSTVEnIqWuZlVEKqENvFMCA=='
> 
> client = InfluxDBClient(url=INFLUX_ADDR, token=TOKEN, org=ORG, debug=False)
> 
> query = '''
> from(bucket: "BUCKET2")
>   |> range(start: 0, stop: now())
>   |> filter(fn: (r) => r["_measurement"] == "trades-BINANCE" or r["_measurement"] == "trades-FTX")
>   |> filter(fn: (r) => r["_field"] == "price")
>   |> filter(fn: (r) => r["symbol"] == "WAVES-USD-PERP")
> '''
> system_stats = client.query_api().query_data_frame(org=ORG, query=query)
> display(system_stats.head())
> ```
> 
>  ```
> Traceback (most recent call last):
>   File "C:/Users/Cosimo/PycharmProjects/untitled/testredgears.py", line 29, in <module>
>     display(system_stats.head())
> TypeError: 'module' object is not callable
> Exception ignored in: <function InfluxDBClient.__del__ at 0x09D596E8>
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\influxdb_client\client\influxdb_client.py", line 265, in __del__
>   File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 84, in __del__
>   File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 661, in _signout
> TypeError: 'NoneType' object is not callable
> Exception ignored in: <function ApiClient.__del__ at 0x09E1DE38>
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 84, in __del__
>   File "C:\Python\lib\site-packages\influxdb_client\_sync\api_client.py", line 661, in _signout
> TypeError: 'NoneType' object is not callable
> 
> Process finished with exit code 1

The error can be caused by using wrong interpreter. It looks like that you use a _vanilla_ `python` but you are using `IPython` so you have to use `IPython` interpreter. Something like... `ipython my_script.py`.

Regards

**Comment by Crxnxss** [comment]
Do not forget to close client with "client.close()" at the end of the script.

**Comment by ebarti** [comment]
> 

I don't think this is needed. This is done on exiting.

**Comment by Cosmingld** [comment]
Thanks guys!
