### ISSUE TITLE
How to get the average timestamp using Flux

### ISSUE THREAD

**Issue by AsmaSaid** [influxdata/influxdb-client-python#452]
I need to get the average timestamp for a specific Measurement in InfluxDB 2.0 via the Flux query language

how can I achieve something close to below query:

from(bucket: bucket)
  |> range(start: 0, stop: now())
  |> filter(fn: (r) => r["_measurement"] == measurement)
  |> keep(columns: ["_time"])
  |> sort(columns: ["_time"], desc: false)
  |> mean(column: "_time") <<<<<<<< fix here

Thanks.

**Comment by bednar** [comment]
Hi @AsmaSaid,

thanks for using our client.

I am not expert to Flux Language, please try ask at our [Slack](https://influxcommunity.slack.com/archives/CH8RGRW4T) or [community forum](https://community.influxdata.com).

Regards
