### ISSUE TITLE
query API truncate _value to 2 decimal point

### ISSUE THREAD

**Issue by yashsonanitvp** [influxdata/influxdb-client-python#459]
I am using below query string,

        vIQ= '''from(bucket: "XXXX") 
                                            |> range(start: _start, stop: _end)
                                            |> filter(fn: (r) => r["_measurement"] == "Services") 
                                            |> filter(fn: (r) => r["ServiceName"] == _serviceName) 
                                            |> filter(fn: (r) => r["_field"] == _fieldName ) 
                                            '''
Creating Client as below,

            vClient= influxdb_client.InfluxDBClient(
                                url=InfluxDB_URL,
                                token=InfluxDB_TOK,
                                org=InfluxDB_ORG
                            )
           vQueryAPI = vClient.query_api()

Setup Params,

          vServiceName = "XXX"
          vResponseTimeParams = {
                              '_serviceName': vServiceName,
                              '_fieldName': "ResponseTime",
                              '_start': vStartTimeStamp,
                              '_end': vEndTimeStamp
                          }

Execute as Below,

                vTables = vQueryAPI.query(vIQ, params=vResponseTimeParams)

                for vTable in vTables:

                    for vRecord in vTable:
                        vKey = vRecord["_time"]
                        vResponseTimeMap[vKey] = vRecord["_value"]
                        print("vRecord", vRecord)

I am getting vRecord["_value"] value in 2 decimal where actual data in influxdb is 10 decimal. How to change decimal ?

Example : {'result': '_result', 'table': 0, '_start': datetime.datetime(2022, 5, 1, 0, 0, tzinfo=tzutc()), '_stop': datetime.datetime(2022, 5, 2, 0, 0, tzinfo=tzutc()), '_time': datetime.datetime(2022, 5, 1, 21, 58, tzinfo=tzutc()), '_value': 0.47, 'ServiceName': XXXX', '_field': 'ResponseTime', '_measurement': 'Services'}

**Comment by bednar** [comment]
Hi @yashsonanitvp,

thanks for using our client.

> I am getting vRecord["_value"] value in 2 decimal where actual data in influxdb is 10 decimal. How to change decimal ?

There is no settings for configure decimal places, it should be works out of box.

Can you share the `debug` output of the client?

```python
vClient= influxdb_client.InfluxDBClient(
                            url=InfluxDB_URL,
                            token=InfluxDB_TOK,
                            org=InfluxDB_ORG,
                            debug=True
                        )
```

Regards

**Comment by yashsonanitvp** [comment]
Hi @bednar ,

Please find below log,

send: b'POST /api/v2/query?org=#### HTTP/1.1\r\nHost: ####.####.com\r\nAccept-Encoding: identity\r\nContent-Length: 1345\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Token ####\r\nUser-Agent: influxdb-client-python/1.29.1\r\n\r\n'

send: b'{"extern": {"imports": [], "body": [{"type": "OptionStatement", "assignment": {"type": "VariableAssignment", "id": {"type": "Identifier", "name": "_serviceName"}, "init": {"type": "StringLiteral", "value": "####"}}}, {"type": "OptionStatement", "assignment": {"type": "VariableAssignment", "id": {"type": "Identifier", "name": "_fieldName"}, "init": {"type": "StringLiteral", "value": "ResponseTime"}}}, {"type": "OptionStatement", "assignment": {"type": "VariableAssignment", "id": {"type": "Identifier", "name": "_start"}, "init": {"type": "IntegerLiteral", "value": "1651363200"}}}, {"type": "OptionStatement", "assignment": {"type": "VariableAssignment", "id": {"type": "Identifier", "name": "_end"}, "init": {"type": "IntegerLiteral", "value": "1651449600"}}}]}, "query": "from(bucket: \\"####\\") \\n                                    |> range(start: _start, stop: _end)\\n                                    |> filter(fn: (r) => r[\\"_measurement\\"] == \\"Services\\") \\n                                    |> filter(fn: (r) => r[\\"ServiceName\\"] == _serviceName) \\n                                    |> filter(fn: (r) => r[\\"_field\\"] == _fieldName ) \\n                                    ", "dialect": {"header": true, "delimiter": ",", "annotations": ["datatype", "group", "default"], "commentPrefix": "#", "dateTimeFormat": "RFC3339"}}'

reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/csv; charset=utf-8
header: Vary: Accept-Encoding
header: X-Influxdb-Build: OSS
header: X-Influxdb-Version: 2.0.9
header: Date: Wed, 22 Jun 2022 12:28:47 GMT
header: Transfer-Encoding: chunked

**Comment by bednar** [comment]
It looks correct. 

Can you check the raw response from server?

```python
raw = vQueryAPI.query_raw(vIQ, params=vResponseTimeParams)
print(raw.data.decode('utf-8'))
```

**Comment by yashsonanitvp** [comment]
No luck.
Below is sample:
,result,table,_start,_stop,_time,ServiceName,_measurement,host,ResponseTime
,,0,2022-05-01T05:00:00Z,2022-05-02T05:00:00Z,2022-05-02T04:59:00Z,####,Services,####,0.47

**Comment by bednar** [comment]
> `,,0,2022-05-01T05:00:00Z,2022-05-02T05:00:00Z,2022-05-02T04:59:00Z,####,Services,####,0.47`

This is a raw response from the InfluxDB. The `0.47` has only two decimal points so the client works correctly. 

Did you try your query in the InfluxDB UI? How do you ingest your data into InfluxDB?

**Comment by yashsonanitvp** [comment]
![image](https://user-images.githubusercontent.com/90341600/175037622-23086f69-9a82-40cf-9b7d-f79f0b49c134.png)

**Comment by yashsonanitvp** [comment]
@bednar Hi Sir, Can you share me the link of actual code used for query method?

**Comment by bednar** [comment]
Hard to say where is a glitch... Is it problem for all your data or only particular subset? Can you double check that uses correct bucket and organization when you querying by client?

**Comment by yashsonanitvp** [comment]
Hi @bednar , I am sending data through Telegraf. Do you think it will cause the issue?

**Comment by bednar** [comment]
Hard to say, probably not, because on your [screenshot](https://github.com/influxdata/influxdb-client-python/issues/459#issuecomment-1163081616) there are correct data.

**Comment by yashsonanitvp** [comment]
Do you have any other solution which I can try?

**Comment by bednar** [comment]
Can you try query exactly one same record by InfluxDB UI and by `python` client? I think the problem is caused by your data in InfluxDB...

**Comment by yashsonanitvp** [comment]
Hi @bednar , I found the issue. In influxUI  ` |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) ` is used in all query, due to this I am getting the data as shown in screen shot. Telegraf sending data in 2 decimal only. Thanks for the help. This is not issue from library. We can close this issue.
