### ISSUE TITLE
InfluxDBClient default org is not used by WriteAPI

### ISSUE THREAD

**Issue by ptamilarasan** [influxdata/influxdb-client-python#46]
InfluxDBClient org parameter is documented as being the default for the query and write api, however only the QueryAPI client actually does this.  The WriteAPI client requires the org to be specified.

https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/influxdb_client.py#L28

https://github.com/influxdata/influxdb-client-python/blob/82ee030ebd5ec2ed87f1455d46188172e11acdad/influxdb_client/client/query_api.py#L34-L35

https://github.com/influxdata/influxdb-client-python/blob/82ee030ebd5ec2ed87f1455d46188172e11acdad/influxdb_client/client/write_api.py#L144

**Comment by russorat** [comment]
@ptamilarasan thanks for opening this! we will fix, but we'd be happy to review a community PR as well.

**Comment by bednar** [comment]
Hi @ptamilarasan,

The issue is fixed in [1.3.0 milestone](https://github.com/influxdata/influxdb-client-python/milestone/5). 

If you would like to use a dev version then install client via:

```pip install git+https://github.com/influxdata/influxdb-client-python.git@master```

Regards
