### ISSUE TITLE
pandas write client does not work

### ISSUE THREAD

**Issue by cosmo86** [influxdata/influxdb-client-python#463]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...using window11, intel 12th gen, Python 3.9.7
2. ...   
import h5py
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tables

dataframe look like this
<img width="662" alt="image" src="https://user-images.githubusercontent.com/51028745/178653209-c45ee58c-b1d1-45e0-b28c-0b38c4948424.png">

using the official tutorial : replacing the _data_frame with my own df shown in the last step
<img width="651" alt="image" src="https://user-images.githubusercontent.com/51028745/178653368-acc8c46f-81be-4ab6-98b3-d4122a37c690.png">

3. ...

__Expected behavior:__
Describe what you expected to happen.
expect the data to be written to the influxdb
__Actual behavior:__
Describe What actually happened.
nothing get written, the measurment wont even be created either, no error returnd to jupyter notebook console
__Specifications:__
 - Client Version:
 - InfluxDB Version:2.x
 - Platform:python

**Comment by cosmo86** [comment]
add: 
I am new to database, so sorry if the question is stupid 
thanks for the help

**Comment by bednar** [comment]
Hi @cosmo86,

thanks for using our client.

For the `jupyter` notebook will be better to use `synchronous` write API. Try to change initialisation of the `WriteApi` to:

```python
from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
    write_api = client.write_api(write_options=SYNCHRONOUS)

```

For more info see:

- https://influxdb-client.readthedocs.io/en/stable/usage.html#synchronous-client
- https://influxdb-client.readthedocs.io/en/stable/usage.html#write

**Comment by cosmo86** [comment]
Hi @bednar 
I just tried using your suggestion, but the issue still exist:

the notebook cell seems excuted the code just fine:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/51028745/178655356-bec156b0-9b69-4efb-b4b7-7f3678fed816.png">

but there is nothing in the database: i have refreshed the page
<img width="449" alt="image" src="https://user-images.githubusercontent.com/51028745/178655410-7ef5dc43-686f-4eef-9b25-ec5429381444.png">

**Comment by bednar** [comment]
Your timestamp is `1970-08-22 ...`. Do you have correct time range in InfluxDB UI?

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/455137/178655715-cb74a80f-d436-4f31-9283-375618bd8305.png">

**Comment by cosmo86** [comment]
@bednar 
like I said, I am stupid.
thanks for answering my question. I will close this issue.
If you dont mind, can i ask you another question?

Is aggregate function mandatory for displaying data in the UI?
Could I just display a column value VS the timestamp?

**Comment by bednar** [comment]
> Is aggregate function mandatory for displaying data in the UI? Could I just display a column value VS the timestamp?

You can switch to `Query Builder` and use your custom query:

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/455137/178661601-cc65b854-1512-4305-967f-486a3785401d.png">

**Comment by cosmo86** [comment]
@bednar  thanks a lot!
