### ISSUE TITLE
question of deleting all measurements

### ISSUE THREAD

**Issue by sleepgary** [influxdata/influxdb-client-python#466]
We're looking to use the API to delete all measurements from an InfluxDB 2.0 cloud instance.

We've set up a client as below, but I've been unable to find an example of how to delete all measurements based on this?

` client = InfluxDBClient(url = INFLUXDB_URL, token = INFLUXDB_TOKEN)` 
` delete_api = client.delete_api()` 
` start = "1970-01-01T00:00:00Z"` 
` stop = "2022-07-18T09:00:10.000Z"` 
` delete_api.delete(start, stop, '_measurement="?????"', bucket=BUCKET, org=ORG)` 

What strings can I type in those question marks?

**Comment by bednar** [comment]
Hi @sleepgary,

thanks for using our client. 

Did you try `empty` string... ''?

Regards

**Comment by sleepgary** [comment]
I tried empty string , but i got a error message like this:
`"urllib3.exceptions.ReadTimeoutError:HTTPConnectionPool(host='xx.xx.xx.xx', port=xxxx): Read timed out. (read timeout=9.984999999869615)"`

**Comment by bednar** [comment]
It looks like that the `delete` takes more than 10 seconds. Try to increase timeout by:

```python
client = InfluxDBClient(url = INFLUXDB_URL, token = INFLUXDB_TOKEN, timeout=30_000)
```

**Comment by sleepgary** [comment]
@bednar 
Thank for your helping! That works for me!
