### ISSUE TITLE
variable in the query string

### ISSUE THREAD

**Issue by defaliz** [influxdata/influxdb-client-python#474]
Hi,
i try to put variable in the query string like this :
bucket = "my_bucket"
a = measurement

query = 'from(bucket:my_bucket) |> range(start: -2d) |> filter(fn:(r) => r["_measurement"] == a )'
but it doesn't work...
how to put variable in the query string ?
regards

**Comment by bednar** [comment]
Hi @defaliz,

thanks for using our client.

Here is an example how to use query parameters: https://github.com/influxdata/influxdb-client-python/blob/c958ada2be86e87e25d8accd34b2c891f1ad41e1/examples/query.py#L33

Regards

**Comment by defaliz** [comment]
Thank bednar..
So I put my variable in quotes and that'll ? Like that..whith varabke "a"

bucket = "my_bucket"
a = measurement
query = 'from(bucket:my_bucket) |> range(start: -2d) |> filter(fn:(r) => r["_measurement"] == "a" )'

**Comment by bednar** [comment]
No, you have to use `a` without quotes. You can use something like:

```python
from influxdb_client import InfluxDBClient

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
    query_api = client.query_api()

    """
    Query: using Bind parameters
    """

    p = {"b": "my-bucket", "m": "my_measurement"}

    tables = client \
        .query_api() \
        .query('from(bucket: b) |> range(start: -2d) |> filter(fn:(r) => r["_measurement"] == m)', params=p)

    for table in tables:
        for record in table.records:
            print(record)

```

**Comment by defaliz** [comment]
Great ! I've seen params = p
Thank a lot !
Best regards..

**Comment by defaliz** [comment]
hi Bednar,
i've used your code and i 've always the same error when i use variables b and m
HTTP response body: b'{"error":"type error 1:79-1:80: undefined identifier \\"m\\""}\n'
but when i write directly measurement and bucket in quotes it's ok, like this :
bucket = "enedis_ad"
org = "_"
token = "xxxxxx"
with InfluxDBClient(url="http://localhost:8086", token=token, org=org, debug=False) as client:
query_api = client.query_api()
p = {"b": bucket, "m": "enedis_daily"}
tables = client \
        .query_api() \
        .query('from(bucket: b) |> range(start: -2d) |> filter(fn:(r) => r["_measurement"] == m )', params=p)

regards
