### ISSUE TITLE
query_api.query using only one core 100%, makes query too slow

### ISSUE THREAD

**Issue by YellaGoya** [influxdata/influxdb-client-python#484]
I`m tyring to use Python client for my project but it loads only one core 100%

test code querying COUNT() of 1 day ( 864,000 row, every 0.1sec ) error_code

>query = ' from(bucket: "samsung")\
|> range(start: 2022-04-20T00:00:00Z, stop: 2022-04-21T00:00:00Z)\
|> filter(fn: (r) => r["_measurement"] == "*****ng")\
|> filter(fn: (r) => r["_field"] == "Error_Code")\
|> count()'
temp = query_api.query(org=org, query=query)

is there any way to load all-core for querying?

__Expected behavior:__
load all cores 

__Actual behavior:__
load only one core 100%

__Specifications:__
 - InfluxDB Version:2.3.0
 - Platform:Ubuntu 20.04 LTS
 - Ryzen threadripper 24-core

**Comment by powersj** [comment]
Hi!

Thanks for using the Python client library.

> is there any way to load all-core for querying?

The query API call, sends a request to the `/api/v2/query` endpoint of InfluxDB. InfluxDB is what then handles the actual execution of the flux query. I am not sure you would see a huge improvement in splitting the query up by hour, and then joining the answer.

> test code querying COUNT() of 1 day ( 864,000 row, every 0.1sec )

If you are querying every tenth of a second, does it possibly make sense to modify your time range? Such that maybe you are only querying the last hour and keeping track of the previous hours?

As of now, I'm not sure I see how the library could be changed to help your use case, but let me know if I have missed something.

Thanks!
