### ISSUE TITLE
multiple queries in a single db call

### ISSUE THREAD

**Issue by NashTools** [influxdata/influxdb-client-python#489]
is it possible to send multiple queries to InfluxDB in a single API call ?

see: Multiple Queries in https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/

**Comment by powersj** [comment]
Hi,

The link you provided for the docs is from InfluxDB 1.7. If you are using that version of InfluxDB you should instead be using the [influxdb-python library](https://github.com/influxdata/influxdb-python), not this one.

This library, the influxdb-client-python, is meant to support InfluxDB Cloud, InfluxDB 2.x, and some limited support of InfluxDB 1.8.

In this version, the query API takes a [Flux query](https://docs.influxdata.com/influxdb/v2.3/query-data/flux/). There are a lot of features included with Flux, including [comparing across buckets](https://test2.docs.influxdata.com/influxdb/cloud/query-data/common-queries/compare-values/). That example shows multiple queries, but ultimately the need to return a single set of values.

Give those docs a read and see if any of them match your use-case.

Thanks!

**Comment by powersj** [comment]
Hi! Hopefully, the docs that I linked to helped out. I'm going to close this for now.
