### ISSUE TITLE
Does Async Write API support batching?

### ISSUE THREAD

**Issue by Aeroking21** [influxdata/influxdb-client-python#492]
Hi,

I want to upload a list of 200 Points at once to InfluxDB using the Async Write API. I'm not sure if the Async API supports batching and I'm not sure how to upload them at once.

**Comment by bednar** [comment]
Hi @Aeroking21,

>  I'm not sure if the Async API supports batching and I'm not sure how to upload them at once.

The `async` API doesn't supports the batching. You can use following example to look how to prepare batches for `async` API:

https://github.com/influxdata/influxdb-client-python/blob/master/examples/asynchronous_batching.py

> I want to upload a list of 200 Points at once to InfluxDB using the Async Write API

You can write these 200 point at once by: `await write_api.write(bucket="my-bucket", record=my_array)`. For complete example see: https://github.com/influxdata/influxdb-client-python/blob/20c867d6516511fe73b0cae36c1705131cfa92f7/examples/asynchronous.py#L27

Regards
