### ISSUE TITLE
Allow configuring retries with from_config_file

### ISSUE THREAD

**Issue by hterik** [influxdata/influxdb-client-python#506]
__Proposal:__
I would like to configure the API url using a config-file, and still have the option to configure the `retries` parameter in the `InfluxDBClient`

__Current behavior:__
1. Calling `InfluxDBClient.from_config_file`, proxies into `_BaseClient._from_config_file`.
2. `_BaseClient._from_config_file` calls _BaseClient constructor without the `retries`-parameter set, and no other option to tunnel through kwargs.
    https://github.com/influxdata/influxdb-client-python/blob/ee24b3ebaa18c262ceb8a89027b63cf9ebb4ae45/influxdb_client/client/_base.py#L169-L172
4. where `retries` is being read from kwargs, that was never passed in from the calls above:
    https://github.com/influxdata/influxdb-client-python/blob/ee24b3ebaa18c262ceb8a89027b63cf9ebb4ae45/influxdb_client/client/_base.py#L92

__Desired behavior:__
Either allow retries to be configured in the config-file, or add an additional parameter to `InfluxDBClient.from_config_file` that allows this to be set.

__Use case:__
Client-side retries is always important for a stable system. Without this option, the from_config_file function is very hard to motivate and instead one has call the InfluxDBClient constructor and provide all parameters manually.

**Comment by bednar** [comment]
Hi @hterik,

thanks for using our client.

I will change the signature of the `InfluxDBClient.from_config_file` to accept `**kwargs` which will be passed to the `_BaseClient.__init__`.

So you will be able to use something like:

```python
InfluxDBClient.from_config_file(retries=WritesRetry(total=3, retry_interval=1, exponential_base=2))
```

Regards

**Comment by bednar** [comment]
Hi @hterik,

the proposal is fixed in https://github.com/influxdata/influxdb-client-python/pull/510. 

You could try a dev version by: 

`pip install git+https://github.com/influxdata/influxdb-client-python.git@config_env_kwargs`

Regards
