### ISSUE TITLE
Why is python so slow

### ISSUE THREAD

**Issue by guodunwang** [influxdata/influxdb-client-python#515]
### Specifications

* Client Version: 1.33.0
* InfluxDB Version: 2.4
* Platform: win11

### Code sample to reproduce problem

```python

query2 = '''
from(bucket:"test")
        |> range(start: 2014-01-01T00:00:00Z, stop: 2014-02-01T00:00:38Z)
        |> filter(fn: (r) => r._measurement == "ceshi101003")
        |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
        |> drop(columns: ["_start", "_stop", "_measurement"])
'''

with InfluxDBClient(url="http://localhost:8086", token=my_token, org=my_org,timeout=1000000) as client:
    result2 = client.query_api().query_data_frame(org=my_org,query=query2)
    # print(result.tail(10))
    print(len(result2))

```

### Expected behavior

i wanta get the data in 1 min.

### Actual behavior

![image](https://user-images.githubusercontent.com/38942505/194998164-548d86f3-dfdb-4148-9d05-5c3151013d69.png)

### Additional info

Could it be faster?

**Comment by bednar** [comment]
Hi @guodunwang,

thanks for using our client.

The most time consumption part of your query is a parsing `_time` into Python `datetime` representation. Do you have installed the `ciso8601` to more performance parsing?

- https://github.com/influxdata/influxdb-client-python#installation

Regards

**Comment by guodunwang** [comment]
Thank you for your prompt reply. I have installed the ciso8681, but i just use "import ciso8601" in my python script and I don't know if it works when I execute my python script. Could you tell me how to use ciso8681 with the influxdb-client ? I could not find any other use of it in the README.rst.
![image](https://user-images.githubusercontent.com/38942505/195023061-8c47c6b4-0b99-4565-aceb-f13e9f0807b5.png)

**Comment by bednar** [comment]
You don't need to import `ciso8681` into your file. The client uses automatically if it is in your `python` path. You can check it by:

```
from influxdb_client.client.util.date_utils import get_date_helper
date_helper = get_date_helper()
print(date_helper.parse_date)
```

which will returns something like:

```
<built-in function parse_datetime>
```

How much time take your query in InfluxDB UI?

**Comment by guodunwang** [comment]
@bednar
Hi, bednar. It goes on like this for about 18 seconds and then it got stuck. According to my own stopwatch, it took 1min40s from the time the script was submitted until the results were tabulated. 
![image](https://user-images.githubusercontent.com/38942505/195847638-40873ab1-3dba-4589-a952-55eef85aae24.png)
Then, not long after the data was presented, the page crashed, I think that it's due to the size of the data, after all, there were 6000000+ points.

and now it takes about 1min10s to query 6646154 points in python script. The data is the same as what I show you two days ago. And I don't know  if this is a normal or optimal performance. Thank you for your attention.

**Comment by intelroman** [comment]
@guodunwang 
How much resources you have on your server .. do you endup swapping in the flux VM.
Check memory usage for influx server.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Comment by max0x7ba** [comment]
@guodunwang 

> @bednar Thank you for your prompt reply. I have installed the ciso8681, but i just use "import ciso8601" in my python script and I don't know if it works when I execute my python script. Could you tell me how to use ciso8681 with the influxdb-client ?

The timestamp formatting and parsing are unnecessary. `pandas.DataFrame` parses those formatted timestamps and that takes forever. `ciso8681` is a wrong solution because the timestamps must not be formatted in the first place.

The right solution https://github.com/influxdata/influxdb-client-python/issues/187#issuecomment-765347650

Not sure why this is not explained in `influxdb-client-python` documentation.
