### ISSUE TITLE
Write gzip file

### ISSUE THREAD

**Issue by chriszal** [influxdata/influxdb-client-python#522]
__Proposal:__
Write gzipped files on influxdb with python library

__Current behavior:__
If this already exists and i haven't managed to implement it please inform me but i havent managed to send a straight up binary array of a gzip compressed file.

__Desired behavior:__
I'm using an android application that collects data and compresses it into a gzip file. I send those files to a server and then using the python library i would like to be able to send them in the compressed form to influxdb. 

__Alternatives considered:__
I know this is possible with the api and a post request but im not sure if it would be possible or better with the python library.
__Use case:__
The data collected is a lot and in a mobile device so compressing it on the spot is a must. Decompressing it and then sending it to influxdb would take a lot of resources and time.

**Comment by bednar** [comment]
Hi @chriszal,

thanks for using our client.

How looks your data? Is it `json` or Line Protocol or ...? 

You can use the `python` library for ingesting structured data, for more info see - https://github.com/influxdata/influxdb-client-python/blob/master/examples/write_structured_data.py.

Unfortunately the library doesn't supports  ingesting GZIP file. You can only send gzipped HTTP request which contains Line Protocols. 

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
