### ISSUE TITLE
python influxdb check success boolean

### ISSUE THREAD

**Issue by Bra1nsen** [influxdata/influxdb-client-python#524]
Dear Developer,

how can one check back if the data reached influxdb cloud 2.x?

I use something like that:

```
        write_api = client.write_api(write_options=SYNCHRONOUS)
        p = influxdb_client.Point("Kameradom").field("Temperatur", temperature).field("Druck", pressure)
        write_api.write(bucket=bucket, org=org, record=p)
```

I just would like to get an boolean if write_api worked or not.

Sorry I know its not the right place to ask something like that but you guys can answer that within 30 seconds while I would have to google for 4 hours.Thanks

**Comment by bednar** [comment]
Hi @Bra1nsen,

thanks for using our client.

If the `write_api.write(bucket=bucket, org=org, record=p)` doesn't throws an error it means that data was successfully written.

Regards

**Comment by Bra1nsen** [comment]
thanks for the quick response. 

I just want to add a function, which reboots the weather station if data isnt arriving. I need some kind of a boolean return or similiar. thanks ahead

**Comment by bednar** [comment]
You can use something like this:

```python
from datetime import datetime

from influxdb_client import WritePrecision, InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
    p = Point("my_measurement") \
        .tag("location", "Prague") \
        .field("temperature", 25.3) \
        .time(datetime.utcnow(), WritePrecision.MS)

    try:
        client.write_api(write_options=SYNCHRONOUS).write(bucket="my-bucket", record=p)
        reboot = False
    except Exception as e:
        reboot = True

    print(f"Reboot? {reboot}")

```

**Comment by Bra1nsen** [comment]
great thanks

**Comment by Bra1nsen** [comment]
Hey bednar. I would like to add some kind of condition, so that it only reboots, if the data is not sent for longer than 5 minutes/ exception persists. 

I tried:

```
	except Exception as e:
		time.sleep(300)
		reboot = True	
```

in hope that the reboot boolean stays false after the `try: `  works again, but after the 300s the reboot gets true. 

I need something like, if Exception holds on for 5 minutes: reboot = True. thank you

**Comment by bednar** [comment]
You can keep `datetime` when the exception shows and compare this date with actual time.
