### ISSUE TITLE
Unable to use the buckets_api on Influx 1.8.10

### ISSUE THREAD

**Issue by Pitastic** [influxdata/influxdb-client-python#541]
### Specifications

* Client Version: 1.35.0
* InfluxDB Version: 1.8.10
* Platform: Linux (Ubuntu 20.04)

Reproduce:
- Create a new database with the buckets method

On Influx 1.8 I am dealing with databases and not yet with buckets. The only problem is, that there is no `client.create_database()` anymore. Thanks to your migration guide and the examples in this repo it is clear that I should use the `client.buckets_api()` for that instead. These API Endpoints don't exist on 1.8 what makes sense to me.

But as this should be backwards compatible with 1.8 is there a workaround for this or am I missing something?

### Code sample to reproduce problem

```python
from influxdb_client import InfluxDBClient, BucketRetentionRules

org = ''

with InfluxDBClient(url='http://myserver:8086', token='user:password', org=org) as client:
    buckets_api = client.buckets_api()
    retention_rules = BucketRetentionRules(type="expire", every_seconds=3600)
    created_bucket = buckets_api.create_bucket(bucket_name="bucket-by-python",
                                               retention_rules=retention_rules,
                                               org=org)
```

### Expected behavior

Create a "database" instead of a "bucket".

### Actual behavior

Endpoint for API call is not found.

### Additional info

```
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Tue, 20 Dec 2022 21:42:34 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```

**Comment by Pitastic** [comment]
Found [this old Issue](https://github.com/influxdata/influxdb-client-python/issues/259#issuecomment-851063669) which suggests to use `requests` to call the API v1 directly. Do I really have to 😋 ?

**Comment by bednar** [comment]
Hi @Pitastic,

thanks for using our client.

> But as this should be backwards compatible with 1.8 is there a workaround for this or am I missing something?

The client is not backwards compatible with 1.8. You can only use this client with [InfluxDB 2.0 API compatibility endpoints](https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-20-api-compatibility-endpoints). 



> Found [this old Issue](https://github.com/influxdata/influxdb-client-python/issues/259#issuecomment-851063669) which suggests to use `requests` to call the API v1 directly. Do I really have to 😋 ?

Yes, you have to, but every Pull Request is welcome. If you want to add a helper for this into client code base ... feel free to create PR.

Regards
