### ISSUE TITLE
I cannot connect to the cloud db

### ISSUE THREAD

**Issue by pjdervan** [influxdata/influxdb-client-python#55]
**InfluxDB version:** e.g. 1.7.9 
 **InfluxDB-python version:** e.g. 5.2.3 
 **Python version:** 3.7.4 
 **Operating system version:** macOS 10.14.5

 I cannot seem to connect to my cloud database. It works ok for a local db.

 Code is:

 import codecs
 from datetime import datetime

 from influxdb_client import WritePrecision, InfluxDBClient, Point
 from influxdb_client.client.write_api import SYNCHRONOUS

url = "https://eu-central-1-1.aws.cloud2.influxdata.com"
 token = "eJfb567aSoJnoDZJRaTI48lgzafILzOEaW70CEQqStin4xm9mboyYQO7dLJWVwRBXyLbrje9nvI6aXMJN1HlCg=="  
bucket = "Keithley2410"
org = "paul.dervan@liverpool.ac.uk"
user= "dervan"
password = "something"
 

client = InfluxDBClient(url=url, user=user, token=token, password=password)

Error is:

TypeError: __init__() got an unexpected keyword argument 'user'

If I use:

client = InfluxDBClient(url=url, token=token)

I get this error:

HTTP response body: {"code":"forbidden","message":"insufficient permissions for write"}

That bucket does have read/write permissions.

 Any help would be great.
 Paul

**Comment by bednar** [comment]
Hi @pjdervan,

We have an example how to connect to InfluxDB 2.0 Cloud - [influx_cloud.py example](https://github.com/influxdata/influxdb-client-python/blob/master/examples/influx_cloud.py).

Try use client same way... something like this:

```python
url = "https://eu-central-1-1.aws.cloud2.influxdata.com"
token = "eJfb567aSoJnoDZJRaTI48lgzafILzOEaW70CEQqStin4xm9mboyYQO7dLJWVwRBXyLbrje9nvI6aXMJN1HlCg=="
bucket = "Keithley2410"
org = "paul.dervan@liverpool.ac.uk"

client = InfluxDBClient(url=url, token=token)

point = Point(kind).tag('host', host).tag('device', device).field('value', 25.3).time(time=datetime.utcnow())

write_api = client.write_api(write_options=SYNCHRONOUS)
write_api.write(bucket=bucket, org=org, record=point)

client.close()
```

Regards

**Comment by pjdervan** [comment]
Hi,

I tried that swell and I get the following error:

HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 03 Feb 2020 12:59:54 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '67', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'x-platform-error-code': 'forbidden'})
HTTP response body: {"code":"forbidden","message":"insufficient permissions for write”}

I do have read and write.




But I don’t seem to provide a password or user id. Is there an init file I need to set up. Before or during the running of the program (eg an *.ini). 

Paul

____________________________________________________________________
Dr Paul Dervan                         
Liverpool ATLAS Upgrade ENDCAP Pixel 
University of Liverpool
Department of Physics
O. Lodge Laboratory
Oxford Street 
L69 7ZE         
Liverpool, 
UK
Tel:  +44 (0)151 794 3422    
Fax: +44 (0)151 794 6932
E-mail: paul.dervan@cern.ch

**Comment by bednar** [comment]
There is not an init file that should be set up. 

Please, try validate token via:

```bash
curl -i -X POST 'http://localhost:9999/api/v2/write?org=my-org&bucket=my-bucket' \
    -H 'Authorization: Token my-token' \
    -d 'h2o,location=west level=1'
```

If you renamed your organization, bucket or something else try generate new token.

**Comment by pjdervan** [comment]
Hmm. Seems its not authorised.

(base) Pauls-MacBook-Pro:~ dervan$ curl -i -X POST 'https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/write?org=paul.dervan@liverpool.ac.uk&bucket=Keithley2410'
HTTP/1.1 401 Unauthorized
Date: Mon, 03 Feb 2020 13:32:48 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 55
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
x-platform-error-code: unauthorized

{"code":"unauthorized","message":"unauthorized access"}(base) Pauls-MacBook-Pro:~ dervan$ 



____________________________________________________________________
Dr Paul Dervan                         
Liverpool ATLAS Upgrade ENDCAP Pixel 
University of Liverpool
Department of Physics
O. Lodge Laboratory
Oxford Street 
L69 7ZE         
Liverpool, 
UK
Tel:  +44 (0)151 794 3422    
Fax: +44 (0)151 794 6932
E-mail: paul.dervan@cern.ch

**Comment by pjdervan** [comment]
Hi Jakub,

It’s now working.

I just deleted the token. And re-made one.

Sorry for troubling you.

Paul
____________________________________________________________________
Dr Paul Dervan                         
Liverpool ATLAS Upgrade ENDCAP Pixel 
University of Liverpool
Department of Physics
O. Lodge Laboratory
Oxford Street 
L69 7ZE         
Liverpool, 
UK
Tel:  +44 (0)151 794 3422    
Fax: +44 (0)151 794 6932
E-mail: paul.dervan@cern.ch

**Comment by bednar** [comment]
No problem at all. I am glad that it works.
