### ISSUE TITLE
Version 1.3.0 on PyPi is incomplete

### ISSUE THREAD

**Issue by CharlesParent** [influxdata/influxdb-client-python#57]
Hello,
I just downloaded influxdb-client-python (1.3.0) from PyPi (https://pypi.org/project/influxdb-client/#files) in order to integrate it one of my project using buildroot.

It appears the archive does not include all the files (requirements.txt for example)
![image](https://user-images.githubusercontent.com/6388268/74017687-f6091800-4994-11ea-81cf-d31a6cd5929a.png)

I would like to integrate this python package in buildroot to be able to build it on one of my project. For now I will get the source directly from github but it could be nice to have all the sources on pypi.org

Please let me know if you need anything

**Comment by bednar** [comment]
Hi @CharlesParent,

thanks for using our client. 

We will fix it in milestone [1.4.0](https://github.com/influxdata/influxdb-client-python/milestone/6).

Regards

**Comment by CharlesParent** [comment]
@bednar Ok thank you very much !
