### ISSUE TITLE
Column Limit issue

### ISSUE THREAD

**Issue by MatinF** [influxdata/influxdb-client-python#575]
### Specifications

Writing pandas dataframe to InfluxDB Cloud 2.0 with Python client

### Code sample to reproduce problem

Using below repository:
https://github.com/CSS-Electronics/canedge-influxdb-writer

### Expected behavior

Expected all data to be written to InfluxDB. This works with our older accounts created about a year ago, but not on newly created accounts.

### Actual behavior

We get below error when trying to write data. The issue seems to be that we're trying to add more than 200 unique signals (i.e. fields) for the same measurement - and apparently that is not possible in newer versions of the cloud?

```
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 09 May 2023 09:01:43 GMT', 'Content-Type': 'application/json', 'Content-Length': '216', 'Connection': 'keep-alive', 'trace-id': 'a5e2abe810cb6c3f', 'trace-sampled': 'false', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Influxdb-Request-ID': '3402a4e1bf06f25e3e0b3d6523c10cde', 'X-Influxdb-Build': 'Cloud'})
HTTP response body: {"code":"invalid","message":"dml handler error: service limit reached: couldn't create columns in table E7DEAEE7; table contains 199 existing columns, applying this write would result in 267 columns, limit is 200"}
```

**Comment by powersj** [comment]
> Expected all data to be written to InfluxDB. This works with our older accounts created about a year ago, but not on newly created accounts.

Sorry no one ever commented on this. Newer accounts are using InfluxDB IOX-backed [are limited to 200 columns](https://www.influxdata.com/blog/time-series-data-cardinality-influxdb/#:~:text=To%20ensure%20queries%20stay%20performant,your%20data%20into%20multiple%20measurements.).

This isn't really an issue with the client libraries, so I am closing this.
