### ISSUE TITLE
Specify header name for from_config_file() function

### ISSUE THREAD

**Issue by Siirko** [influxdata/influxdb-client-python#585]
__Proposal:__
To be able to specify which header chose from a config file instead having by default "influx2" 

__Current behavior:__
When loading a config file via from_config_file() it is impossible to specify which header we want to load and 
load by default influx2 header

__Desired behavior:__
from_config_file(section="influx2", ...) 

__Use case:__
To be able to load / switch config more easily

**Comment by bednar** [comment]
Hi @Siirko,

thanks for your suggestion 👍 

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards

**Comment by Siirko** [comment]
> Hi @Siirko,
> 
> thanks for your suggestion 👍
> 
> Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.
> 
> Regards

If I times yes, but this is can be easily implemented on this file https://github.com/influxdata/influxdb-client-python/blob/77cac49181a6b7236a8a6a16d0e5939973006b52/influxdb_client/client/_base.py#L114 where 'influx2' is a argument of this function

**Comment by Siirko** [comment]
Functionality added with test, tell me if I need to add more test ....
