### ISSUE TITLE
Installation issue with debian12 bookworm

### ISSUE THREAD

**Issue by rolfeisenhut** [influxdata/influxdb-client-python#597]
Installation of python module is rejected, because package not found.

pip install influxdb-client  fails with message to use 

sudo apt install python3-influxdb-client

but htis module is not listed in the package store, so installation is rejected. 

Is there a nearby solution for this issue? 

regards Rolf 

message from pip...
pip install influxdb-client

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
------------------------------------------------------

and from 
sudo apt install python3-influxdb-client
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3-influxdb-client

**Comment by jules-ch** [comment]
you're trying to install `python3-influxdb-client` which does not exists.

Also when using the system `pip` command you're trying to install `influxdb-client` with the system python which is probably still python2 or python < 3.7.

The command line is trying to help you, saying 

```If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.

If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.

See /usr/share/doc/python3.11/README.venv for more information.
```

Have you tried creating a virtualenv with a python version supported by `influxdb-client` package ?

**Comment by bednar** [comment]
You have to install client via: `pip install influxdb-client`.
