### ISSUE TITLE
InfluxDBClient: client.health() returns "...AttributeError: 'InfluxDBClient' object has no attribute 'health'..."

### ISSUE THREAD

**Issue by integraciones-tiagora** [influxdata/influxdb-client-python#609]
### Specifications

* Client Version: influxdb 5.3.1 installed on Pycharm IDE
* InfluxDB Version: I think it is 1.7.9 running on top of Linux
* Platform: Python program runs on MacOS Ventura 13.5.1

Dear sirs:
I am running my Python script on PyCharm 2022.3.3 (Community Edition). My call to InfluxDB works OK, but I would like to add some checks to my program in case the connection fails.

I found that I should use the following sentences:

health = client.health()
if health.status == "pass":
    print("Connection OK")
else:
    print(f"Connection error: {health.message}!")

But my interpreter fails with the following error message:

 **_health = client.health()
AttributeError: 'InfluxDBClient' object has no attribute 'health'_**

¿ Do I need to upgrade my client? ¿Or is there any other available way to check the health of my connection?

Your help will be greatly appreciated
Best regards
 Rogelio

### Code sample to reproduce problem

```python
```
client = InfluxDBClient(host='10.235.2.19', port=8086, username='admin', password='nimda')
client.switch_database('telegraf')

health = client.health()
if health.status == "pass":
    print("Conexión exitosa a InfluxDB.")
else:
    print(f"Error de conexión a InfluxDB: {health.message}!")

### Expected behavior

I expect client.health() to return a pass or the error code

### Actual behavior

My program fails with the following error message:

 **_health = client.health()
AttributeError: 'InfluxDBClient' object has no attribute 'health'_**

**Comment by bednar** [comment]
Hi @integraciones-tiagora,

> ¿ Do I need to upgrade my client? ¿Or is there any other available way to check the health of my connection?

You have to use the `v2` client: https://github.com/influxdata/influxdb-client-python#pip-install. You are currently using the v1 client.

Regards
