### ISSUE TITLE
Can not write a point to the specific time (HH:MM:SS) using Point.time

### ISSUE THREAD

**Issue by tkaewplik** [influxdata/influxdb-client-python#620]
### Specifications

* Client Version: 1.39.0
* InfluxDB Version: v2.6.1 (server: 9dcf880, fontend: 5ba8e15) Update: v2.7.4 also has this issue
* Platform: Ubuntu 22.04.3 LTS (Jammy Jellyfish)

### Code sample to reproduce problem

```python
from influxdb_client import InfluxDBClient, Point
from influxdb_client.client.write_api import SYNCHRONOUS
from influxdb_client.domain.write_precision import WritePrecision

ORG = "org"
# ENDPOINT_URL = 'http://influxdb:8086'
BUCKET = 'table1'
TABLE_NAME = 'table1'
TOKEN = "XXXXX"
MEASUREMENT="_measurement"

client = InfluxDBClient(url="http://localhost:8086", token=TOKEN, org=ORG)

write_api = client.write_api(write_options=SYNCHRONOUS)

"""
Add Data
"""

p = Point(MEASUREMENT)

timestamp = "2023-12-05T21:20:32.001001231Z"        
p.time(timestamp, write_precision=WritePrecision.S)

fields = {"number": 1}

tags = {}
tags['tag1'] = "tag1"
tags['timeeeeeeee'] = timestamp

for tag in tags:
    p.tag(tag, tags[tag])

for field in fields:
    p.field(field, fields[field])

write_api.write(bucket=BUCKET, record=p)

"""
Close client
"""
client.close()
```

### Expected behavior

I tried to add my data point to the specific time in the past

### Actual behavior

```python
timestamp = "2023-12-05T21:20:32.001001231Z"        
p.time(timestamp, write_precision=WritePrecision.S)
```

<img width="1009" alt="image" src="https://github.com/influxdata/influxdb-client-python/assets/5256282/c2b34aeb-8f95-412c-8470-f77d7d7e7995">

I should get the data point on "2023-12-05T21:20:32.001001231Z"  but I got "2023-12-06T07:00:00.000Z" somehow.
it seems that the time of the day can not be saved to that specific point

**Comment by bednar** [comment]
Hi @tkaewplik,

thanks for using our client.

> I should get the data point on "2023-12-05T21:20:32.001001231Z" but I got "2023-12-06T07:00:00.000Z" somehow.
it seems that the time of the day can not be saved to that specific point

Please check the query which is used in InfluxDB UI, there is a probably the window aggregation function which cause the the timestamp is `2023-12-06T07:00:00.000Z`.
