### ISSUE TITLE
Missing Type Hints

### ISSUE THREAD

**Issue by hf-kklein** [influxdata/influxdb-client-python#622]
__Proposal:__
* There should be type hints in this library.
* The type hints shall be available to users of the library.
 
__Current behavior:__
* There are no type hints.
* When type checking my own code with mypy, I get the error message:
> error: Skipping analyzing "influxdb_client": module is installed, but missing library stubs or py.typed marker  [import-untyped]

__Desired behavior:__
* There shall be type hints in the code, especially in the user facing signatures.
* there shall be a `py.typed` file that is contained in the package (see [PEP 561](https://peps.python.org/pep-0561/)).

__Alternatives considered:__
None that I know of.

__Use case:__
* Better developer experience
* Type checks in code using this client (aka "Compile" time safety)

**Comment by bednar** [comment]
Hi @hf-kklein,

thanks for your suggestion.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards

**Comment by bednar** [comment]
@alespour it is already resolved in v3 client
