### ISSUE TITLE
ur patch is no longer working i have test it multiple time 

### ISSUE THREAD

**Issue by neonarc4** [influxdata/influxdb-client-python#624]
does this influxdb python has patch and delete ? 
```
patch_checks_id_async("xxxx", check)
``` plz fix the patch only put is working 
i have tired patch its no longer working can u plz check it

**Comment by neonarc4** [comment]
what is auth method?

**Comment by bednar** [comment]
Hello @neonarc4,

Thank you for bringing this issue to our attention. To better understand and resolve the problem you're experiencing, could you please provide us with a snippet of executable Python code that reproduces the issue with the non-working checks? Having a concrete example will help us pinpoint the problem and ensure that any fixes we apply directly address the issue you're facing.

Additionally, if you could provide any specific error messages, logs, or context on how this issue manifests in your environment, it would greatly aid our debugging efforts.

We appreciate your cooperation and are committed to resolving your issue promptly.

Thanks!
