### ISSUE TITLE
README.rst is not rendered correctly on GitHub

### ISSUE THREAD

**Issue by twrasmussen** [influxdata/influxdb-client-python#634]
### Specifications

* Client Version:
* InfluxDB Version:
* Platform:

### Code sample to reproduce problem

```python
```

### Expected behavior

Links to v1 client library in readme no longer linked to valid web page

### Actual behavior

Links to v1 client library in readme no longer linked to valid web page

### Additional info

Links to v1 client library in readme no longer linked to valid web page

**Comment by bednar** [comment]
The "rst" format is still supported, as seen here: [sphinx-readme README.rst](https://github.com/TDKorn/sphinx-readme/blob/main/README.rst). Therefore, we need to review the syntax of our README.rst to ensure it's correct.

**Comment by bednar** [comment]
The GitHub uses this project to convert RST to HTML - https://github.com/github/markup
