### ISSUE TITLE
Unable to install on Windows with and without Visual Studio

### ISSUE THREAD

**Issue by wojciechka** [influxdata/influxdb-client-python#65]
Issue reported in InfluxDB Community Slack (https://influxcommunity.slack.com/archives/CH8RV8PK5/p1582899056015100):
```
Collecting ciso8601>=2.1.1
  Using cached ciso8601-2.1.3.tar.gz (15 kB)
Installing collected packages: ciso8601, influxdb-client
    Running setup.py install for ciso8601 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\cmic\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\cmic\\AppData\\Local\\Temp\\pip-install-ssomainb\\ciso8601\\setup.py'"'"'; __file__='"'"'C:\\Users\\cmic\\AppData\\Local\\Temp\\pip-install-ssomainb\\ciso8601\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\cmic\AppData\Local\Temp\pip-record-dv948eri\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\cmic\appdata\local\programs\python\python38-32\Include\ciso8601'
         cwd: C:\Users\cmic\AppData\Local\Temp\pip-install-ssomainb\ciso8601\
    Complete output (12 lines):
    running install
    running build
    running build_py
    package init file 'ciso8601\__init__.py' not found (or not a regular file)
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\ciso8601
    copying ciso8601\__init__.pyi -> build\lib.win32-3.8\ciso8601
    copying ciso8601\py.typed -> build\lib.win32-3.8\ciso8601
    running build_ext
    building 'ciso8601' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

It seems that InfluxDB Python package depends on `ciso8601`, which requires compilation.

It seems that running `pip install ciso8601` without Visual Studio, with VS 2019 and VS 2015 all fails to compile `ciso8601`.

The package should have clearer instructions on how it should be installed on Windows.

Also, perhaps it is possible to not use `ciso8601` and use built-in `datetime` features if the said package is not available? So that if `ciso8601` is present, it is used, but otherwise it's still possible to use the client?

**Comment by bednar** [comment]
Hi @wojciechka,

we use `ciso8601` to parsing timestamps in query results. It's much faster than built-in `datetime`.

I am going to update `README` with instructions how to build client on Windows platform.

Regards

**Comment by bednar** [comment]
Hi @wojciechka,

for successfully installation client on Win platform you should install **Visual C++ Build Tools 2015**: [http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe](http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe). 

After that the `ciso8601` will be builded.

Regards
