### ISSUE TITLE
Add functionality to read from an InfluxDB backup without restoring data to InfluxDB instance

### ISSUE THREAD

**Issue by wolfig** [influxdata/influxdb-client-python#661]
__Proposal:__
I suggest to enhance the existing client or to create an additional client such that the client is able to read an InfluxDB backup data store without restoring it to a running InfluxDB instance. Via the client it shall be possible to perform simple queries to the data backed up before.

__Current behavior:__
To my knowledge, this is not possible to access the backup data store in a reasonable manner without restoring it to an InfluxDB instance.

__Desired behavior:__
* It shall be possible to extract data the backup data store without the need of restoring data to a live InfluxDB database instance.
* It shall be possible to limit the data extraction to: measurement, timeframe
* The extracted data shall be represented by a Pandas Dataframe

__Alternatives considered:__
Restore backup and extract data from live DB instance, drop data after extraction.

__Use case:__
In our environment, the database size needs to be kept below a quite small size on disk (256 GB). Hence, regulary backups of the database are created and the DB is wiped from data. However, administrators regularly get requests to access data (mostly of one single measurement) from already backed up data.

**Comment by bednar** [comment]
Hi @wolfig,

Thank you for your proposal and for your interest in enhancing our project. We currently do not have this type of function on our development backlog.

Given this, would you be interested in helping us implement it? We welcome contributions from our community, and your involvement could greatly accelerate the inclusion of this new function. If you're willing, we would be delighted to support you through the process and provide any necessary guidance or resources.

Please let us know if this is something you would be able to assist with, and we can discuss the next steps.

Best Regards
