### ISSUE TITLE
re-signing on session expire

### ISSUE THREAD

**Issue by amin-basiri** [influxdata/influxdb-client-python#668]
__Proposal:__
create new session on session expire when using username and password authentication.

__Current behavior:__
when using username and password authentication session will expire after a while.

__Desired behavior:__
i need to create new session when old session expired without re-initializing the client manually.

__Alternatives considered:__
also never expire feature (or remind me) may help

https://github.com/influxdata/ui/issues/6940

**Comment by bednar** [comment]
Hi @amin-basiri,

Thanks for using our client.

Regarding session renewal after expiration, our preferred method is token-based authorization, which we recommend using.

Best regards
