### ISSUE TITLE
The error asyncio.exceptions.CancelledError occurred while parsing the CSV.

### ISSUE THREAD

**Issue by kivdev** [influxdata/influxdb-client-python#671]
### Specifications

* Client Version: 1.46.0
* InfluxDB Version: 1.8.10
* Platform: Debian (docker)

### Code sample to reproduce problem

```python
async with InfluxDBClientAsync(url="http://localhost:8086", token="my-token", org="my-org") as client:
        # Stream of FluxRecords
        query_api = client.query_api()
        records = await query_api.query_stream(
        (
            'from(bucket:"{bucket}") |> range(start: {start}, stop: {stop})'
            '|> filter(fn: (r) => r["_measurement"] == "{measurement}")'
            '|> filter(fn: (r) => r.name == "{metric}")'
        ).format(
            bucket='metrics', start='2023-01-01T00:00:00Z', stop='2023-12-31T23:59:59Z', metric='http_request_total_count', measurement='http')
        )
        async for record in records:
            print(record)
```

### Expected behavior

Executed without errors.

### Actual behavior

```
File "/app/my_app/service.py", line 51, in get_influxdb_data
    async for record in records:
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/client/flux_csv_parser.py", line 141, in _parse_flux_response_async
    async for csv in self._reader:
  File "/usr/local/lib/python3.11/site-packages/aiocsv/readers.py", line 54, in __anext__
    return await self._parser.__anext__()
asyncio.exceptions.CancelledError
```

### Additional info

The error occurs only if there is a lot of data. (251,395 records with JSON content)

**Comment by bednar** [comment]
Hi @kivdev,

Thank you for reaching out with your issue. To better understand and address the problem you're experiencing, it would be incredibly helpful if you could share an example of how your data looks. An anonymized export from the InfluxDB UI would be ideal.

This information will allow us to accurately simulate your scenario and work towards a resolution.

Thanks a lot for your cooperation. Looking forward to your response.

Best Regards.

**Comment by kivdev** [comment]
Hi @bednar,

The data is stored as a string in the format [{"client": str, "requests": int, "date_report": str}, ....]. Unfortunately, I cannot provide a slice from the database.

**Comment by nastynaz** [comment]
I'm also having this error. I'm returning a query with 300k rows. Any updates?

**Comment by karel-rehor** [comment]
I've managed to reproduce this issue with the attached script.  [exploreIssue671.py.txt](https://github.com/user-attachments/files/17773888/exploreIssue671.py.txt)
```
$ python examples/exploreIssue671.py seed size 100000
$ python examples/exploreIssue671.py query
```

Will investigate further.

**Comment by karel-rehor** [comment]
After further investigation.  It appears the root cause is in the `aiohttp` library, which raises this exception when the timeout for the transaction has been exceeded.  A simple solution is to add a `timeout` parameter when instantiating the async client, whenever a large batch of response records is anticipated.  The default timeout value is currently 10_000 ms.   

For example
```python
async with InfluxDBClientAsync(url="http://localhost:8086", token="my-token", org="my-org", timeout=60_000) as client:
   ...
```
I'm opening a PR to more clearly handle this exception in this situation.
