### ISSUE TITLE
flux_table.py Linting (Bug and FIX)

### ISSUE THREAD

**Issue by youarecode** [influxdata/influxdb-client-python#674]
### Specifications

* Client Version: 1.46.0
* InfluxDB Version:
* Platform:

### Code sample to reproduce problem

**TableList** Typing is not working:
- just write (no need to execute) this in vscode, it may lead to a static linting error

```python
bucket='MyBucket'
measurement='MyMeasurement'
field='MyField'
query=f'''
        from(bucket: "{bucket}")
        |> range(start:0)
        |> filter(fn: (r) => r["_measurement"] == "{measurement}")
        |> filter(fn: (r) => r["_field"] == "{field}")
        |> last()
'''
client=InfluxDBClient(url, token, org)
query_api=client.query_api()
result=query_api.query(query)

MyValue=result[0].records[0].get_value() if result else False
MyTimestamp=result[0].records[0].get_time()  if result else False
```

### Expected behavior

Linting to work for:
- record field 'get_value()' or get_time()

### Actual behavior

SOLUTION:

Add typing here:
```python
# flux_table.py
class FluxTable(FluxStructure):
    def __init__(self) -> None:
        """Initialize defaults."""
        self.columns: List[FluxColumn] = []  #<<<<---- add this typing here
        self.records: List[FluxRecord] = []     #<<<<---- add this typing here
```

### Additional info

Thank you in advance

**Comment by bednar** [comment]
@youarecode thanks for using our client.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

**Comment by youarecode** [comment]
You are probably right, but to be honest, that line of code was my first contact with influxdb, 

Even for simple code I know nothing about the system. :)

**Comment by bednar** [comment]
Your code suggestion is fine and correct 👍

> SOLUTION:
> 
> Add typing here:
> 
> ```python
> # flux_table.py
> class FluxTable(FluxStructure):
>     def __init__(self) -> None:
>         """Initialize defaults."""
>         self.columns: List[FluxColumn] = []  #<<<<---- add this typing here
>         self.records: List[FluxRecord] = []     #<<<<---- add this typing here
> ```
> 

Once you’ve submitted the PR, I’ll review it as soon as possible. If there are any further adjustments needed, I’ll provide feedback through the GitHub PR comments.

You’re on your way to becoming one of our contributors ;)

**Comment by youarecode** [comment]
Thx you very much, I'll do it in a couple of hours
