### ISSUE TITLE
_time value set to January 1, 1970, 00:00:00 at UTC in all write functions

### ISSUE THREAD

**Issue by MayankSharma-MS** [influxdata/influxdb-client-python#71]
While using _write_client.write method, every write is setting _time to January 1, 1970, 00:00:00 at UTC irrespective of value passed.

sample code
in_client = InfluxDBClient(url=URL, token=TOKEN, org=my_org, debug=True)
_write_client = in_client.write_api(write_options=WriteOptions(batch_size=500,
                                                            flush_interval=10_000,
                                                            jitter_interval=2_000,
                                                            retry_interval=5_000))
_write_client.write(bucket_id, my_org,[f'pollution_test,tag_name=tag_val pollution_level="HIGH" {int(time.time())}', f'pollution_test,tag_name=tag_val pollution_level="LOW" {int(time.time())}'])

**Comment by bednar** [comment]
Hi @MayankSharma-MS,

`time.time()` - Return the current time in seconds since the Epoch => you have to specify time precision to Seconds.

```python
_write_client.write(bucket_id, my_org,
                    [f'pollution_test,tag_name=tag_val pollution_level="HIGH" {int(time.time())}',
                     f'pollution_test,tag_name=tag_val pollution_level="LOW" {int(time.time())}'], 
                    write_precision=WritePrecision.S)
```

Regards

**Comment by MayankSharma-MS** [comment]
Great, this works for Line Protocol. Thanks bednar for quick response.
Two follow up questions:
1) What can be used for Mili and Micro second in WritePrecision?
2) Does this works the same way for Dictionary-style object?
sample code for Dictionary-style object with WritePrecision in seconds
_write_client.write("my-bucket", "my-org", {"measurement": "h2o_feet", "tags": {"location": "coyote_creek"}, "fields": {"water_level": 1.0}, "time": time.time()}, "write_precision": WritePrecision.S)

**Comment by bednar** [comment]
1. For Mili: `WritePrecision.MS`, for Micro: `WritePrecision.US`
1. Yes

**Comment by MayankSharma-MS** [comment]
Thanks again @bednar
