### ISSUE TITLE
How to save annotation point or annotation window?

### ISSUE THREAD

**Issue by vit1251** [influxdata/influxdb-client-python#83]
If you are doing research that can be divided into stages, then you may want to save these stages in InfluxDV and display them in charts later. I found "Annotation" as well tools for that. But no idea how to set Annotation pin or annotation window with ```influxdb-client-python```? I want to get result like shown on screenshot below:

![image](https://user-images.githubusercontent.com/110534/79225241-1ce83c80-7e65-11ea-9958-0c4ed75b1300.png)

Could you please help me with set annotation pin and annotation window.

**Comment by bednar** [comment]
Hi @vit1251,

Can you please share a bit more detail what kind of problem you have?

* example of your python code
* StackTrace
* ....

Regards

**Comment by vit1251** [comment]
Yes. Example us better way to understand how to add new annotation in Chronograph. Thanks.

**Comment by bednar** [comment]
If its not related to the python client, please try to ask in our Slack Channel: https://www.influxdata.com/slack or Community site: https://community.influxdata.com

**Comment by vit1251** [comment]
> If its not related to the python client, please try to ask in our Slack Channel: https://www.influxdata.com/slack or Community site: https://community.influxdata.com

Hmm.. Look like set pin annotation is some kind of InfluxDB protocol but I does not understand how to do this job over ```influx-client```.

Thanks.
